### ISSUE TITLE
PoDoFo creates unreadable PDFs when OpenSSL RC4 is not available and PODOFO_HAVE_OPENSSL_NO_RC4 is set

### ISSUE THREAD

**Issue by derreisende77** [podofo/podofo#1]
I am using PoDoFo vcpkg 0.9.7 and 0.9.8 packages with OpenSSL.
Until OpenSSL 3.0.2 it had RC4 encryption included and the following code to encrypt a pdf file worked flawless:
```c++
doc.SetEncrypted("",
                             "hello",
                             PoDoFo::PdfEncrypt::ePdfPermissions_Print |
                             PoDoFo::PdfEncrypt::ePdfPermissions_Accessible |
                             PoDoFo::PdfEncrypt::ePdfPermissions_HighPrint,
                             PoDoFo::PdfEncrypt::ePdfEncryptAlgorithm_AESV2,
                             PoDoFo::PdfEncrypt::ePdfKeyLength_128);
```

With OpenSSL 3.0.2 RC4 encryption got disabled.
Trying to encrypt a pdf with the above command failes with a internal logic error thrown (as somehow expected).

I recompiled PoDoFo and added `ADD_DEFINITIONS(-DPODOFO_HAVE_OPENSSL_NO_RC4)` to `CMakeLists.txt` to disable RC4 OpenSSL support.
This way the above command does not throw an exception anymore and a encrypted PDF is created. **But when trying to open the file it asks for a password and all inputs are incorrect.**
To me it looks like the passwords get garbled when RC4 support is not available for PoDoFo.

**Comment by ceztko** [comment]
First sorry but I don't personally test OpenSSL 3.0 nor I'm ready to switch to it yet. My plan for PoDoFo-next (what will happen after 0.9.8) is mandating OpenSSL, so it will no be possible to compile PoDoFo without OpenSSL anymore. As you say OpenSSL 3.0 by default doesn't expose RC4, but internally it seems it will be still be internally [supported](https://github.com/openssl/openssl/blob/abe90105ba0908d5a2f500997f2bf2fceb263acd/providers/implementations/ciphers/cipher_rc4.c#L13) for an indefinite amount of time. So the solution may be enabling RC4 in OpenSSL when compiling PoDoFo, maybe unsetting [`OPENSSL_NO_DEPRECATED_3_0`](https://github.com/openssl/openssl/blob/master/include/openssl/rc4.h). We should probably require OpenSSL to have some more granular macros to enable some selected functions that are necessary to support popular formats like PDF.

**Comment by ceztko** [comment]
I put the hands on OpenSSL 3.x and I added support to [pdfmm](https://github.com/pdfmm/pdfmm/commit/682ac34514ce9b118a695dd2d06feda814064e13). Soon openssl 3.x support will be in podofo-next as well.

**Comment by ceztko** [comment]
PoDoFo-next is up and OpenSSL 3.0 support is partially there. Still missing:
1. Fix a couple of deprecation warnings for the use of deprecated methods;
2. All construction of contexts must use the SSL PoDoFo private engines, so there shouldn't be conflicts if other codes in the process use OpenSSL.

**Comment by ceztko** [comment]
OpenSSL 3.0 proper support should now be checked in https://github.com/podofo/podofo/commit/55c2ffd53b9eff2ac0418b3bce1a29e9a6688359
