### ISSUE TITLE
Convert from HTML Readme to Markdown Readme

### ISSUE THREAD

**Issue by KunalGehlot** [podofo/podofo#10]
Create a Markdown version of the README to make the project more accessible to people visiting the GitHub page.

**Comment by ceztko** [comment]
Thank you again for your branch 0.9.x Markdown conversion. As said, PoDoFo-next (soon 0.10) already had a MD readme. I don't have energies now to integrate some 0.9.x readme content into it, and as said I believe it was way too much verbose than what's needed in today's standards. I close the issue for now, but feel free to create a new issue later if nothing happens and you would like to see some content from the old one in the newer.
