### ISSUE TITLE
App fails to compile with podofo and XCode 15 RC due to no matching function for call to 'operator=='

### ISSUE THREAD

**Issue by derreisende77** [podofo/podofo#100]
* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [x] Bug report
  - [ ] Feature request/suggestion

* **[Bug report] What is the current behavior?**
When compiling my app on macOS Sonoma RC with Xcode 15 RC compilation fails with the following error:
```
In file included from /Users/XXX/Downloads/test/orgelemtreeviewer/pdfgenerator.cpp:1:
In file included from /Users/XXX/Downloads/test/orgelemtreeviewer/pdfgenerator.h:11:
In file included from /Users/XXX/Downloads/test/orgelemtreeviewer/cmake-build-release/vcpkg_installed/arm64-osx/include/podofo/podofo.h:22:
In file included from /Users/XXX/Downloads/test/orgelemtreeviewer/cmake-build-release/vcpkg_installed/arm64-osx/include/podofo/auxiliary/StreamDevice.h:15:
/Users/XXX/Downloads/test/orgelemtreeviewer/cmake-build-release/vcpkg_installed/arm64-osx/include/podofo/auxiliary/basetypes.h:96:16: error: no matching function for call to 'operator=='
        return std::operator==(lhs, (std::string_view)rhs);
```
* **[Bug report] What is the expected behavior?**
Compilation of the source code should work flawlessly. The same code compiles fine on Xcode 14.

* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**
Create a minimum c++ application and include <podofo.h>, then compile.

* **Please tell us about your environment:**
  
  - Version/git revision: [1.10.0]
  - Operating System: macOS Sonoma RC
  - Package manager used: vcpkg latest
```
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.0.0
Thread model: posix
```

* **[Bug report/Feature request] Other information**
Successful compilation can be achieved by commenting out L93-L97 in `basetypes.h`:
```
/*template <typename = void>
    bool operator==(const char* lhs, const charbuff_t<>& rhs)
    {
        return std::operator==(lhs, (std::string_view)rhs);
    }*/
```
  I am not familiar enough with c++ to figure out why it fails on Xcode 15.

**Comment by ceztko** [comment]
This is already fixed in 0.10.1
