### ISSUE TITLE
Subsetting .ttc does not work, InitTables() reads the header as if it is a .ttf

### ISSUE THREAD

**Issue by SebastianKotewitz** [podofo/podofo#101]
* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [X] Bug report
  - [ ] Feature request/suggestion

* **What is the current behavior?**
When adding a font of .ttc format and enabling *embedding* and *subsetting*, the subsetting fails during InitTables. Saving the document fails during the font embedding stage.
InitTable reads the .ttc file header as if it was a .ttf file, so the tableCount is incorrectly set to the version of the .ttc format used (in my case 2).

* **What is the expected behavior?**
The font should be subset and embedded just like a .ttf font would. It would require knowing what font face idx should be used, and then reading the .ttc header to find the offset of the correct font

* **Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**
Create a PDFMemDocument and load any .ttc font into it with *embedding* and *subsetting* enabled.
In my case, I used SearchFont("MS UI Gothic"), which should come installed on windows. It is the second face included in the collection.
Add some text to the document using the font.
Save the document.

* **Please tell us about your environment:**
  
  - Version/git revision: [1.10.0]
  - Operating System: [ Windows (64 bits) ]
  - Package manager used: [ vcpkg ]

* **Other information**
Embedding the font without subsetting it works (as expected, since the issue comes from subsetting and reading the header)
I am not at the pc right now, but I can attach a PDF and/or code to reproduce the issue when I get to it if needed.

**Comment by ceztko** [comment]
This proved to be challenging as FreeType doesn't easily allow to extract TrueType fonts from TTC fonts.

**Comment by ceztko** [comment]
Some context in the FreeType devel mailing list[1].

[1] https://www.mail-archive.com/freetype-devel@nongnu.org/msg13637.html

**Comment by ceztko** [comment]
I'm definitely leveraging CMap CID mappings to define the encoding and like you noticed this allows for efficient subsetting. CID mappings are well described in the PDF specification since at least PDF 1.2 so I'm assuming these readers not able to render them to be uncompliant, so you should report them. Anyway, can you post a sample PDF specifying which readers are not able to render them?

> as neither implementation is necessarily more correct than the other.

Well, Adobe created PDF so I generally give Adobe implementations more credit, even if they don't always closely follow the specification they wrote.

**Comment by SebastianKotewitz** [comment]
[font_embedding_sample.pdf](https://github.com/podofo/podofo/files/13166014/font_embedding_sample.pdf)
I quickly put a document together with two pieces of text. 
The document reads fine in these readers:
 - Chromium
 - Firefox
 - Adobe Acrobat

Only the lower text is rendering in the following reader:
 - Bluebeam Revu 21


The upper text font is created using SearchFontMetrics followed by GetOrCreateFontFromBuffer based on those metrics. It is automatically subset.

The lower text font is created using SearchFontMetrics followed by GetOrCreateFontFromBuffer based on those metrics, but with the following PdfFontCreateParams
![image](https://github.com/podofo/podofo/assets/32564200/887d60bc-fa4a-4e91-bb86-45cb6ac8a6cd)
This may not be optimal, but it forces the font to use Identity-H encoding and displays correctly in the offending reader, so it should be ok as a demonstration.

I have also had issues with unicode mapping in Bluebeam, where some text was being extracted incorrectly (but worked fine in other readers).



> > as neither implementation is necessarily more correct than the other.
> 
> Well, Adobe created PDF so I generally give Adobe implementations more credit, even if they don't always closely follow the specification they wrote.

I just meant that both implementations should be legal, and I would therefore argue that it should not be necessary to implement a different way of subsetting fonts in PoDoFo based on one reader being unable to render the current (legal) implementation.

**Comment by ceztko** [comment]
> The document reads fine in these readers:
> [...]
> Adobe Acrobat

Please retry with latest Adobe Acrobat Reader: with your sample lower text does not really work. I'm not sure if what you are trying to do should work or it is guaranteed to not work at all, but sorry I can't spend time in supporting you manually plugging encodings: 100% of the recent effort in PoDoFo was put in giving you the most efficient PDF, allowing to insert strings in Unicode without caring about the internals for the encoding. You should really report to Bluebeam that a licit PDF is not rendered correctly. If you want to follow other approaches you're free to try it, but you'll be on your own.

**Comment by SebastianKotewitz** [comment]
I admit the sample might not be 100% what my main writer does; it was just quickly put together in an isolated context and quickly checked in firefox and bluebeam. I'll make sure to check the latest Adobe Acrobat Reader.

I absolutely understand your stance on fonts in PoDoFo, and I would prefer if I could just use your method of embedding and subsetting fonts. I'll have to contact BlueBeam about the issue.
Thank you for your time.
