### ISSUE TITLE
test fails when built with optimizations

### ISSUE THREAD

**Issue by eli-schwartz** [podofo/podofo#103]
Compiled against git master (commit da8a1b9ca8cedbf61f9a9b242608267c62de9dea).
```
$ ./target/podofo-unit testCMYKConstructor
Filters: testCMYKConstructor

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
podofo-unit is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
testCMYKConstructor
-------------------------------------------------------------------------------
/tmp/podofo/test/unit/ColorTest.cpp:362
...............................................................................

/tmp/podofo/test/unit/ColorTest.cpp:429: FAILED:
  REQUIRE( color.ConvertToRGB() == PdfColor(1.0 - dRed, 1.0 - dGreen, 1.0 - dBlue) )
with expansion:
  {?} == {?}

===============================================================================
test cases:  1 |  0 passed | 1 failed
assertions: 12 | 11 passed | 1 failed
```

This was discovered on x86_64, but in particular, it only happens for me when I build with optimizations: `CXXFLAGS="-march=native -O2"`.

It also appears to be triggered by `-march=x86-64-v3` on its own, but *not* `-march=x86-64-v2`, which should narrow it down a lot more.

_Originally posted by @eli-schwartz in https://github.com/podofo/podofo/issues/6#issuecomment-1731237023_

**Comment by eli-schwartz** [comment]
Note that setting `-ffp-contract=off` makes podofo compile correctly even with optimizations, as far as the test case is concerned.

**Comment by ceztko** [comment]
What's the error (distance from expected value)? Because if it's a small epsilon it could be just an approximation issue.

**Comment by eli-schwartz** [comment]
The error message I posted has all the information I was able to get at the time. I was wondering whether `{?} == {?}` was the failure logger failing to show the actual context of the failure...

I don't know much about PDF other than building and using calibre (the ebook library software) that depends on podofo. I'd be happy to run whatever tests you'd like me to run but I'll probably need a bit of guidance.

**Comment by ceztko** [comment]
I was able to reproduce and the culprit is `-march=x86-64-v3`. An optimization seems to cause numerical values generated with the same formula, data and data types do produce different results at different code locations (compare for example https://stackoverflow.com/questions/62353629/does-the-same-floating-point-calculation-producing-different-results-when-perfor). I think the only fix is to compare the values with a tolerance.

**Comment by ceztko** [comment]
Fixed, thank you for the report.

**Comment by eli-schwartz** [comment]
Thanks for the fix (which I'm now backporting). Happy to see that I was just being over-cautious. :)
