### ISSUE TITLE
Adobe cmap resources and mapping resources

### ISSUE THREAD

**Issue by as-ascii** [podofo/podofo#104]
* **I'm submitting a:**
Question

* **[Bug report/Feature request] Other information**
Hello,

First of thank you for great opensource library.

I am in progress of refactoring pdf parser with custom code to use podofo library and have a question about the following resources that are downloaded and used in the old parser:
https://github.com/adobe-type-tools/cmap-resources
https://github.com/adobe-type-tools/mapping-resources-pdf

Does PoDoFo use them somehow? Are they required (to parse all pdf files via podofo correctly)? Are they supported in 0.10? If they are not supported, how to inject additional code into podofo library that can load and parse them?

Best regards.

**Comment by ceztko** [comment]
PoDoFo has now a good (enough?) CMap parser[1]. The resources you are mentioning in the first link are probably the CMap resources that are needed to map the predefined charsets defined by these CMaps to glyphs and unicode strings (9.7.5.2 Predefined CMaps, ISO 32000-2:2020). The second link is less clear to me as where it is useful. As far as I know when the CMap are external the PDF parser should supply them so yes: in general they are still needed. If you want to improve PoDoFo to bundle such data it would be fantastic, as I don't have time for such a big task. In this case, please let me know how you want to procede.

[1] https://github.com/podofo/podofo/blob/master/src/podofo/main/PdfCMapEncoding.cpp

**Comment by ceztko** [comment]
Please, let me if you plan to do some work about this topic. I'm very interested in improving PoDoFo support for external resources.
