### ISSUE TITLE
what happened with PdfTable class ?

### ISSUE THREAD

**Issue by msilewicz** [podofo/podofo#105]
I've just cloned git repo and there is no sign of PdfTable class - which was crucial for pdf table generation in version 0.9x of podofo
library ?
Are there any plans related to bringing PdfTable class back in source ?
sample grep command result is as follow :

test/CreationTest/CreationTest.cpp:717:    PdfTable table1( nCols, nRows );
test/CreationTest/CreationTest.cpp:741:    PdfTable table2( nCols2, nRows2 );
test/CreationTest/CreationTest.cpp:908:        printf("Drawing using PdfTable.\n");
test/CreationTest/CreationTest.cpp:911:        pRoot->Last()->CreateNext( "PdfTable Test", PdfDestination( pPage ) );

**Comment by ceztko** [comment]
Hello, I would like to be clear on `PdfTable`: I believe that compositions of primitive functions from PoDoFo that provides some kind of high level formatting do not belong to PoDoFo, with few exceptions (like for example proper text shaping/alignment). This was, I believe, the case of `PdfTable`, so I decided to drop it and have a more maintainable API. If you still need that, I recommend you to recover the old code from PoDoFo 0.9.x and have a local copy in your tree.
