### ISSUE TITLE
PoDoFo(0.9.8)  pdfextractor  encountered an error. Error: 8 ePdfError_InternalLogic

### ISSUE THREAD

**Issue by jianjianzhao** [podofo/podofo#109]
command: /root/pdfextractor B3B353297FE04450CAA7EC4D72AA6C401B373EE4.6015 B3B353297FE04450CAA7EC4D72AA6C401B373EE4.zip openpass
Error output:
Error: An error 8 ocurred during processing the pdf file.
PoDoFo encountered an error. Error: 8 ePdfError_InternalLogic
        Error Description: An internal error occurred.
        Callstack:
        #0 Error Source: /home/actions-runner/_work/root/txtextractor/pdfextractor/bin/podofo-0.9.8/src/podofo/doc/PdfMemDocument.cpp:431
                Information: SetPassword called without reading a PDF file.

We are using PoDoFo(0.9.8) on rocky9, when uncompressing the file with pdfextractor, it output error output above but there is no such issue in centos7,  coud you please help to check this issue, thanks.

**Comment by ceztko** [comment]
Since no one took responsibility to do it, 0.9.x is not actively maintained. You should migrate to 0.10.x and following versions. Also you are not really posting any actual code showing the problem, nor attaching a sample PDF, nor following the issue creation template in general.
