### ISSUE TITLE
Changelog: please prepend 'Unreleased' to unreleased version to help distinguish version info from previously released versions 

### ISSUE THREAD

**Issue by luzpaz** [podofo/podofo#119]
Currently the podofo [Changelog](https://github.com/podofo/podofo/blob/master/CHANGELOG.md) is structured in a way that the unreleased version isn't indicated that it's unreleased. This makes it challenging for downstream packagers to parse the changelog for updates. 

![Screenshot_20231219_110440](https://github.com/podofo/podofo/assets/4140247/62bb2345-40a6-4570-ae70-6299572862e8)

----

Would it be possible to prepend 'Unreleased' to `Version 0.11.0` like so:

**Comment by ceztko** [comment]
It makes a lot of sense, thanks for asking.
