### ISSUE TITLE
Error in function fromChars

### ISSUE THREAD

**Issue by NieLuc** [podofo/podofo#125]
* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [x] Bug report
  - [ ] Feature request/suggestion

* **[Bug report] What is the current behavior?**
I get the following error when trying to compile my project in which I only created a PdfPainter object:

/src/podofo/src/podofo/private/PdfDeclarationsPrivate.h: In instantiation of 'bool utls::TryParse(const string_view&, T&, std::chars_format) [with T = double; <template-parameter-1-2> = void; std::string_view = std::basic_string_view<char>]':
/src/podofo/src/podofo/private/PdfDeclarationsPrivate.h:336:28: error: no matching function for call to 'from_chars(std::basic_string_view<char>::const_pointer, std::basic_string_view<char>::const_pointer, double&, std::chars_format&)'
  336 |         if (std::from_chars(str.data(), str.data() + str.size(), val, fmt).ec == std::errc())
      |             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

\src\podofo\src\podofo\private\PdfDeclarationsPrivate.h:344: Warnung: control reaches end of non-void function [-Wreturn-type]

src/podofo/src/podofo/private/PdfDeclarationsPrivate.h: In function 'bool utls::TryParse(const string_view&, T&, std::chars_format) [with T = double; <template-parameter-1-2> = void]':
src/podofo/src/podofo/private/PdfDeclarationsPrivate.h:344:5: warning: control reaches end of non-void function [-Wreturn-type]
  344 |     }
      |     ^
* **[Bug report] What is the expected behavior?**
It should work I guess

* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**
I just used
```c++
#include <podofo/podofo.h>
int main(int argc, char *argv[]) {
    QApplication app(argc, argv);
    PdfPainter document;
    return app.exec();
}
```

* **Please tell us about your environment:**
  
  - Version/git revision: [1.10.0]
  - Operating System:Windows 64 bits
  - Package manager used: source
  - MinGW
  - Qt Tools and Qt Creator

* **[Bug report/Feature request] Other information**
- I dont know if my CMakeLists.txt is correct, but I implemented it just like stated in the documentation

  E.g. sample PDF documents, stacktraces, related issues, links for us to have contex, suggestions how to fix, etc.
![image](https://github.com/podofo/podofo/assets/141717827/aae8503b-6bfb-46c8-a793-2d20112d44ab)

**Comment by ceztko** [comment]
Please, try 0.10.3 first

**Comment by NieLuc** [comment]
I now switched to 0.10.3 and it still doesnt work

**Comment by ceztko** [comment]
I checked: `bool utls::TryParse(...)` funcitons in `PdfDeclarationsPrivate.h` were not in 0.10.0, nor in 0 .10.3 (you can check the 0.10.x [branch](https://raw.githubusercontent.com/podofo/podofo/0.10.x/src/podofo/private/PdfDeclarationsPrivate.h)), but they were introduced in master in 0.11-dev, so at least you were inaccurate in reporting the version you were testing. If you really tested 0.10.3 and still have compilation errors then the error should have changed, as a minimum. I recommend you to check your source tree because you may have some mess making you believe you are testing one version, when you are really referring to a different one.

**Comment by NieLuc** [comment]
Sorry your right, the error changed, but the function causing the error is the same.

\src\podofo\src\podofo\main\PdfColor.cpp:686: Fehler: no matching function for call to 'from_chars(std::basic_string_view<char>::const_pointer, std::basic_string_view<char>::const_pointer, double&, std::chars_format)'
/src/podofo/src/podofo/main/PdfColor.cpp: In static member function 'static PoDoFo::PdfColor PoDoFo::PdfColor::FromString(const string_view&)':
/src/podofo/src/podofo/main/PdfColor.cpp:686:28: error: no matching function for call to 'from_chars(std::basic_string_view<char>::const_pointer, std::basic_string_view<char>::const_pointer, double&, std::chars_format)'
  686 |         if (std::from_chars(name.data() + 1, name.data() + name.size(), grayVal, chars_format::fixed).ec != std::errc())
      |             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ceztko** [comment]
Please specify the exact version of the compiler used in mingw.

**Comment by NieLuc** [comment]
Im using MinGW 11.2.0

**Comment by ceztko** [comment]
Please try [0.10.x](https://github.com/podofo/podofo/tree/0.10.x) branch for a fix.
