### ISSUE TITLE
Missing Lua support

### ISSUE THREAD

**Issue by signalwerk** [podofo/podofo#127]
I install on an [Alpine Linux](https://www.alpinelinux.org/) the latest source from `master` and run the following;

```sh
 apk add --no-cache \
    git \
    cmake \
    make \
    gcc \
    g++ \
    lua-dev \
    freetype-dev \
    fontconfig-dev \
    openssl-dev \
    libxml2-dev \
    zlib-dev \
    jpeg-dev \
    tiff-dev \
    libpng-dev \
    libidn-dev

# Configure the build with CMake, including the tools
cmake -DCMAKE_BUILD_TYPE=Release -DPODOFO_BUILD_TOOLS=TRUE ..

# Compile PoDoFo and its tools
cmake --build . --config Release
```

This generates everything without an error. But the tools `podofocolor` and `podofoimpose` are compiled without Lua support. If I run the same commands with the branch `0.9.x` I get Lua support. This can also be checked with `podofocolor` (see second line for options);

### Version: 0.9.8
```man
Usage: podofocolor [converter] [inputfile] [outpufile]
        [converter] can be one of: dummy|grayscale|lua [planfile]
        podofocolor is a tool to change all colors in a PDF file based on a predefined or Lua description.

PoDoFo Version: 0.9.8
```

### Version: 0.11.0
```man
Usage: podofocolor [converter] [inputfile] [outpufile]
        [converter] can be one of: dummy|grayscale
        podofocolor is a tool to change all colors in a PDF file based on a predefined or Lua description.

PoDoFo Version: 0.11.0
```

I made a [`Dockerfile`](https://github.com/signalwerk/docker-podofo/blob/main/Dockerfile) that reproduces the problem.

How could I enable the Lua support again?

**Comment by ceztko** [comment]
> **Warning**: Tools are currently **untested** and **unmaintained**.

That's really the only possible answer. Lua is not searched anymore in global `CMakeLists.txt`, then [this](https://github.com/podofo/podofo/blob/6fa0b11ddc36a2aa6cc15a81859e44be653830a6/tools/podofocolor/CMakeLists.txt#L13C4-L13C13) condition will always be false, and the Lua code was never ported to PoDoFo >=0.10.

Did you author the Lua support? Patch welcome if you re-enable the support for it, but consider that the tools may be ditched from PoDoFo repository, at some point, if they are not cleaned to a point they can be maintained again.
