### ISSUE TITLE
cmap generated by PdfDynamicEncoding is displayed differently in different readers

### ISSUE THREAD

**Issue by CH-Chang** [podofo/podofo#137]
Hi!
Last day, I requested a pull request and merged it. #136 

I use another way to draw a paragraph on a PDF page.
Below is my code.

```cpp
std::string textOver255 = "12345糟姨集鞋南槍痕痰林托入笑為潮立碰慘紡命窯舒喬檔脊吸渣誘餓躁強瓣倚扣拼襯裙凈錄釀薯憂擇十肅亭宰都愉冬乃考摟償老居題釣盯侵臣騾購標搬輛映納銷蜂宋頭號鄭藝駛斥鏟遵饑絨挨草保示她房礙宜扶涼困供探濫裁鴨膏橫坦傍愧蜓山儀辜略機評疑寸浩韻挪墻含帆由化里肌目淹誤匹枕浸有協斯名哥其香響逼裂油館慰七狹置露河樓弊增熱懂劇難盞拘罵撇芽胡慧關準補必舌遼晴奏愛江掏疲番走芬秩撤搭饅槐伸填灣蝦載簾哄寫急病攤田惕次泡捏糧附刷李鉆解阿違嫁天塌句善訊夠衰唇險學欠堆弟貪爆徐太孤鎮膛婆褲傷謹憶鵝踢贈擔仗膀挽兄扔基窩幕裹血暴米政覆柴力豎悼劫肥書翁屑";

PdfMemDocument* document = new PdfMemDocument();

PdfFontManager* fontManager = &(document->GetFonts());
PdfFont* font = &(fontManager->GetOrCreateFontFromBuffer(bufferview(fontBytes, fontSize)));

// Draw a XObjectForm
unique_ptr<PdfXObjectForm> xObjectPtr = document->CreateXObjectForm(Rect(0, 0, 720, 1280));
PdfXObjectForm* xObject = xObjectPtr.get();

PdfPainter* painter1 = new PdfPainter();
painter1->SetCanvas(*xObject);

PdfGraphicsStateWrapper* graphicsState = &(painter1->GraphicsState);
graphicsState->SetFillColor(PdfColor(0, 0, 0));
graphicsState->SetStrokeColor(PdfColor(0, 0, 0));

PdfTextStateWrapper* textState = &(painter1->TextState);
textState->SetFont(*font, 12);

painter1->DrawTextMultiLine(textOver255, 0, 0, 720, 1280);

painter1->FinishDrawing();

delete painter1;

// Draw XObjectForm to Page
PdfPageCollection* pages = &(document->GetPages());
PdfPage* page = &(pages->CreatePage(Rect(0, 0, 720, 1280)));

PdfPainter* painter2 = new PdfPainter();
painter2->SetCanvas(*page);
painter2->DrawXObject(*xObject, 0, 0, 1.0, 1.0);

painter2->FinishDrawing();

delete painter2;

vector<char>* pdfVector = new std::vector<char>();
PoDoFo::VectorStreamDevice outputStreamDevice(*pdfVector);

fontManager->EmbedFonts();
document->Save(outputStreamDevice);

delete document;
delete pdfVector;
```

The produced PDF:
[Error.pdf](https://github.com/podofo/podofo/files/14400118/Error.pdf)

In Adobe Acrobat Reader, the display looks like:
![Error_AcrobatReader.png](https://github.com/podofo/podofo/assets/56328238/650c6e43-cc0f-47b1-96a7-bd521fb6a815)

But in Firefox, the display looks like:
![Error_Firefox.png](https://github.com/podofo/podofo/assets/56328238/0dc74286-f1fe-4979-b3a7-9e5cb2174337)

I think Firefox treats the cmap encode 01 and 0100 are duplicated and make it display with error result.
![Error_Structure.png](https://github.com/podofo/podofo/assets/56328238/4695b4c2-ed5e-442e-9c7e-e9b7f300fd5d)

So,
I changed some code to make the produced cmap encoding padding start with zero.
I acknowledge that the modification may not be suitable for PdfDynamicEncoding,
but I just want to conduct some tests.

Change:
https://github.com/podofo/podofo/blob/af33808ffe42113d37d574af3c2bfae78c5e5686/src/podofo/main/PdfFont.cpp#L702

To:
```cpp
code = PdfCharCode(m_DynamicToUnicodeMap->GetSize(), 2); 
```

And

Change:
https://github.com/podofo/podofo/blob/af33808ffe42113d37d574af3c2bfae78c5e5686/src/podofo/main/PdfFont.cpp#L789

To:
```cpp
auto inserted = m_SubsetGIDs.try_emplace(gid, PdfCID(PdfCharCode((unsigned)m_SubsetGIDs.size() + 1, 2)));
```

The produced PDF:
[Error_Padding.pdf](https://github.com/podofo/podofo/files/14400256/Error_Padding.pdf)

In Adobe Acrobat Reader, the display looks good.
![Error_Padding_AcrobatReader.png](https://github.com/podofo/podofo/assets/56328238/98f730f2-e13c-4746-b5ca-e9bd90c1be1c)

In Firefox, the display looks also good.
![Error_Padding_Firefox.png](https://github.com/podofo/podofo/assets/56328238/421ab5d7-7a93-4e65-9224-4e48efeebddf)

But!
In the macOS PDF previewer,
Everything goes wrong....
![Error_Padding_MacOS.jpg](https://github.com/podofo/podofo/assets/56328238/d2545605-6698-48d3-b644-8f7bffc99b42)

I have no idea how to solve it.
I've checked the /ToUnicode and /Encoding encoding, and they are correct!
![Error_Padding_cmap.png](https://github.com/podofo/podofo/assets/56328238/00129420-19fb-4b31-96dc-53fcf72f7f65)

**Comment by ceztko** [comment]
Hello. I wrote `PdfDynamicEncoding` so I'm the right person to ask. Unfortunately these issues requires time for testing and debugging, so I can't guarantee I can help you promptly, but I will give you all the hints I have in mind.

One thing I can tell you immediately is that there is a rule that codespace ranges must not overlap. The algorithm described by the PDF specifications tells to look for smaller codes first (1 byte), and then move to greater codes (2 bytes, 3 bytes, ...) , until a match is found. So...
```
<01><ff>
<0100><0105>
```
look fine, as they define 2 codes (1 byte and 2 bytes) that don't overlap (1-255 and 256-261). So, if the `bfchar` mappings to the font are fine everything should be ok, according to the specification. At first, I would not assume the behavior of Firefox (that uses pdf.js) or MacOs Preview app to be correct.

So far here are the apps/egines that display [Error.pdf](https://github.com/podofo/podofo/files/14400118/Error.pdf) correctly (my tests):
- Adobe Reader (engine: own Adobe engine)
- Gnome Evince (engine: poppler/xpdf)
- chrome (engine: pdfium)
- ImageMagick (engine: ghostscript)

Here it follows the engines that fails:
- Firefox (engine: pdf.js)
- Apple Preview (engine: unknown engine)

Seeing that the majority of the engines render the PDF correctly, I would start debugging pdf.js code (which is not hard to debug with a JavaScript debugger) to understand if the latter is doing something wrong. If you are up for the challenge here is a script [PdfJsDebugViewer.cmd.txt](https://github.com/podofo/podofo/files/14403628/PdfJsDebugViewer.cmd.txt) I use on Windows (but you can take inspiration to use in a other OS) to debug a [distribution](https://github.com/mozilla/pdf.js/releases) of pdf.js with chrome. With this I can put any desired breakpoint and debug pdf.js locally.

**Comment by CH-Chang** [comment]
Here is the source code for pdf.js to process cmap mapping.

https://github.com/mozilla/pdf.js/blob/e42b114e80c89b1766ce4b93fe7298c00435173c/src/core/cmap.js#L325

In the [Error.pdf](https://github.com/podofo/podofo/files/14400118/Error.pdf) the last line is

```
<f4f5f6f7f8f9fafbfcfdfeff010001010102010301040105> Tj
```

f4 => U+57FA '基'
f5 => U+7AA9 '窩'
f6 => U+5E55 '幕'
f7 => ...
f8 => ...
f9 => ...
fa => ...
fb => ...
fc => ...
fd => ...
fe => ...
ff => ...
01 => ...
00 => error...

Seems the range should sort from bigger one to less one?

Cmap should be
```
2 begincodespacerange <0100><0105><01><ff> endcodespacerange
```

rather than
```
2 begincodespacerange <01><ff><0100><0105> endcodespacerange
```

**Comment by flyingswan3000** [comment]
In my opinion, the code space ranges `<01><ff>` and `<0100><0105>` do indeed overlap. If the first byte is 0x01, the PDF engine cannot determine which code to use.

For example, consider a stream `0x010501`. How would it decode?

`<01> <05> <01>` or `<0105> <01>`?

Could you please provide the source for the PDF specifications that mention to look for smaller codes first (1 byte), and then move to greater codes (2 bytes, 3 bytes, ...) ? This information would be very helpful for further understanding and discussions.

**Comment by CH-Chang** [comment]
> Here is the source code for pdf.js to process cmap mapping.
> 
> https://github.com/mozilla/pdf.js/blob/e42b114e80c89b1766ce4b93fe7298c00435173c/src/core/cmap.js#L325
> 
> In the [Error.pdf](https://github.com/podofo/podofo/files/14400118/Error.pdf) the last line is
> 
> ```
> <f4f5f6f7f8f9fafbfcfdfeff010001010102010301040105> Tj
> ```
> 
> f4 => U+57FA '基' f5 => U+7AA9 '窩' f6 => U+5E55 '幕' f7 => ... f8 => ... f9 => ... fa => ... fb => ... fc => ... fd => ... fe => ... ff => ... 01 => ... 00 => error...
> 
> Seems the range should sort from bigger one to less one?
> 
> Cmap should be
> 
> ```
> 2 begincodespacerange <0100><0105><01><ff> endcodespacerange
> ```
> 
> rather than
> 
> ```
> 2 begincodespacerange <01><ff><0100><0105> endcodespacerange
> ```
> 
> Match two bytes first than match one bytes.

I tested it.
It doesn't work.

Here is the PDF.
[Error_ordered.pdf](https://github.com/podofo/podofo/files/14413646/Error_ordered.pdf)

Might pdf.js should change the algorithm to archieve process two bytes first then process one bytes.
Another chosen is that padding start with zero while expanding.

**Comment by ceztko** [comment]
> In my opinion, the code space ranges <01><ff> and <0100><0105> do indeed overlap.

@flyingswan3000: No, they don't. It's `(1,255)` and `(256, 261)`. Overlap means, for example, `(1,255)` and `(255, 261)`.

> Could you please provide the source for the PDF specifications that mention to look for smaller codes first (1 byte), and then move to greater codes (2 bytes, 3 bytes, ...) ?

Sure thing. From ISO 32000-2:2020 "9.7.6.2 CMap mapping":

```
A sequence of one or more bytes shall be extracted from the string and matched against the codespace
ranges in the CMap. That is, the first byte shall be matched against 1-byte codespace ranges; if no
match is found, a second byte shall be extracted, and the 2-byte code shall be matched against 2-byte
codespace ranges. This process continues for successively longer codes until a match is found or all
codespace ranges have been tested. There will be at most one match because codespace ranges shall
not overlap.
```

> Perhaps pdf.js should consider changing the algorithm to process two bytes first and then process one byte.

@CH-Chang Why? The specification dictated algorithm tells to start with smaller ranges and makes sense. Still I don't understand if you find a problem in pdf.js or not.

**Comment by CH-Chang** [comment]
I think the algorithm operation should be like this:

```
<f4f5f6f7f8f9fafbfcfdfeff010001010102010301040105> Tj
```

f4f5 => not match..
f4 => U+57FA '基' 
f5f6 => not match..
f5 => U+7AA9 '窩'
f6f7 => not match..
...
ff01 => not match..
ff => U+8C4E '豎'
0100 => U+60BC '悼'
0101 => U+52AB '劫'
...


The algorithm should try more combinations of bits first.

The specification dictated algorithm will face below issue

```
<f4f5f6f7f8f9fafbfcfdfeff010001010102010301040105> Tj
```

f4 => U+57FA '基'
f5 => U+7AA9 '窩'
f6 => U+5E55 '幕'
f7 => ...
f8 => ...
f9 => ...
fa => ...
fb => ...
fc => ...
fd => ...
fe => ...
ff => ...
01 => ...
00 => error...

Chosen 1 -> look back:
0100 => U+60BC '悼'

Or

Chosen 2 -> look forward:
0001 => still error...

**Comment by ceztko** [comment]
@CH-Chang: Sorry, but I don't understand your last message. The specification says another thing and compliant reader must follow the specification. So, either we find a bug in PoDoFo in serializing char codes or we find a bug in pdf.js/Apple Preview tool not following closely the specification.

**Comment by CH-Chang** [comment]
@ceztko: I think we may have misunderstood the description of ISO 32000-2:2020 "9.7.6.2 CMap mapping". According to the description, we should look for a one-bit code first, then a two-bit code, and so on.

Assuming that the code for one byte has been defined from 0x01 to 0xff, this, combined with the ISO description mentioned above, means that it is impossible to make a Cmap with more than 255 characters. When parsing, the search for the code for two bytes will never happen, because it must always be possible to parse one byte into a character, which is obviously not reasonable.

I don't know what's going on here, perhaps I need to check the Adobe Acrobat Reader related parsing code to explain it, but it's not open source...

**Comment by ceztko** [comment]
> I think we may have misunderstood the description of ISO 32000-2:2020 "9.7.6.2 CMap mapping". According to the description, we should look for one byte first, then two bytes, and so on.

Yes, that was I was saying at first. I wrote Unicode [decoding](https://github.com/podofo/podofo/blob/af33808ffe42113d37d574af3c2bfae78c5e5686/src/podofo/main/PdfEncodingMap.cpp#L205) as well.

> Assuming that the character for one byte has been defined from 0x01 to 0xff, this, combined with the ISO description mentioned above, means that it is impossible to make a Cmap with more than 255 characters. When parsing, the search for two bytes will never happen, because it must always be possible to parse each one byte into a character, which is obviously not reasonable.

Ok, I'm possibly seeing what's happening here and the PoDoFo implementation of `PdfDynamicEncoding` may be wrong after all: not only the ranges must not overlap in the decimal form, but they must leave room for extendibility so bigger codes can't be confused. In this case we must rethink how ranges are built.

**Comment by ceztko** [comment]
The best source of information here is almost for sure the Adobe Technical Note #5014, called "[Adobe CMap and CIDFont Files Specification](https://adobe-type-tools.github.io/font-tech-notes/pdfs/5014.CIDFont_Spec.pdf)". Start reading from page 48 "Codespace" and following pages, especially 50.

**Comment by ceztko** [comment]
So the codes must not overlap not only _linearly_ on the decimal value, but also _rectangularly_ based on the decimal value and code size. The code must be fixed in several places because clearly this was not handled properly before. We need a very simple function `unsigned char GetNonOverlappingCharCodeSize(unsigned cid)` that given a growing CID tells the size of the char code so in the end the ranges won't overlap rectangularly.

**Comment by CH-Chang** [comment]
I think we might need more than just a GetNonOverlappingCharCodeSize function. Maybe we need a map that records who used the font and corrects what was written when the font is expanded, which would be a big job.

Like this:
https://github.com/podofo/podofo/blob/af33808ffe42113d37d574af3c2bfae78c5e5686/src/podofo/main/PdfPainter.cpp#L402

When the font cmap expanding, we need to update the stream content also.

**Comment by ceztko** [comment]
>  Maybe we need a map that records who used the font

There's already a [map](https://github.com/podofo/podofo/blob/af33808ffe42113d37d574af3c2bfae78c5e5686/src/podofo/main/PdfFont.cpp#L787) being built with actually used GIDs/CIDs, it's the whole point of `PdfDynamicEncoding`. I believe the main mistake is how a `PdfCharCode` is built from just the integral value of the CID, which [at the moment](https://github.com/podofo/podofo/blob/af33808ffe42113d37d574af3c2bfae78c5e5686/src/podofo/main/PdfEncodingCommon.cpp#L19) is just determining the **minimum** number of bytes to represent the numerical code, which clearly appears to be **wrong**. The fix would be to create a valid variable size code like [UTF8](https://en.wikipedia.org/wiki/UTF-8#Encoding), but I believe it can be simpler than that. I need to think about (I'm busy with my job now) but I believe it's possible to reserve ranges in the first byte so the code will just scale from (let say) 1 to 4 bytes maximum, and the decimal numerical code will always be the exact hexadecimal conversion to decimal of the 1-4 bytes of the code unit (instead for sure UTF8 can't be simple like this). When this is fixed, we just need to ensure the ranges are correctly built from used GIDs/CIDs in this [code](https://github.com/podofo/podofo/blob/af33808ffe42113d37d574af3c2bfae78c5e5686/src/podofo/main/PdfEncoding.cpp#L581), and the bug should hopefully go away, without the need to intervene in other parts of the code in PoDoFo.

**Comment by CH-Chang** [comment]
I used the FSS-UTF encoding method to make the correction, here is the corrected code.

The resulting PDF is as follows:
[Error_Fixed.pdf](https://github.com/podofo/podofo/files/14441606/Error_Fixed.pdf)

But it still doesn't seem to work in the MacOS preview app...

**Comment by CH-Chang** [comment]
Then I found out that the abnormal character is

```
character: '協'
unicode: U+5354
cid: 0xc286
```

The current codespacerange is 

```
2 begincodespacerange
<01> <7f> <c280> <c485> endcodespacerange
```

c2 is in the range c2 through c4.
but 86 is not in the range 80 to 85.
This results in a character parsing failure and cannot be displayed correctly.

Therefore.
I decided to write the full codespacerange of the codesize directly.

Here are my changes
https://github.com/podofo/podofo/compare/master...CH-Chang:podofo:bug/encoding?expand=1

The resulting PDF looks like this
[Error_Fixed_Range.pdf](https://github.com/podofo/podofo/files/14442459/Error_Fixed_Range.pdf)

If there is no problem, I will open a pull request.

**Comment by ceztko** [comment]
That's a great job (thank you!). Please create the PR (also squash the commits, please) so it will be easier for me to review it but allow me also to investigate if there could be a simpler solution. As I was mentioning [here,](https://github.com/podofo/podofo/issues/137#issuecomment-1968575068) what I'm still not 100% sure is if using transformations like FSS-UTF or UTF8 is really necessary, because in this way we loose _CID_ and _char code_ decimal value equality, which would be very convenient and would possibly protect against possibly breaking other parts of the code. FSS-UTF/UTF8 where designed to avoid mismatches with other single byte encodings, while here we don't have this requirement: maybe you can elaborate why you decided to use FSS-UTF anyway? I have very limited time to work on PoDoFo so a new release (0.11 or 1.0) is not in sight, but I want to find the time to review your changes and another pending PR ASAP, so please continue testing your solution in the mean time.

**Comment by CH-Chang** [comment]
I've squashed my commit and opened a pull request.
Here is my pull request.

https://github.com/podofo/podofo/pull/139

I've been browsing algorithms for variable-length coding, such as  [Google Protobuf Encoding](https://protobuf.dev/programming-guides/encoding/), but I think they're all too complicated to use in practice, and there's no better way than with the FSS-UTF, so I tend to use FSS-UTF directly.

**Comment by ceztko** [comment]
#139 merged, thank you for the positive collaboration. It would be great now to make a test case with the code above and text extraction, checking for consistency of the extracted text.
