### ISSUE TITLE
Images are skewed

### ISSUE THREAD

**Issue by BrianErickson-InfoCon** [podofo/podofo#142]
Paper Width(inches): 7.5524997711181641  
Paper Height(inches): 6.9675002098083496
Paper Width(PDF Units): 543.77998352050781
Paper Height(PDF Units): 501.66001510620117

The Images are skewed left to right at about 45 degree angle.

Paper Width(inches): 7.5500001907348633
Paper Height(inches): 6.9699997901916504
Paper Width(PDF Units): 543.60001373291016
Paper Height(PDF Units): 501.83998489379883

No skew.

The long precision is due to the conversion done by atof and cast from double to float.
The entered value are:
Width: 6.9675
Height: 7.5525

I don't want skewing, I do not allow skewing.
Why the skewing?

**Comment by ceztko** [comment]
There are some problems in your report. First: don't assume English is the first language of the reader and don't assume the reader is on the same page as you are. I'm really having a problem understanding what you are trying to achieve and you didn't come up with any material (code sample, pdf, screenshot...) that shows your exact problem. Your inquiry is so vague that you may be talking about tools (which are not supported) or older (unsupported) pre 0.10 versions of PoDoFo. I believe it's best to lock this issue: open a new one once you are ready to provide more context.
