### ISSUE TITLE
Who did do a mistake?

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#15]
In `PdfFont::GetStringLength()` I caught an exception here:

```cpp
const string& PdfString::GetRawData() const
{
    if (m_data->State != PdfStringState::RawBuffer)
        throw runtime_error("The string buffer has been evaluated");

    return m_data->Chars;
}
```

What is going on:

```cpp
const auto str = createPdfString( *it );

const auto length = font->GetStringLength( str, fontSt );
```

where:

```cpp
PdfString
PdfRenderer::createPdfString( const QString & text )
{
	return PdfString( text.toUtf8().data() );
}
```

My string `PdfString::m_data->State` = `PoDoFo::PdfStringState::Ascii` and my application crashes in `PdfString::GetRawData()`.

Who is wrong?

**Comment by ceztko** [comment]
`PdfString` has now a state determining if it has been evaluated to a UTF-8 string or it's still an unevaluated buffer with indeterminate content. Thhe overalods taking `PdfString` needs the unevaluated buffer. I don't know what exactly you are doing, but you shouldn't use `PdfString` to compute text length, that's reserved for text extraction from content streams. You just gave me the wonderful idea to rename the overloads with `PdfString` so people will stop using them inadvertently. I just made it https://github.com/podofo/podofo/commit/439829b34153143ef0b9525d10fc5a3bc94c38cc.
