### ISSUE TITLE
Unable to load legacy providers in OpenSSL >= 3.x.x

### ISSUE THREAD

**Issue by Neil-0609** [podofo/podofo#153]
When I use podofoencrypt.exe to encrypt, the encryption is successful on my own computer. However, an exception occurs on other computers, and the error is printed as follows:
ERROR: An error occurred during processing the pdf file
PdfErrorCode::InvalidHandle, An invalid handle was passed or returned, but initialized data was expected.
Callstack:t#0 Error Source: main\PdfMemDocument.cpp(254)
t#1 Error Source: private\OpenSSLInternal.cpp(46), Information: Unable to load legacy providers in OpenSSL >= 3.x.x

**Comment by ceztko** [comment]
I guess today RC4 is not that required, so I stopped eagerly throwing on missing RC4. It should help.

**Comment by Neil-0609** [comment]
> I guess today RC4 is not that required, so I stopped eagerly throwing on missing RC4. It should help.

the command I used is: podofoencrypt.exe -o 123 C:\Users\Administrator\Desktop\1.pdf C:\Users\Administrator\Desktop\1_1.pdf. Default  PdfEncryptAlgorithm::AESV2,not PdfEncryptAlgorithm::RC4

**Comment by ceztko** [comment]
That was failing because RC4 was eagerly loaded unconditionally.

**Comment by Neil-0609** [comment]
> That was failing because RC4 was eagerly loaded unconditionally.

tks,slove it by  recompile OpenSSL
