### ISSUE TITLE
how to remove freeobject

### ISSUE THREAD

**Issue by pallybi** [podofo/podofo#156]
i dont knwo how to remove freeobject

**Comment by ceztko** [comment]
"freeobject" doesn't look like PDF terminology. Maybe you mean "Free text" annotations. Then you just access all annotations in a page with `PdfPage::GetAnnotations()` and then you use `PdfAnnotationCollection::RemoveAnnotAt()` or  `PdfAnnotationCollection::RemoveAnnot` methods to remove it, after discovering the type of the annotation with `PdfAnnotation::GetType()`.
