### ISSUE TITLE
Question: Migration to 0.10.x - What happend to PdfField?

### ISSUE THREAD

**Issue by Mr-Rayman** [podofo/podofo#158]
I'm in the process of migrating my code to 0.10.x.   I didn't see any explaination in the migration guide:

What happened to PdfField, especially the method PdfPage::getField()? And further the annotation of the specific PdfField earlier obtained using GetWidgetAnnotation()?

How can I access/modify all the form fields and their annotations in a PdfPage?

Thanks, Stefan

**Comment by ceztko** [comment]
Yes, that was removed since from an API perspective that looked like the Page has an actual list of fields, while this is not true (it really has only a list of annotations, which may be or not fields). I may add an iterator to enumerate only fields later, but the previous indexing like method won't be put back. Before that, you can iterate annotations to retrieve fields:

```void GetPageFields(vector<PdfField*> &fields, PdfPage &page)
{
    auto& annotations = page.GetAnnotations();
    for (unsigned i = 0, annotCount = annotations.GetCount(); i < annotCount; i++)
    {
        auto& annot = annotations .GetAnnotAt(i);
        if (annot.GetType() != PdfAnnotationType::Widget)
            continue;

        fields.push_back(&static_cast<PdfAnnotationWidget&>(annot).GetField());
    }
}```

**Comment by Mr-Rayman** [comment]
Thanks for the explaination and your efforts in maintaining PoDoFo! I like the C++17 version much better, but there are still many things unclear.

Wenn I convert a PdfString to std::string, for example from Dictionary Key-Values or PdfTextBox, the returned std::string is enclosed in brackets. Why are PdfStrings always enclosed in brackets when going to std::string and how can I prevent this?

Example:
```
std::string valueIn = "Hello World";
PdfTextBox *pdfTF = dynamic_cast<PdfTextBox*>(&pdfField);
pdfTF->SetText(PdfString(valueIn));
// ..
std::string valueOut = pdfTF->GetText()->ToString();
std::cout << valueOut;
```
leads to:   
(Hello World)

**Comment by ceztko** [comment]
You are using the wrong method. The documentation of `ToString()` is clear enough that is not the string you are looking for. Use `GetString()` instead.
