### ISSUE TITLE
helloworld does not compile with libxml2 v2.12.6

### ISSUE THREAD

**Issue by blackandwhitebg** [podofo/podofo#159]
* **I'm submitting a:**
  - [X] Bug report

I was working with older versions of the dependencies and decided to update those.
Those that work correctly are:

- OpenSSL 3.0.13
- LibJpeg 9f
- LibPng 1.6.43
- LibTiff 4.6.0t
- FreeType 2.13.2
- zlib 1.3.1

However,
with LibXml2 - everything works with 2.10.3.
When I tried with 2.12.6 (the latest), the Hello World application fails to compile because of Unresolved Externals

I am testing with the current source code as they are in github right now (May 1st 2024).
I`m compiling all of the dependencies and podofo in Release mode with /MT flag using Visual Studio 2022.

**Comment by ceztko** [comment]
Not enough info, such as the unresolved symbols. Quite frankly, I believe that for linking issues with 3rd party dependencies, users have the burden of both 1) fix/debug their issues and 2) provide more substantial proofs that the project is responsible for the failed compilation, which I don't see here. Quite interestingly, the CI mac [build](https://github.com/podofo/podofo/actions/runs/8881660362/job/24384549852) is already building with 2.12.6, so I'm quite confident PoDoFo has nothing to do with your actual issue.

**Comment by blackandwhitebg** [comment]
Hello again,
I`m sorry - it works correctly. 
The problem was in the way I build libxml2.

So basically, I have only good news - the Project compiles and works with the very latest version of each of its dependencies.
Thank you!
