### ISSUE TITLE
Add high-level API to load font from a file

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#16]
Just to keep in mind that this feature is needed. I wrote you by email before, you said that this should be simple to implement it, and you were going to do it ASAP.

**Comment by ceztko** [comment]
Added in https://github.com/podofo/podofo/commit/2521705c8eaaa68ac4b91fa72646c9dd3df9b157. The methods you are looking for are `GetOrCreateFont()`/`GeOrCreateFontFromBuffer()`. It was a bit harder than I initially thought so I couldn't resist to rename `PdfFontManager` methods to something more clear of what's really happening under the hood and return references, when meaningful. Just see the diff, it's easy to fix compilation.

> and you were going to do it ASAP

Correct, I told you so, but always remember that there is [no warranty](https://github.com/podofo/podofo#no_warranty), of any kind.
