### ISSUE TITLE
Loading Multipage TIFFs

### ISSUE THREAD

**Issue by sfirouz** [podofo/podofo#161]
* **I'm submitting a:**
  - [x] Feature request/suggestion

* **[Feature request] Currently there is no way to load a single page from a multi-page TIFF (other than 0th page) into a `PdfImage`.
*  I thought I can use the `TIFFOpen` to open the file and then use `TIFFSetDirectory` to set the desired page number and then call `loadFromTiffHandle` function of `PdfImage`, but that function is private (and in my humble opinion there is no reason for it to be private).
* I think we all agree that we need a way to work with multi-page TIFF files. So we either need another `Load `function that takes page number or the quickest way would be to make `loadFromTiffHandle `public.

* **Please tell us about your environment:**
  
  - Version/git revision: [0.10.3]
  - Operating System: [Windows 11 (64 bits) ]
  - Package manager used: [source]

**Comment by ceztko** [comment]
While I am unsure people are waiting for this feature that eagerly, I believe it's is interesting enough that could be promoted straight to the generic image loading signatures like this:

```
    void Load(const std::string_view& filepath, unsigned imageIndex = 0);
    void LoadFromBuffer(const bufferview& buffer, unsigned imageIndex = 0);
```

We handle it in the same exact way for fonts where only TTC fonts actually may contain more than one font, no need to expose private signatures. Patch welcome, it should be quite easy.

**Comment by sfirouz** [comment]
> While I am unsure people are waiting for this feature that eagerly, I believe it is interesting enough that could be promoted straight to the generic image loading signatures like this:
> 
> ```
>     void Load(const std::string_view& filepath, unsigned imageIndex = 0);
>     void LoadFromBuffer(const bufferview& buffer, unsigned imageIndex = 0);
> ```
> 
> We handle it in the same exact way for fonts where only TTC fonts actually may contain more than one font, no need to expose private signatures. Patch welcome, it should be quite easy.

While I agree that it is very easy to create the enhancement by adding a parameter and calling the `TIFFSetDirectory` before reading the page data, there are other reasons why you might want to allow users to access `loadFromTiffHandle` and the likes. For example one of the problems I ran into was some scanners/cameras save the image as their sensor sees it and then the just set the [TIFFTAG_ORIENTATION](https://www.awaresystems.be/imaging/tiff/tifftags/orientation.html) in tiff files and [similar property in JPEG and PNG](https://learn.microsoft.com/en-us/windows/win32/gdiplus/-gdiplus-constant-property-item-descriptions#propertytagorientation) to compensate for it. That means we need to read that property and use the correct matrix transformation (or `PdfImage` has to account for it) to draw the image on the page. looking at documentation for [TIFFGetField](https://libtiff.gitlab.io/libtiff/functions/TIFFGetField.html), there are tons of fields that user might want to know about that effects the image.
When I started with C++ about 35 years ago, I was told you make a function or class member private to protect some internal function/data. None of the functions that are surrounded by `#ifdef PODOFO_HAVE_xxx_LIB` qualify for that requirement. I understand the trend to make things private as much as possible, but my question is "WHY"? What advantage do we gain by making them private or what is the disadvantage to make them public and let the user of the library have access to them? Keep in mind we can no longer instantiate `PdfImage` by ourselves. We have to use `CreateImage` function of `PdfDocument` to create one. That means inheriting from `PdfImage` would be useless.

**Comment by sfirouz** [comment]
In case the above samples are mangled by GitHub, here is a zipped version

[Images.zip](https://github.com/podofo/podofo/files/15406854/Images.zip)

**Comment by ceztko** [comment]
I understand your point, but handling metadata with orientation (any format supporting it) is another feature that would be great to be supported internally. Another feature: topic for another issue (and again patches would be welcome).

About API design, there's another issue about exposing data structures from other APIs that is version mismatching: bad things may happen if the consumer library version is different from the one PoDoFo is compiled with. We have already a precedent in `PdfFontManager` where PoDoFo is accepting `FT_Face` from freetype, and I'm thinking about removing it for the same reason. Yes, the trend recently is about reducing the API surface, sealing classes and removing public methods that were supposed to be for internal infrastructure use only. I'm actively working with this spirit as I believe it gives great value for a small cost. It's my duty to keep the bar high to reach a 1.0 which I want to be a very polished and refined API. The pace of development is not as fast as I would like it to be, but I'm working under the hood even when I don't commit big patches for long time (another big refactor coming related to `PdfColor`).

**Comment by sfirouz** [comment]
Thank you for a great tool. I really appreciate what you've done here. As I'm sure everyone else who is using it feels the same way.
