### ISSUE TITLE
multiple use of TIFFClose on the same TIFF handle

### ISSUE THREAD

**Issue by sfirouz** [podofo/podofo#162]
* **I'm submitting a:**
  - [x] Bug report

* **[Bug report] What is the current behavior?**
inside the `loadFromTiffHandle` every time an exception is about to be raised, the function `TIFFClose` is being called and then the exception is raised. The exception is caught in `loadFromTiff` and `TIFFClose` gets called again which tries to close a TIFF file that is already closed.

* **[Bug report] What is the expected behavior?**
All of the calls to `TIFFClose` inside the `loadFromTiffHandle` should be removed and only the one in `loadFromTiff` should remain.
even better would be to use a wrapper class like this inside `loadFromTiff` and never use `TIFFClose` anywhere else:
```
class TTiffWrapper
{
protected:
	TIFF* hInfile;
public:
	TTiffWrapper(void);
	TTiffWrapper(const std::string& aPath);
	virtual ~TTiffWrapper(void);
	bool Open(const std::string& aPath);
	void Close(void);
	TIFF* operator&(void);
	void SetCurrentPage(const unsigned int cPage);
	bool GetIsOpen(void) const;

	__declspec(property(get = GetIsOpen)) bool IsOpen;
};

TTiffWrapper::TTiffWrapper(void)
{
    hInfile = nullptr;
}

TTiffWrapper::TTiffWrapper(const std::string& aPath)
{
    Open(aPath);
}

TTiffWrapper::~TTiffWrapper(void)
{
    Close();
}

bool TTiffWrapper::Open(const std::string& aPath)
{
    Close();
    hInfile = TIFFOpen(aPath.data(), "rb");

    return (nullptr != hInfile);
}

void TTiffWrapper::Close(void)
{
    if (nullptr != hInfile)
    {
        TIFFClose(hInfile);
        hInfile = nullptr;
    }
}

TIFF* TTiffWrapper::operator&(void)
{
    return hInfile;
}

void TTiffWrapper::SetCurrentPage(const unsigned int cPage)
{
    if (nullptr != hInfile)
        TIFFSetDirectory(hInfile, cPage);
}

bool TTiffWrapper::GetIsOpen(void) const
{
    return (nullptr != hInfile);
}
```
When using the class above, the & operator can be used as parameter to `loadFromTiffHandle`.

* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**
* try to load a Tiled TIFF
  
  - Version/git revision: [0.10.3]
  - Operating System: [Windows 11 (64 bits)]
  - Package manager used: [source]

**Comment by ceztko** [comment]
Also fixed in [0.10.x](https://github.com/podofo/podofo/tree/0.10.x). If you can give me some testing I may release a 0.10.4 soon (that has just a couple of fixes, including this one).

**Comment by sfirouz** [comment]
> Also fixed in [0.10.x](https://github.com/podofo/podofo/tree/0.10.x). If you can give me some testing I may release a 0.10.4 soon (that has just a couple of fixes, including this one).

[Test.zip](https://github.com/podofo/podofo/files/15450503/Test.zip)
I see that you have enabled the multipage TIFF support. Thank you. Here is a TIFF file that you can test with. Only the 1st page has orientation set to `ORIENTATION_TOPLEFT`. so the rest should generate an exception because you have added these lines:

```
if (orientation != ORIENTATION_TOPLEFT)
        PODOFO_RAISE_ERROR(PdfErrorCode::UnsupportedImageFormat);
```

I would like ask you to please please please PLEASE remove them. If you do this, you'll remove our ability to externally deal with images that have orientations other than `ORIENTATION_TOPLEFT`.
We don't have control over what kind of images are sent to our apps for processing. I only mentioned this orientation case, because I came across it while processing images in my app and I ended up with sideways pages. But I was able to overcome that by using Matrix that you've kindly provided. If you keep those lines in, I won't be able to use it anymore. So please please please take those 2 lines out. You can add them back in once you have programed `PDFImage` to deal with those cases. But for now, please leave it out.

**Comment by sfirouz** [comment]
> 
> Done [2b39823](https://github.com/podofo/podofo/commit/2b398232b243e61e8b930274f5a413ae519437fd) .
> 
Thanks

> 
> I guess there's a typo here, I guess it should be "if you do this, you'll **add** the ability...".
> 
sorry I meant if you leave those lines in, we would loose our ability to deal with it externally

> As said, please create a new ticket with the feature request to handle TIFF rotation information. Do you own the copyright for the test picture(s)? If so, please attach the link to the attachment and make a public domain MIT 0 statement for that, so we can add it to the resource repo.
> 
[Test.zip](https://github.com/user-attachments/files/15534048/Test.zip)
Sorry for the delayed response. I've been really busy at work and home.
I will create a ticket for adding more properties to PDFImage (like resolution). It would not be TIFF specific.
The image that I sent is a picture of WWII memorial in Hawaii. I do not believe it is copyrighted, but let's not take any chances. I've created another multipage TIFF that I'm attaching to this. You can add this one to the repo freely.

> 
> I'm not sure I did anything other than supplying a `SetMatrix()` method in the `PdfXObject` base class.

And that is not a small thing and it is more than enough. You've also created the Matrix class. Thank you.

**Comment by ceztko** [comment]
> I will create a ticket for adding more properties to PDFImage (like resolution). It would not be TIFF specific.

Ok, but please understand earlier what has a chance of getting improved/added and what not. Handling of metadata with rotations from images is fine: one may also expect to find a property with the original rotation after the image is loaded but the the PDF specification has no obvious property where to store this information other than the raw transformation matrix. With image resolution do you mean calibrated pixel density (PPI/LPI)? Again, PDF specification has no obvious parameter where to store this information.

**Comment by ceztko** [comment]
Again: what resolution do you specifically mean, other than raw width and height? Not all pictures supply a calibrated resolution.
