### ISSUE TITLE
PoDoFo JavaScript interface

### ISSUE THREAD

**Issue by Antonov548** [podofo/podofo#164]
I working on JavaScript interface for PoDoFo https://github.com/Antonov548/podofo.js. It's only prototype.
But I have interest in improving it and thinking of building tool based on it.

Let me know please if it make sense to put this changes in the podofo repository.

I also think to work on some features in PoDoFo. I see that this is missing in TODO list.
1. Add support of decoding ICC based images.
2. I found that sometimes glyph ID's found incorectlly for some unicode symbols.

**Comment by Antonov548** [comment]
> I will look at your attempt to bind PoDoFo to JS with WebAssembly compiled code

Thanks for the feedback.
I think PoDoFo feats good for WebAssembly due to the concept of handling pdf in memory and it might be nice alternative to create PDF in JavaScript.

There is no much binding and only few tests for now, but I will implement more. Also, I guess I will prepare some examples of usage.

Okay, thanks I will wait for updates. It's defenatlly non trivial color space, I see that usuaully third parties are used to implement this color space.

> Please open a separate ticket with what you found.

I will try to find more information what exact cases lead to this issue and create separate ticket.

**Comment by ceztko** [comment]
> In few days (really) I will release a refactor/review of the PdfColor/PdfColorSpace classes. Please have a look at this work before submitting code decoding colors in non trivial PDF color spaces

Have a look at the message in the mailing list:
https://sourceforge.net/p/podofo/mailman/message/58778530/

And the commit itself: https://github.com/podofo/podofo/commit/4ebb40b87f94be4487574c1444cc0849325883b2

If you have some idea about decoding ICC based images, the code will have to inherit [`PdfColorSpaceFilter`](https://github.com/podofo/podofo/blob/master/src/podofo/main/PdfColorSpaceFilter.h).

**Comment by Antonov548** [comment]
> > In few days (really) I will release a refactor/review of the PdfColor/PdfColorSpace classes. Please have a look at this work before submitting code decoding colors in non trivial PDF color spaces
> 
> Have a look at the message in the mailing list: https://sourceforge.net/p/podofo/mailman/message/58778530/
> 
> And the commit itself: [4ebb40b](https://github.com/podofo/podofo/commit/4ebb40b87f94be4487574c1444cc0849325883b2)
> 
> If you have some idea about decoding ICC based images, the code will have to inherit and implement [`PdfColorSpaceFilter`](https://github.com/podofo/podofo/blob/master/src/podofo/main/PdfColorSpaceFilter.h).

Many thanks. I will take a look. Just did npm package - https://www.npmjs.com/package/podofo.js

**Comment by ceztko** [comment]
> I also think to work on some features in PoDoFo. [...]
> 1. Add support of decoding ICC based images.

Hello. Did you have a chance to look at ICC color spaces?

**Comment by Antonov548** [comment]
> > I also think to work on some features in PoDoFo. [...]
> > 
> > 1. Add support of decoding ICC based images.
> 
> Hello. Did you have a chance to look at ICC color spaces?

Hello. 

Yes, I checked this topic. And seems it's really not trivial and as for me seems requires additional third party library. For example lcms library.

I have seen this library used in another PDF parsers. I also have reviewed refactoring of color spaces code. I guess in general I can work on this topic if you agree on using some of the third parties.

Also I have worked on the online tool for creating PDF's using Podofo and there also rendering of PDF using Podofo parsers. Not everything is works there in tearms of rendering - some problems with fonts and images, but simple PDF's are works. I hope I can share this tool soon.

**Comment by ceztko** [comment]
There's no issue at at all to add obvious dependencies that is not worth reimplementing in PoDoFo, and you are welcome to share any code you're working on. Even if you don't end pushing an actual patch to PoDoFo your work will be recognized if it's good for integration and if the license is compatible (best double LGPL2.0+/MPL2).

**Comment by ceztko** [comment]
Hello, I just added a stub integration for lcms. You can enable by decommenting lines [here](https://github.com/podofo/podofo/blob/b082931af4230b12ca55baab780df43b2c6538e9/CMakeLists.txt#L179) and [here](https://github.com/podofo/podofo/blob/b082931af4230b12ca55baab780df43b2c6538e9/CMakeLists.txt#L257).

You can also find the prebuilt dependencies in the [deps](https://github.com/podofo/podofo-deps/tree/master/3rdparty/lcms2) repo (which is used by the [playground](https://github.com/podofo/podofo/tree/master/playground)).

I tested it briefly in the `helloworld.cpp` example:

```
#include <lcms2.h>
// ...
cmsHPROFILE hInProfile = cmsOpenProfileFromFile(R"(D:\Untitled2.icc)", "r");
```
Which you can enable with the following lines in the CMakeLists.txt:

```
include_directories(${LCMS2_INCLUDE_DIR})
target_link_libraries(helloworld ${PODOFO_LIBRARIES} ${LCMS2_LIBRARIES})
```

**Comment by ceztko** [comment]
I will use it for an unrelated task, but if you want to investigate adding ICC decode then you can start from this.

**Comment by ceztko** [comment]
I improved lcms2 conditional finding [support](https://github.com/podofo/podofo/blob/c5a3c4f2584bb3ee04b33cd43134f59391613004/CMakeLists.txt#L179), but it must still be enabled with a variable (`PODOFO_WANT_LCMS2`).
