### ISSUE TITLE
`helloworld` example doesn't work and more...

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#17]
`helloworld` example fails with:

```
PoDoFo encountered an error. Error: 1PdfErrorCode::InvalidHandle
Error Description: A nullptr handle was passed, but initialized data was expected.
Callstack:      #0 Error Source : base/PdfEncoding.cpp: 82
Information: The provided string can't be converted to CID encoding
```

Add following lines to `helloworld` example:

```cpp
// You could set a different color than black to draw
// the text.
// 
// painter.SetColor(1.0, 0.0, 0.0);

PdfTextState st;
st.FontSize = 8.0;
st.RenderingMode = PdfTextRenderingMode::Fill;

auto length = font->GetStringLength( "ABCDEFGHIKLMNOPQRSTVXYZ", st );

std::cout << "Length of \"ABCDEFGHIKLMNOPQRSTVXYZ\": " << length << std::endl;

// Actually draw the line "Hello World!" on to the PdfPage at
```

I want to say that `font->GetStringLength( "ABCDEFGHIKLMNOPQRSTVXYZ", st );` returns 0, that is an error.

**Comment by ceztko** [comment]
The example works for me but it's environment dependent so it may not work in your OS/installation.
Please pull https://github.com/podofo/podofo/commit/f1ce70ccbaf77fb8b493df07b42cf49636994592  and re-run `helloworld`. Here it prints:

```
The font name is ArialMT
The family font name is Arial
The font file path is C:\windows\fonts\arial.ttf
The font face index is 0
```

Attach the font that gets selected, I will see if there are bugs or the failure is to be expected. The point of `PdfFontManager::SearchFont` (was `GetFont` before) is that it will do a best effort to find a font that fits the parameters you passed. The matched font may be a fallback one that may not have the required features/glyphs. I don't know exactly if I can improve the API so the users are more aware that they search may not go as expected. One alternative is to print a warning, for example when the searched font pattern name is different from retrieved font name (or family font name), but I think it may be too much frequent warning. Or I may just provide a "test" API to see if the input text will be handled correctly, use it in `helloworld` and if the text is not supported on the found font in the system not use a fallback font, and that's become the way to do things.

**Comment by igormironchik** [comment]
OK, I see.

In my case the output is:

```
The font name is aakar-medium
The family font name is aakar
The font file path is /usr/share/fonts/truetype/fonts-gujr-extra/aakar-medium.ttf
The font face index is 0
```

This possibly explains why Cyrillic is not handled .

**Comment by igormironchik** [comment]
But what about my second question?

```cpp
PdfTextState st;
st.FontSize = 8.0;
st.RenderingMode = PdfTextRenderingMode::Fill;

auto length = font->GetStringLength( "ABCDEFGHIKLMNOPQRSTVXYZ", st );

std::cout << "Length of \"ABCDEFGHIKLMNOPQRSTVXYZ\": " << length << std::endl;
```

In my case `PdfFont::GetStringLength()` returns 0 always!

**Comment by igormironchik** [comment]
I confirm that I don't have `Arial` on my Ubuntu. OK.

Please consider my second question.

**Comment by ceztko** [comment]
> In my case `PdfFont::GetStringLength()` returns 0 always!

I fixed it, it was a bug. I also improved the helloworld example to just not draw Cyrillic text if the font doesn't support it. 

> I confirm that I don't have Arial on my Ubuntu

Actually, Arial is a Microsoft font, so you don't normally find in non-Microsoft systems, but you find compatible Arial family fonts. One common is LiberationSans. Do you actually have an idea why a [hindi](http://kartikm.github.io/fonts-aakar/) font was matched in your system?

**Comment by igormironchik** [comment]
> Do you actually have an idea why a [hindi](http://kartikm.github.io/fonts-aakar/) font was matched in your system?

I guess because this font is alphabetically on first place in my system.
