### ISSUE TITLE
PdfIndirectObjectList::GetDocument dereferences nullptr

### ISSUE THREAD

**Issue by ccreutzi** [podofo/podofo#174]
It looks like `PdfIndirectObjectList::GetDocument` was changed from returning a pointer to a reference instead, but the old documentation still says that this could be a `nullptr`:

``` cpp
public:
    /** \returns a pointer to a PdfDocument that is the
     *           parent of this vector.
     *           Might be nullptr if the vector has no parent.
     */
    inline PdfDocument& GetDocument() const { return *m_Document; }
```

The comment is correct, `m_Document` *is* `nullptr` here, e.g., during `TEST_CASE("testLoadEncrypedFilePdfParser")` in `EncryptTest.cpp`.

I didn't want to fiddle with your API design, so I have not created a patch to propose. Let me know if you would like me to. That would probably change (back?) to `PdfDocument const* GetDocument() const`.

**Comment by ceztko** [comment]
Thank you, good spot. The correct thing to do here is having the version returning the reference marked something like `GetDocumentUnsafe()` and be marked private, but it can still be used by `PdfParser` which is the only use and is already marked as friend. Then `GetDocument()` can be changed to return pointer.

**Comment by ceztko** [comment]
By the way, could you describe your level of involvement with regard to `PoDoFo` 1.0.0-dev? Are you just doing some flyby checks? Are you doing some bigger work and/or do you plan some bigger contributions?

**Comment by ccreutzi** [comment]
I've finally found a bit of time to put into very basic security checks, as we had discussed in the video conference call a long time back. That is going to involve larger patches than the ones I already sent, but I want to include test points for anything non-obvious.

Currently not planning to take anything from the TODO list – I might look into something like the `GetFields` topic, but I'd let you know before I start, to avoid duplicate work.

From: Francesco Pretto ***@***.***>
Date: Tuesday, 2. July 2024 at 13:03
To: podofo/podofo ***@***.***>
Cc: Christopher Creutzig ***@***.***>, Author ***@***.***>
Subject: Re: [podofo/podofo] PdfIndirectObjectList::GetDocument dereferences nullptr (Issue #174)

By the way, could you describe your level of involvement with regard to PoDoFo 1.0.0-dev? Are you just doing some flyby checks? Are you doing some bigger work and/or do you plan some bigger contributions?

**Comment by ceztko** [comment]
> Currently not planning to take anything from the TODO list

That's no problem. I will certainly clear the list myself for 1.0.

> That is going to involve larger patches than the ones I already sent

What topics? I hope these will fit with the API for 1.0.

Also please answer reviews for:
https://github.com/podofo/podofo/pull/173
https://github.com/podofo/podofo/pull/175

**Comment by ccreutzi** [comment]
Sorry, I don't see any question or other response in #173 and #175, I am waiting for your review there. What am I missing?

>> That is going to involve larger patches than the ones I already sent
> What topics? I hope these will fit with the API for 1.0.

I'm not planning to make API changes, mostly because I have not familiarized myself with your plans in sufficient detail yet. Thanks for making the changes needed here.

**Comment by ceztko** [comment]
Sorry, I didn't close reviews for #173 and #175, you should have received them now.

**Comment by ceztko** [comment]
I actually had a second thought since I had a final review of `PdfIndirectObjectList` which is not much safer to use (before a lot of internal methods were just exposed as public): now the parameter-less constructor is private and used only in unit tests. I reverted `GetDocument()` to return reference again in https://github.com/podofo/podofo/commit/e4387c274d47207ab5afe50a93d873c71aace4eb.
