### ISSUE TITLE
`PdfPainter::DrawImage()` doesn't draw

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#18]
Hello,

I'm continuing to port my application to `PoDoFo` 0.10.0 and caught new issues. 

```cpp
#include <podofo/podofo.h>

using namespace PoDoFo;

int main()
{
	PdfMemDocument doc;

	PdfPainter painter;

	auto & page = doc.GetPages().CreatePage( PdfPage::CreateStandardPageSize( PdfPageSize::A4 ) );

	painter.SetCanvas( page );

	auto img = doc.CreateImage();
	img->Load( "1.png" );

	painter.DrawImage( *img.get(), 50.0, 50.0 );

	painter.FinishDrawing();

	doc.Save( "1.pdf" );

	return 0;
}
```

In the resulting PDF I don't see image in the PDF viewer.

**Comment by igormironchik** [comment]
[1.pdf](https://github.com/podofo/podofo/files/10421529/1.pdf) is a PDF that was created with this small application.

**Comment by ceztko** [comment]
Yes, something bad is happening when loading the PNG. I will have a look at this tomorrow night.

**Comment by igormironchik** [comment]
The same situation with JPEG, with loading from buffer too.

**Comment by ceztko** [comment]
This is fixed and now unit tested both for PNG, JPEG. It was not in PoDoFo 0.9.x .
