### ISSUE TITLE
Cross-reference stream dictionary with /W [1 8 2]

### ISSUE THREAD

**Issue by ccreutzi** [podofo/podofo#180]
* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [X] Bug report
  - [ ] Feature request/suggestion

* **[Bug report] What is the current behavior?**

PoDoFo errors on reading this file: 
[mlsp_01_intro.pdf](https://github.com/user-attachments/files/16162950/mlsp_01_intro.pdf)

The place it throws an error is in `PdfXRefStreamParserObject::ReadXRefStreamEntry`, because this file has an XRef stream dictionary with `/W [1 8 2]` and PoDoFo does not expect any field with a size larger than 4.

* **[Bug report] What is the expected behavior?**

Other PDF readers do not seem to have a problem with this (real-world) file, I'd expect PoDoFo to simply read it, too.

* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**

```
target/podofotxtextract mlsp_01_intro.pdf
```

**Comment by ceztko** [comment]
Thank you, PR accepted.
