### ISSUE TITLE
Removing Implicit Encryption from PDF Documents

### ISSUE THREAD

**Issue by ferencIOS** [podofo/podofo#184]
* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [ ] Bug report
  - [x] Feature request/suggestion

* **[Feature request] What feature should be implemented in PoDoFo?**
I am wondering if it is possible to remove implicit encryption from a PDF document using this library. If this is feasible, could you please provide guidance or documentation on how to achieve this?

Thank you for your support and continued development of PoDoFo.

**Comment by ceztko** [comment]
I haven't used myself the functionality but I believe `doc.SetEncrypt(nulllptr)`, followed by a save, should do the trick and it's also unit tested now. There are [situations](https://github.com/podofo/podofo/blob/44bb43cf651eeaefdc1b515148565c0b3c68e069/TODO.md?plain=1#L20) where it shouldn't be allowed. Other than that, please report bugs if you find any.
