### ISSUE TITLE
PDF/A-3 Code Example

### ISSUE THREAD

**Issue by MrAhmedSayedAli** [podofo/podofo#185]
**Is there a Example Attach XML file to the PDF (PDF/A-3) ?**

like [This Link](https://zatca.wafeq.com/reference/pdfa-3)

**Comment by ceztko** [comment]
No sorry, I don't know much about embedded resources in PDF other than following the specification it should be doable (maybe the concept is actually not so tightly related to PDF/A-3). PDF/A compliance in general is a complex topic and PoDoFo doesn't help you too much with that other than technically preserving it following PDF incremental updates (and you are in charge of adding compliant content).

**Comment by petervwyatt** [comment]
Such PDFs could possibly be ZUGFeRD, OrderX or Fractur-X which extend PDF/A-3 to include specific kinds of XML payloads. See:
* https://www.ferd-net.de/standards/zugferd-2.2/index.html?changelang=4 
* https://www.ferd-net.de/standards/order-x/index.html 
* http://fnfe-mpe.org/factur-x/factur-x_en/

**Comment by ceztko** [comment]
@petervwyatt well, PoDoFo has a basic support for attachments through "7.11.3 File specification dictionaries" and now is also [unit tested](https://github.com/podofo/podofo/blob/905b2704f88f9dd0e8aeb77ff0c9c4590f23d9f1/test/unit/BasicTest.cpp#L152) (the API was a bit broken, but I fixed it). With those it enables the attachment view in Acrobat, see [TestFilespecAttachment.pdf](https://github.com/user-attachments/files/16557880/TestFilespecAttachment.pdf), which may be what the original poster was asking. It's still unclear to me if there's a specific relation of attachments with PDF/A-3.

**Comment by petervwyatt** [comment]
There is no new method of embedding file data in PDF/A-3 except that PDF/A-3 first introduced the feature called "Associated Files" (AF) and the **AFRelationship** key to file specification dictionaries. This was then adopted into PDF 2.0 (ISO 32000-2, 14.13 and Table 43) so you can refer to that (available at no-cost) along with [related errata](https://pdf-issues.pdfa.org/32000-2-2020/clause14.html#H14.13.5). There is also the PDF Association [PDF 2.0 AppNote on Associated Files](https://pdfa.org/resource/pdf-2-0-application-note-002-associated-files/). The ZUGFeRD, etc. specs also rely on AF with specific values for **AFRelationship** and specific types of XML payloads.

You'll need to get copies of the ISO 19005-3 and -4 standards if you want to create or validate PDF/A-3 (or PDF/A-4), or be an official "conforming processor".

**Comment by ceztko** [comment]
> There is no new method of embedding file data in PDF/A-3 except that PDF/A-3 first introduced the feature called "Associated Files" 

Thank you for the information.

> You'll need to get copies of the ISO 19005-3 and -4 standards if you want to create or validate PDF/A-3 (or PDF/A-4), or be an official "conforming processor".

Yes, I already have all PDF/A normative documents. PoDoFo doesn't offer any facility to create/validate (or convert to) PDF/A documents, but it can be used to build such functionalities.
