### ISSUE TITLE
failed signature - SigDict/ / Contents illegal data

### ISSUE THREAD

**Issue by omerbrandis** [podofo/podofo#188]
hello podofo team, 

I seems that even after your help in #143 & #147, I'm still haven't been able to get it right, 
when the pdf document is opened by adobe reader (version 2024.002.20991)I see the following msg : 
"at least one signature is invalid" 
- rev.1:signed by unknown,
- signature is invalid :  there are errors in the formatting or information contained in this signature ( support information : SigDict / Contents illegal data).
- signer's identity has not yet been verified.

using podofo master from 18.3.2024,
code : 

```
PoDoFo::PdfMemDocument document;


auto& FirstPage = document.GetPages().GetPageAt(0);
PoDoFo::PdfSignature & signature = FirstPage.CreateField<PoDoFo::PdfSignature>("Signature", PoDoFo::Rect(100, 600, 100, 100));
signature.SetSignatureDate(PoDoFo::PdfDate::LocalNow());
           

PoDoFo::charbuff outputBuffer;
auto stream = std::make_shared<PoDoFo::BufferStreamDevice>(outputBuffer);

std::string cert,pkey;
readTestInputFile("...", cert);
readTestInputFile("...", pkey);
           
auto signer = PoDoFo::PdfSignerCms(cert, pkey);
PoDoFo::SignDocument(document, *stream, signer, signature);

document.Save("....");
```

any help will be greatly appreciated.
:-)

**Comment by omerbrandis** [comment]
Dear ceztko thank you for your response, 

I'm afraid I need a bit more help then provided.

a. the error in adobe does not exactly match the one you have described.  it may be due to different adobe reader versions, but may also indicate a different problem.
attached are screen shots for my case.

[
![failed signature](https://github.com/user-attachments/assets/3fba0928-ec03-426c-be33-72ae8d6ca431)

![signature properties](https://github.com/user-attachments/assets/5b62c5fd-4b21-431e-b96b-f22ada9514c0)

I have found a "certificate details" button elsewhere, when pressed it does not show any information.
b. as for the privkey and cert validity.
I first generated the private key and cert using lets encrypt + certbot :
certbot certonly --standalone --key-type rsa -d myDomain.com -d www.myDomain.com
* please note that 2 domains are certified in one certificate.

the generated pem files seem to be valid, since I am able to use them for ssl , both chrome and firefox accept them.

I then converted them to der files using : 
sudo openssl rsa -in /etc/letsencrypt/live/myDomain.com/privkey.pem -out privateKey.der -outform DER
sudo openssl x509 -in /etc/letsencrypt/live/myDomain.com/fullchain.pem -out myCA.der -outform DER
* i've also tried an input file that does not have the full chain, only my cert, same results.
* I checked that myCA.der is valid using https://www.sslshopper.com/ssl-converter.html to convert it to crt then read its contents using https://www.sslshopper.com/certificate-decoder.html, it seemd to match the original content.

can you provide more information regarding :  "Check your pair certificate/private key: they should cryptographically match."
how can I check this ?

**Comment by omerbrandis** [comment]
+ is there a method that can be used to explicitly check the validity of the cert+privkey ?
possibly PdfSignerCms::ComputeSignature ?

**Comment by ceztko** [comment]
To explicitly check if the cert-private key are correctly paired you can just encrypt some text with the public key in the certificate, and decrypt the ciphered text it with the private key. The public API functions in PoDoFo are not suitable for the task. There are some RSA private functions but are very low level so I don't recommend those. You need any library (with any language: Java/C#/typescript...) that can perform simple RSA encryption. Also I recommend just trying a pair [certificate](https://github.com/podofo/podofo-resources/blob/master/mycert.der) - [key](https://github.com/podofo/podofo-resources/blob/master/mykey-pkcs1.der) that is guaranteed to work, to verify if the outcome changes. I can also confirm the library is indeed working as intended for basic and several advanced scenarios and if you have trusted certificates you'll see a green tick in the Adobe UI. I'm sorry, I don't have more clues on your issue.

**Comment by omerbrandis** [comment]
Dear Francesco,

Thank you again for trying to help.
I will check the validity of the der files as you have suggested.
In the meantime, can you please share the code you use to validate this
functionality ?  ( upload the source code as sttachment to this issue, or
point me to ita location in the repo, and possibly instructions on how to
execute it ?).

Thanks.

**Comment by ceztko** [comment]
Today LLM models are your friends. I tried this prompt "In c#, give me the code to open  a X.509 certificate in der format, encrypt a small text message, then decrypt the message giving a private key in der format in a separate file" and it gave me a good answe

**Comment by omerbrandis** [comment]
Dear Francesco, 

thanks for reopening this issue and replying quickly.

I am sure I will find the method to check the validity of my der files. :-)
but I would be surprised to find out that their content is the cause for the problem. since as I wrote before, their pem version seem to be valid.

I would like to execute  https://github.com/podofo/podofo/blob/master/test/unit/SignatureTest.cpp : TestSaveOnSigning, 
which seems to be the closest to my code at this point.
first with the mentioned der files ( which I did not see in the repo , and thus hope are created dynamically be the tester )
then if that works, I'll retry with my der files....

can you please provide instructions on how to do that?
( I tried "podofo home" /build/target$ ./podofo-unit
but got : terminate called after throwing an instance of 'std::runtime_error'
  what():  Missing Fonts directory. Ensure you have correctly fetched "extern/resources" git submodule )

:-)

**Comment by omerbrandis** [comment]
Hello Francesco,

i've tried building the most recent version,
it failed : 

git clone git@github.com:podofo/podofo.git
git submodule update --init
 mkdir -p build-linux-Release
cd build-linux-Release/
cmake -DCMAKE_BUILD_TYPE=Release -DARCH=linux-x86_64 -DPODOFO_BUILD_UNSUPPORTED_TOOLS=TRUE ..
make

[  0%] Building CXX object src/podofo/private/CMakeFiles/podofo_private.dir/CmsContext.cpp.o
In file included from ..../podofo-master/podofo/src/podofo/private/CmsContext.cpp:12:
.../podofo-master/podofo/src/podofo/private/OpenSSLInternal.h:54:35: error: expected constructor, destructor, or type conversion before ‘;’ token
   54 | DEFINE_STACK_OF(MY_ESS_CERT_ID_V2);
      |                                                                              ^
.../podofo-master/podofo/src/podofo/private/CmsContext.cpp: In member function ‘void PoDoFo::CmsContext::reset()’:
..../podofo-master/podofo/src/podofo/private/CmsContext.cpp:220:24: error: ‘X509_get0_pubkey’ was not declared in this scope; did you mean ‘X509_get_pubkey’?
  220 |     auto fakePrivKey = X509_get0_pubkey(m_cert);
      |                                         ^~~~~~~~~~~~~~~~
      |                                         X509_get_pubkey
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-unknown-warning-option’
src/podofo/private/CMakeFiles/podofo_private.dir/build.make:75: recipe for target 'src/podofo/private/CMakeFiles/podofo_private.dir/CmsContext.cpp.o' failed
make[2]: *** [src/podofo/private/CMakeFiles/podofo_private.dir/CmsContext.cpp.o] Error 1
CMakeFiles/Makefile2:644: recipe for target 'src/podofo/private/CMakeFiles/podofo_private.dir/all' failed
make[1]: *** [src/podofo/private/CMakeFiles/podofo_private.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2

i'm using gcc 9.4.0.

please advise.
:-)

**Comment by ceztko** [comment]
PoDoFo supports OpenSSL 1.1.x and 3.x up to latest 3.3.1 so I don't exactly what is going on on your system, you'll have to figure it out yourself. Check if you are using an obsolete openssl version. It is also guaranteed to work when compiled with the playground dependencies, which is a sort of development only sandbox.

**Comment by omerbrandis** [comment]
Dear Francesco

regarding my inability to build the latest version - lets put that aside for the moment.
I have a working build cloned on the 18.3.2024.
with this working build, and based on the provided unit tests and the der files taken from the master yesterday, 
I have built a small "tester" its code is attached, 
it is very similar to the code we have originaly discussed.
**its results are the same, meaning , even with your provided der files, the signature is invalid.**
please see attached.
[main.txt](https://github.com/user-attachments/files/16755748/main.txt)
[InMemorySigned-NoneEmptyStream.pdf](https://github.com/user-attachments/files/16755752/InMemorySigned-NoneEmptyStream.pdf)
[InMemorySigned-emptyStream.pdf](https://github.com/user-attachments/files/16755753/InMemorySigned-emptyStream.pdf)
[TestSignature-signed.pdf](https://github.com/user-attachments/files/16755754/TestSignature-signed.pdf)
[TestSignature-signed-from-stream.pdf](https://github.com/user-attachments/files/16755755/TestSignature-signed-from-stream.pdf)
[InMemory.pdf](https://github.com/user-attachments/files/16755756/InMemory.pdf)


:-)

**Comment by ceztko** [comment]
Ok, the problem here is that your are not properly following the examples in the tests, or the [FAQ](https://github.com/podofo/podofo?tab=readme-ov-file#faq), and you are abusing the API in subtle ways. The `PoDoFo::SignDocument()` will itself save the document: you should not save the document afterwards, and you should not continue operations on the same document instances after the signing operations as this is not guaranteed working (it's stated in the FAQ in the Q: "Can I sign a document a second time?"). Please understand that signing is usually an append operation and that the API requires you to provide a device stream filled with an existing document, and signing will happen in place. The following snippet is guaranteed working and will create an invisible signature on a copied `D:\test.pdf` document in the filesystem. The other examples in the tests/FAQ will teach how to sign documents in memory and/or add an appearance. Reorder your ideas and keep things simple and you'll see you'll be able to sign documents correctly.

```cpp
#include <fstream>
#include <filesystem>
#include <podofo/podofo.h>

using namespace std;
using namespace PoDoFo;
namespace fs = std::filesystem;

void readTestInputFile(const string_view& filepath, string& str)
{
    ifstream stream((string)filepath, ios_base::binary);

    stream.seekg(0, ios::end);
    if (stream.tellg() == -1)
        throw runtime_error("Error reading from stream");

    str.reserve((size_t)stream.tellg());
    stream.seekg(0, ios::beg);

    str.assign((istreambuf_iterator<char>(stream)), istreambuf_iterator<char>());
}

int main()
{
    string pkey;
    readTestInputFile(R"(D:\mykey-pkcs8.der)", pkey);

    string cert;
    readTestInputFile(R"(D:\mycert.der)", cert);

    fs::copy_file(fs::u8path(R"(D:\Staging\podofo\extern\resources\blank.pdf)"), fs::u8path(R"(D:\test.pdf)"), fs::copy_options::overwrite_existing);

    auto inputOutput = std::make_shared<FileStreamDevice>(R"(D:\test.pdf)", FileMode::Open);

    PdfMemDocument doc;
    doc.Load(inputOutput);

    auto& page = doc.GetPages().GetPageAt(0);
    auto& signature = page.CreateField<PdfSignature>("Signature", Rect());

    auto signer = PdfSignerCms(cert, pkey);
    PoDoFo::SignDocument(doc, *inputOutput, signer, signature);
}
```
