### ISSUE TITLE
Having trouble with drawing UTF-8 text

### ISSUE THREAD

**Issue by brouhaha** [podofo/podofo#189]
* **I'm submitting a:**
  - [ ] Feature request/suggestion

(really just a help request - sorry but it wasn't obvious where to ask for help)

* **[Feature request] What feature should be implemented in PoDoFo?**

In 0.9.8, I could easily render text strings from UTF-8 including things like Greek letters. I had code like:

```
  const PdfEncoding* encoding = new PdfIdentityEncoding(); // required for UTF8 characters
  font = document.CreateFont("NotoSans",  // pszFontName
				       false,               // bSymbolCharset
				       encoding);           // pEncoding
  // Note that "NotoSans-Medium" does not work!
  painter.SetFont(font);
  font->SetFontSize(height);
  std::string text = "Σ+";
  const pdf_utf8* text = reinterpret_cast<const pdf_utf8*>(text.c_str())
  painter.DrawText(x_in, y, text);

```
In 0.10.3, I'm using:

```
  font = document.GetFonts().SearchFont("NotoSans-Medium");
  // Note that the "-Medium" not only works, but it's now REQUIRED!
  painter.TextState.SetFont(*font, height);
  std::string text = "Σ+";
  painter.DrawText(text, x, y);

```
and that works for ASCII, but not UTF-8 Greek letters. Throws the exception:

  Callstack:t#0 Error Source: main/PdfEncoding.cpp(82), Information: The provided string can't be converted to CID encoding

So I guess I still need a PdfIdentityEncoding, but I haven't figured out how to do it. I've tried:

```
  const PdfEncodingMap* iem = new PdfIdentityEncoding(PdfIdentityOrientation::Horizontal);
  PdfFontCreateParams params =
  {
    PdfEncoding(iem);
  };
  pdf_font[SANS] = document.GetFonts().SearchFont("NotoSans-Medium", params);

```
but the compiler won't let me construct the PdfEncoding from the encoding map pointer, despite that it looks to me like there's such a constructor.

Anyhow, I have no idea whether I'm even on the right track here, so any suggestions would be very welcome.

Thanks!

* **Please tell us about your environment:**
  - Version/git revision: [0.10.3]
  - Operating System: [Linux (64 bits)
  - Package manager used: [yum]

**Comment by ceztko** [comment]
I can't reproduce with master. I downloaded the font from https://fonts.google.com/noto/specimen/Noto+Sans , and saved "NotoSans-Medium.ttf" in a folder and used it like this:

``` cpp
PdfMemDocument doc;
PdfFontManager::GetFontConfigWrapper().AddFontDirectory(R"(D:\Fonts)"); // The folder with "NotoSans-Medium.ttf"
auto& page = doc.GetPages().CreatePage();
auto font = doc.GetFonts().SearchFont("NotoSans");
cout << "Font name: " << font->GetMetrics().GetFontName() << endl;               // Prints "NotoSans-Medium"
cout << "Font family name: " << font->GetMetrics().GetFontFamilyName() << endl;  // Prints "Noto Sans"
{
   PdfPainter painter;
   painter.SetCanvas(page);
   painter.TextState.SetFont(*font, 11);
   std::string text = "Σ+";
   painter.DrawText(text, 100, 600);
}
doc.Save(R"(D:\test.pdf)");
```

Attached the result: 
[test.pdf](https://github.com/user-attachments/files/16922204/test.pdf)

I believe the issue is that you didn't really matched "NotoSans-Medium" searching with `SearchFont("NotoSans")`. You have to debug the metrics inspecting `font->GetMetrics().GetFontName()` and `font->GetMetrics().GetFontFamilyName()` like in the example above. By default PoDoFo >= 0.10.x searches font by family name, like in PoDoFo 0.9.x. It's unclear why matching should be better in your machine with 0.9.x: you should do some debugging with font config tools like `[fc-match](https://linux.die.net/man/1/fc-match)`. Also ensure modern PoDoFo is linking a recent fontconfig build, because that is the 3rd party library that is used to serach for fonts and could make a big difference in the quality of the results.

**Comment by brouhaha** [comment]
Using your code, I've confirmed that even without the AddFontDirectory(), if I ask for "NotoSans", it gets "NotoSans-Medium". I could have sworn that I tried that before without success, but I must be wrong, or had some other difficulty. If I ask for a variant like "NotoSans-Medium", that gets no reported error, but the font it finds is BitstreamVeraSans-Roman, which does not have the "Σ".

If you don't mind, I have one more related question. If I do want a very specific font like "NotoSans-SemiCondensedLightItalic.ttf", what should I do to use that? It's in the same directory as NotoSansMedium.ttf.

Thank you!

**Comment by ceztko** [comment]
>  If I ask for a variant like "NotoSans-Medium", that gets no reported error, but the font it finds is BitstreamVeraSans-Roman

That's because it's searching the family name. The other option is to search for the postscript name:

```
PdfFontSearchParams search;
search.MatchBehavior = PdfFontMatchBehaviorFlags::MatchPostScriptName;
auto font = doc.GetFonts().SearchFont("NotoSans-Medium", search);
```

Or load it directly with `doc.GetFonts().GetOrCreateFont("<pathtofont>")`. It would be great to have the search to find the font with both family and postscript name of the font (with a priority on family). I remember I tried something but then I chose to search on family name only, maybe because I got worse results with what I was trying.

**Comment by brouhaha** [comment]
I figured out how to do it. Not sure if this is the best way, but it works.

```
  auto& fmgr = doc.GetFonts();
  auto& font = fmgr.GetOrCreateFont("fonts/NotoSans-SemiCondensedBlackItalic.ttf");

```

And I see that's what you recommended while I was trying to figure it out, but without the intermediate variable I used for the font manager.

Thanks! This satisfies my urgent font issues. I have some OTF fonts that won't load, but I think I can convert them to TTF.

**Comment by ceztko** [comment]
OpenType fonts are supported.

**Comment by brouhaha** [comment]
Here's one that gives me an error when I try GetOrCreateFont() with its path. FontForge can load it with a few warnings about non-standard glyph mapping.

[stixtwomath-regular.zip](https://github.com/user-attachments/files/16927168/stixtwomath-regular.zip)

Result:

terminate called after throwing an instance of 'PoDoFo::PdfError'
  what():  PdfErrorCode::InvalidFontData, The font data is invalid.
Callstack:t#0 Error Source: main/PdfFontManager.cpp(210), Information: Could not parse a valid font from path fonts/STIXTwoMath-Regular.otf
Aborted (core dumped)

Let me know if you want me to open a new issue for it.

**Comment by ceztko** [comment]
Hmm, you are using PoDoFo 0.10.3, right? That font is not exactly an OTF font, but a CFF (Compact Font Representation), that is a Type1 font in a OpenType container, and it's not supported in PoDoFo. By the way, I found a bug in PoDoFo master trying to load your font.

**Comment by brouhaha** [comment]
OK, thanks for the explanation. I'll see whether FontForge can export it as a TTF or something. You can close this issue.
I really appreciate the help. I use PoDoFo to create PDF files for relegendable keycaps for custom-made calculators, both for printing and for cutting with a Silhouette cutter. I'm working on a new calculator, but you can see the one John and I built and exhibted last year:
    https://hackaday.com/2023/11/07/nixie-tube-rpn-calculator-project/
I'll try to remember to give a shout out for PoDoFo at this year's conference, in less than two weeks.

**Comment by ceztko** [comment]
Good! I just [pushed](https://github.com/podofo/podofo/commit/c543968ea711c87d8839bc9d37f2091f3382b0b7) in master a possible improvement in the quality of font searches, by matching both family and postscript name of fonts by default (this is new compared to [0.9.x](https://github.com/podofo/podofo/blob/5723d09bbab68340a3a32923d90910c3d6912cdd/src/podofo/doc/PdfFontCache.cpp#L829), which was searching only family name). I verified in a small test that in this way one can search for both "NotoSans" and "NotoSans-Medium" and finding the best candidate for both patterns. For me it's important that there's also an option to search only postscript names, which may be more accurate knowing the exact name of the font in some situations.

**Comment by ceztko** [comment]
I forgot to mention: `PdfIdentityEncoding` in general is not really related to support utf-8/Unicode text. It was just a coincidence that in some fonts glyphs are put in the same order as Unicode characters: it won't work in general, nor it could work in general in 0.9.x because of the same reason. PoDoFo >= 0.10 now creates a custom encoding by default, which will support all Unicode characters you insert through different means (eg. drawing text with the painter).

**Comment by brouhaha** [comment]
The font search improvement and the default custom encoding both sound great!
The API updates since 0.9.x do make things a lot more logical. The only other thing that tripped me up a bit was GraphicsState.SetCurrentMatrix(); because of the name, I thought I had to get the current matrix, multiply by my desired transform, and then set the matrix. Of course, all I have to do is call SetCurrentMatrix(), since that uses the PDF "cm" operator. I think something like "ApplyTransformMatrix" would be a better description of what it does, but I'm not going to push hard for a change.
For now, since I want very specific fonts, and because the font licenses are suitable, I've just included the fonts in my repo, and will continue to load them by explicit path. It turns out that the STIXFont people do provide a TTF, so that's solved too.
I've made a lot of progress, and aside from pie-in-the-sky stuff like Unicode combining glyphs, which I know there's already a request for, I'm pretty satisfied with 0.10.3.
I'll make my github repo public after we show off the new calculator the weekend after next, and let you know. I'm not going to claim that my code is a particularly great example, since it's pretty hastily thrown together, a few days with 0.9.8 in October of last year, and now a few days updating to 0.10.3 this week.
Thank you again for all the assistance!

**Comment by ceztko** [comment]
>  The only other thing that tripped me up a bit was GraphicsState.SetCurrentMatrix()

As you have figured it out, that `SetCurrentMatrix()` really ends using the `cm` operator, and the get/set semantics is related to the fact that you are really setting a value in the state. How this set value is then interpreted then it's a matter of what the PDF specification dictates (and PDF specification doesn't allow to set the current absolute transformation matrix). I believe this could be just documented. Patch welcome to master.

**Comment by ceztko** [comment]
But then I commit a mistake in the sense I identify the matrix that is being set with the CTM matrix, which is wrong:

https://github.com/podofo/podofo/blob/67bc0cbca4e86475475e2c333bf4fd4f02a3e823/src/podofo/main/PdfPainter.cpp#L1206

I have to think about it. Maybe after all you are right that `SetCurrentMatrix` may be changed to `ApplyTransformMatrix`, or renamed it to something else. I have to think about it. I will do it before 1.0 .

**Comment by brouhaha** [comment]
I notice that the PDF standard's description of the cm operator is "Concatenate matrix to current transformation matrix", so maybe "ConcatenateTransformMatrix" might be even more descriptive. Anyhow, it works, so I'm not terribly concerned about the name.
I think you're right that there's no way to set a absolute transform matrix. I use Save() and Restore() a _lot_.     :-)

**Comment by ceztko** [comment]
Done in https://github.com/podofo/podofo/commit/b223aec7337538ec433ed91a9f7598a64b589a4a

**Comment by brouhaha** [comment]
Great, thanks!
