### ISSUE TITLE
Cannot build Podofo without libidn 1.x

### ISSUE THREAD

**Issue by hectorem2** [podofo/podofo#190]
* **I'm submitting a:**
  - [x] Bug report

* **[Bug report] What is the current behavior?**
* I cannot compile the library if LibIDN 1.x is not installed, all because of #ifdef PODOFO_HAVE_LIBIDN. In the CMake files, this preprocessor variable can be disabled so that the library is optional, but then enums are not defined and PdfEncrypt.h and PdfEncrypt.cpp don't compile.

* **[Bug report] What is the expected behavior?**
* It could be decided whether to make LibIDN 1 required (or LibIDN 2 maybe)  or to correct the #ifdef PODOFO_HAVE_LIBIDN blocks; that way, others may find easier to build and try this library.

* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**
* Just try to build Podofo without LibIDN 1 installed. It looks like LibIDN 2 won't work.

* **Please tell us about your environment:**
- Ubuntu 24.04 LTS
- GCC 13.2.0
- All required libraries' headers installed from the official repositories (with apt).
  
  - Version/git revision: [1.10.0]
  - Operating System: [all | Windows (32/64 bits) | Linux (32/64 bits) | MacOs]
  - Package manager used: [source | vcpkg | conan | apt | yum]

**Comment by ceztko** [comment]
LibIDN 2 does different stuff from LibIDN 1 so it's not an option at all. Please better specify the version you have the issue, as 1.10.0 is a non existing tag and the last official release is 0.10.4. For the future, libIDN dependency will be removed at some point after 1.0.

**Comment by ceztko** [comment]
The issue was only present in master, fixed.
