### ISSUE TITLE
PdfPage::MovePageAt(unsigned int index) is not working

### ISSUE THREAD

**Issue by kossiLeBeau** [podofo/podofo#191]
Fill the form below, removing parts that don't apply, including this note.
Please note that PoDoFo is currently activelly developed and maintained only
by a single person. The quickest and safest way to ensure bugs that
affects you are fixed and the features you need are checked-in is to
[contribute](https://github.com/podofo/podofo#contributions) high-quality patches.

* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [x ] Bug report
  - [ ] Feature request/suggestion

* **[Bug report] What is the current behavior?**
* PdfPage::MoveAt(unsigned int index) is not working at all. Environment is Windows 10 Pro VC 2019. It does not even throw an exception.

* **[Bug report] What is the expected behavior?**
It is supposes to move the current Pdf Page to a new position indicated by index

* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**
  std::string_view sName("qqq.pdf");
  PdfCommon::SetMaxLoggingSeverity(PdfLogSeverity::None);

  try {
    pdf.Load(sName);
    PdfPageCollection & pages = pdf.GetPages();
    std::cout <<  "Number of pages: " << pages.GetCount() << std::endl;
     pages.FlattenStructure();
     PdfPage &page = pages.GetPageAt(3);
     std::cout << page.GetIndex();  
      page.MoveAt(0);  //  it stayed in the fuction for a while, and returns to the command prompt.
      std::cout << "Going to save to a new file" << std::endl;   // never got this message,
     sName = "qqx.pdf";
     pdf.save(sName);
     std::cout << "Page saved" << std::endl;
  }
  catch(PdfError &e) {
     std::cout << e.GetName() << std::endl;
  }
   
* **[Feature request] What feature should be implemented in PoDoFo?**

* **Please tell us about your environment:**
  
  - Version/git revision: [1.10.0]
  - Operating System: [all | Windows (32/64 bits) Windows 10
  - Package manager used: [source | vcpkg 

* **[Bug report/Feature request] Other information**

**Comment by ceztko** [comment]
Ah, yes. There was a [CHECK-ME](https://github.com/podofo/podofo/blob/c42f4ad5beb18c34d99ac023081042c0986b3623/src/podofo/main/PdfPage.cpp#L303) that I put some time ago. The method was non sense, the classical example of using a sledgehammer to crack a nut. Fixed in master and 0.10.x (but this won't trigger a new release, as it's not critical).
