### ISSUE TITLE
Deferred/async pdf signing

### ISSUE THREAD

**Issue by franfcunha** [podofo/podofo#192]
Dear Francesco,

Thanks for supporting this amazing project. I can just imagine how difficult it can be to answer all the bugs, feature requests and newbie's questions, just like mine, but I want to make it clear that I tried several approaches before opening this issue. 

I am trying to implement sequential/async/deferred pdf signature. The scheme is the following:

1. I have an input .pdf that I want to sign

2. I am responsible for computing a compact representation of the pdf (hash) and send to a webservice (which manages the signer private key) that will return a signature in the form of a signed hash as well as the x509 certificate. So, I don't have the signer private key. 

I tried to decompose the process in two steps:

Process A. PDF preparation / creation of an empty/blank signature. I wrote the resulting pdf, computed the hash and made a request to the external service that returned the signature. I saved the signature in a text file.

Process B. Tried to inject the signed hash in the signature field created in the pdf generated in process A.

Process A code:
 
```
#include <podofo/podofo.h>
#include <fstream>

using namespace std;
using namespace PoDoFo;

using charbuff = charbuff_t<>;

ifstream open_ifstream(const string_view& filename, ios_base::openmode mode)
{
#ifdef _WIN32
    auto filename16 = utf8::utf8to16((string)filename);
    return ifstream((wchar_t*)filename16.c_str(), mode);
#else
    return ifstream((string)filename, mode);
#endif
}

void readTo(charbuff& str, istream& stream)
{
    stream.seekg(0, ios::end);
    auto tellg = stream.tellg();
    
    if (tellg == -1)
        return;

    str.resize((size_t)tellg);
    stream.seekg(0, ios::beg);
    stream.read(str.data(), str.size());
    
    if (stream.fail())
        return;
}

void ReadTo(charbuff& str, const string_view& filepath)
{
    ifstream istream = open_ifstream(filepath, ios_base::binary);
    readTo(str, istream);
}


void readInputFile(const string_view& filepath, string& str)
{
#ifdef _WIN32
    auto filepath16 = utf8::utf8to16((string)filepath);
    ifstream stream((wchar_t*)filepath16.c_str(), ios_base::binary);
#else
    ifstream stream((string)filepath, ios_base::binary);
#endif

    stream.seekg(0, ios::end);
    if (stream.tellg() == -1)
        throw runtime_error("Error reading from stream");

    str.reserve((size_t)stream.tellg());
    stream.seekg(0, ios::beg);

    str.assign((istreambuf_iterator<char>(stream)), istreambuf_iterator<char>());
}


int main() {

    charbuff buff;
    
    std::ifstream  src("/home/mini_projects/pdfsign/data/texto.pdf", std::ios::binary);
    std::ofstream  dst("/home/mini_projects/pdfsign/data/texto2.pdf",   std::ios::binary);
    
    dst << src.rdbuf();

    auto stream = std::make_shared<FileStreamDevice>("/home/mini_projects/pdfsign/data/texto2.pdf", FileMode::Open);

    string cert;
    readInputFile("/home/mini_projects/pdfsign/data/x509.der", cert);

    PdfMemDocument doc(stream);
    auto& page = doc.GetPages().GetPageAt(0);

    const PoDoFo::Rect r(50,50,100,100);

    const std::string_view s{ "blabla" };

    auto& field = page.CreateField(s, PdfFieldType::Signature, r, true);
    
    auto& signature = dynamic_cast<PdfSignature&>(field);

    PdfSignerCmsParams params;
    auto signer = std::make_shared<PdfSignerCms>(cert, params);
    PdfSigningContext ctx;
    auto signerId = ctx.AddSigner(signature, signer);
    PdfSigningResults results;

    ctx.StartSigning(doc, stream, results, PdfSaveOptions::NoMetadataUpdate);
    
    ReadTo(buff, "/home/mini_projects/pdfsign/data/texto2.pdf");
    
    return 0;
}
```

This code is able to generate a pdf with an empty signature, but no identification is shown despite the x509 was provided. Note: if I use doc.save("/home/mini_projects/pdfsign/data/texto2.pdf") instead of ReadTo("/home/mini_projects/pdfsign/data/texto2.pdf") there is a crash with the following info: 

"terminate called after throwing an instance of 'PoDoFo::PdfError'
  what():  PdfErrorCode::UnexpectedEOF, End of file was reached unxexpectedly.
Callstack:t#0 Error Source: main/PdfMemDocument.cpp(223)
t#1 Error Source: private/PdfWriter.cpp(109)
t#2 Error Source: private/PdfParserObject.cpp(93), Information: Unable to parse the stream for object 2 0 R
t#3 Error Source: private/PdfParserObject.cpp(194), Information: Unexpected EOF when reading stream"

I believe that the expected usage is memdocument.save() right?

Process B code:

```
#include <podofo/podofo.h>
#include <fstream>
#include <iostream>

using namespace std;
using namespace PoDoFo;

using charbuff = charbuff_t<>;

ifstream open_ifstream(const string_view& filename, ios_base::openmode mode)
{
#ifdef _WIN32
    auto filename16 = utf8::utf8to16((string)filename);
    return ifstream((wchar_t*)filename16.c_str(), mode);
#else
    return ifstream((string)filename, mode);
#endif
}

void readTo(charbuff& str, istream& stream)
{
    stream.seekg(0, ios::end);
    auto tellg = stream.tellg();
    
    if (tellg == -1)
        return;

    str.resize((size_t)tellg);
    stream.seekg(0, ios::beg);
    stream.read(str.data(), str.size());
    
    if (stream.fail())
        return;
}

void ReadTo(charbuff& str, const string_view& filepath)
{
    ifstream istream = open_ifstream(filepath, ios_base::binary);
    readTo(str, istream);
}


void readInputFile(const string_view& filepath, string& str)
{
#ifdef _WIN32
    auto filepath16 = utf8::utf8to16((string)filepath);
    ifstream stream((wchar_t*)filepath16.c_str(), ios_base::binary);
#else
    ifstream stream((string)filepath, ios_base::binary);
#endif

    stream.seekg(0, ios::end);
    if (stream.tellg() == -1)
        throw runtime_error("Error reading from stream");

    str.reserve((size_t)stream.tellg());
    stream.seekg(0, ios::beg);

    str.assign((istreambuf_iterator<char>(stream)), istreambuf_iterator<char>());
}


int main() {
    
    charbuff buffout;
    
    string signedHash;
    readInputFile("/home/mini_projects/pdfsign/data/signature", signedHash);

    std::ifstream  src("/home/mini_projects/pdfsign/data/texto2.pdf", std::ios::binary);
    std::ofstream  dst("/home/mini_projects/pdfsign/data/texto2_signed.pdf",   std::ios::binary);
    
    dst << src.rdbuf();

    auto stream = std::make_shared<FileStreamDevice>("/home/mini_projects/pdfsign/data/texto2_signed.pdf", FileMode::Open);

    string cert;
    readInputFile("/home/mini_projects/pdfsign/data/x509.der", cert);
    
    PdfMemDocument doc(stream);

    auto& page = doc.GetPages().GetPageAt(0);
    
    for (auto f : page.GetFieldsIterator()){
        
        if (f->GetFullName() == "blabla"){
            cout << "Found signature item!";
    
            auto& signature = dynamic_cast<PdfSignature&>(*f);

            PdfSignerCmsParams params;
            auto signer = std::make_shared<PdfSignerCms>(cert, params);

            PdfSigningResults results;
            
            PdfSigningContext ctx;
            auto signerId = ctx.AddSigner(signature, signer);

            results.Intermediate[signerId] = signedHash;
            
            ctx.FinishSigning(results);
            
            std::cout << signedHash;
            
            break;
        
        }
    }
    
    doc.Save("/home/mini_projects/pdfsign/data/texto2_signed.pdf");

    return 0;

}
```

When running the code I get the following error:

"terminate called after throwing an instance of 'PoDoFo::PdfError'
  what():  PdfErrorCode::InternalLogic, An internal error occurred.
Callstack:t#0 Error Source: main/PdfSigningContext.cpp(68), Information: A sequential signing has not been started
Aborted (core dumped)"

I would be glad to receive some orientation on process. Am I understanding it right? How can I effectively split these two stages of the processing so that the signature can be injected into the empty signature?

Thank you so much!

**Comment by ceztko** [comment]
I understand what you are trying to do, but that feature is currently not available: the signing must be started and finished in the same session, there's no cold resume. Your use case is interesting, but it's not the only one. For example with the current system you can sign several documents in a row better handling exceptions in the middle while contacting the external service, which may be inconvenient having just an event based signing mechanism. In general an event based mechanism is also harder to wrap in higher level language, hence it's convenient to have a 2 steps solution (still with the requirement that they must be completed in the same session). About your exact requirement: I have no plan to implement this feature, so don't assume I will do it anytime soon, unless for any reason it becomes a priority for me. Feel free to fork and implement your solution. If I am not too busy, I will write it later how I imagine the API for this feature, so if you want to contribute back your implementation you'll have higher chances it will be integrated quickly (please note there's high bar for the contributions with regard to API quality).

**Comment by franfcunha** [comment]
Thank you for your reply. Based on your explanation, I really don’t understand what you mean with an “external service”. The use case shown in the tests explicitly mentions the case of an external signing service. How isn’t this the same as the use case I brought to the table? Can you please ellaborate on the ? There is a chance I am getting all these concepts wrongly :-/

**Comment by ceztko** [comment]
By "external service" I mean either an "external [remote] signing service", or a physical signing token, so the definition is not different with regard to your specific use case. The point is that you presented the use case with the two processes A and B assuming that you can store a temporary PDF that hasn't complete the signing in process A and another process B that reloads the temporary PDF stored in A and finishes the signing. That's not supported, you'll have to call `StartSigning` and `FinishSigning` sequentially in the same session as in the [unit](https://github.com/podofo/podofo/blob/a9920fff50e2cc0c6dcfcf64fe4472b54df424ed/test/unit/SignatureTest.cpp#L132) test. The use case you presented is a sort of cold state resuming of a signing operation, and IMO it could be interesting to support in the future. If you just wanted to sign a document using the sequential signing (as I called it somewhere in the API documentation, but I could switch to use the "deferred" adjective, as you suggested), then just call `StartSigning` and `FinishSigning` in the process A, no need for B.

**Comment by ceztko** [comment]
I just renamed sequential -> deferred, which is just the better definition I searched for a while, and poor GPT3 couldn't help me find it.

**Comment by franfcunha** [comment]
I need to test but do you think that is it technically possible to achieve this within a single signing session? My only doubt is that, in that case I am supposed to have already a signed hash available (i.e. i already communicated with the external service the original pdf that I want to sign). In such scenario, the resulting signed pdf would have a content different than the original one, I guess?…

**Comment by ceztko** [comment]
Oh my...now I see what you're doing wrong. The hash to sign is provided to you in the `PdfSigningResults` instance after `StartSigning()`:

```cpp
PdfSigningResults results;
ctx.StartSigning(doc, stream, results, PdfSaveOptions::NoMetadataUpdate);

// This is the equivalent of a signing the hash with an external service. The hash
// to sign is in the in the intermediate results after starting the operation
charbuff signedHash;
ssl::DoSign(results.Intermediate[signerId], pkey, params.Hashing, signedHash);

// You can fill the signed hash in the same results instance, avoiding creating a new one
results.Intermediate[signerId] = signedHash;

// You finish the process right away
ctx.FinishSigning(results);
```

It's no clear in your code what hash you were signing, as you was loosing the correct one which was provided to you. You **can't** obtain it from the raw bytes of the document saved after `StartSigning()`, as it's missing relevant bytes that are stored in the `PdfSigningContext`. Also you **can't** resume a signing operation on a newly loaded document as you were trying to do in process B, you have to fill the signed hash right away after `StartSigning`. Take your time, reorder your ideas, and you'll end up with a correctly signed document.
