### ISSUE TITLE
Page::MoveAt(unsigned index)  produces a wrong page sequence after the move

### ISSUE THREAD

**Issue by kossiBlaise** [podofo/podofo#193]
Fill the form below, removing parts that don't apply, including this note.
Please note that PoDoFo is currently activelly developed and maintained only
by a single person. The quickest and safest way to ensure bugs that
affects you are fixed and the features you need are checked-in is to
[contribute](https://github.com/podofo/podofo#contributions) high-quality patches.

* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [x ] Bug report
  - [ ] Feature request/suggestion

* **[Bug report] What is the current behavior?**
If index1 is the index of the current page, and page:MoveAt(newIndex) is executed,  in the resulting pdf, the two pages at Index1 & newIndex are just swapped. I do not believe that this is the behavior expected after a call to this function.

* **[Bug report] What is the expected behavior?**
If p1, p2. p3, p4 are labels of pages of indexes (i0, i1, i2, i3) in the pdf file. If I move i0 to i2, I should have the label sequence p2, p3, p1, p4. The function Page::MoveAt is producing: p3, p2, p1, p4.
* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**

PdfDocument pdf;
pdf.Load("testPages.pdf");
PdfPageCollection &pages = pdf.GetPages();
PdfPage &page = pages.GetPageAt(0);
page.MoveAt(2);
pdf.Save("qqx.pdf", PdfSaveOptions::None);

* **[Feature request] What feature should be implemented in PoDoFo?**

* **Please tell us about your environment:**
  
  - Version/git revision: [1.10.0]
  - Operating System: [all | Windows (32/64 bits) 
  - Package manager used: [source  

* **[Bug report/Feature request] Other information**

  E.g. sample PDF documents, stacktraces, related issues, links for us to have contex, suggestions how to fix, etc.
[testPages.pdf](https://github.com/user-attachments/files/17302759/testPages.pdf)
[qqx.pdf](https://github.com/user-attachments/files/17302760/qqx.pdf)

**Comment by kossiBlaise** [comment]
PdfPageCollection &pages - pdf.GetPages();
Should be:
PdfPageCollection **&pages = pdf.GetPages();**

**Comment by kossiLeBeau** [comment]
The following code segment fixes the behavior described in the report.
This is a brutal approach. No efficiency is presumend.

bool  PdfPageCollection::TryMovePageAt(unsigned atIndex, unsigned toIndex)
{      
         PODOFO_ASSERT(atIndex` < m_Pages.size() && atIndex != toIndex);
        if (toIndex >= m_Pages.size())
         return false;

       FlattenStructure();

       unsigned int index;
      
      if (toIndex > atIndex) {
        unsigned int inFront;
        for (index = atIndex; index < toIndex; index ++) {
            inFront = index + 1;
            std::iter_swap(m_Pages.begin() + index, m_Pages.begin() + inFront);
            m_kidsArray->SwapAt(index, inFront);
            m_Pages[index]->SetIndex(index);
            m_Pages[inFront]->SetIndex(inFront);
        }
      }
      else {
        unsigned int behind;
        for (index = atIndex; index > toIndex; index --) {
            behind = index - 1;
            std::iter_swap(m_Pages.begin() + behind, m_Pages.begin() + index);
            m_kidsArray->SwapAt(behind, index);
            m_Pages[index]->SetIndex(index);
            m_Pages[behind]->SetIndex(behind);
        }
      }
  return false;
}

**Comment by ceztko** [comment]
Thanks for reporting: I probably confused the function with a swap semantics which is not as useful. I extended the test, it should be fixed now but please give me a feedback. Also I renamed `MoveAt()` -> `MoveTo()` which it makes more sense to me.

**Comment by kossiBlaise** [comment]
Hello Sir,

I need some help finding information on:
1)  template `<typename TNameTree>`
     const TNameTree   *GetTree() const ..

    Where can I find some information on what is the value set of **TNameTree** which should be used to make a call.

2) Similar question on
**template `<typename TElement>`
class PdfNameTree final : public PdfNameTreeBase**

Value set of **TElement** to be used to instantiate PdfNameTree.

I really appreciate it.

**Comment by ceztko** [comment]
Hello.

> Where can I find some information on what is the value set of TNameTree which should be used to make a call.

These are the currently supported trees:
https://github.com/podofo/podofo/blob/211daea5fba3b9f506f5195b893c4bb10d3cfc2f/src/podofo/main/PdfNameTrees.h#L114

Namely `PdfEmbeddedFiles`, and `PdfDestinations`. Other tree types can be submitted through patches, or you manually handle them through low level [`PdfNameTreeOperations`](https://github.com/podofo/podofo/blob/master/src/podofo/main/PdfNameTreeOperations.h).


> Similar question on
>```
>template <typename TElement>
>class PdfNameTree final : public PdfNameTreeBase
>```

That is infrastructural only if you plan to implement a new `PdfNameTree` with its `TElement` and send patches. See the current implementations here:

https://github.com/podofo/podofo/blob/211daea5fba3b9f506f5195b893c4bb10d3cfc2f/src/podofo/main/PdfNameTree.h#L100

**Comment by kossiBlaise** [comment]
Hello Sir,
 Sorry for not getting back at you earlier to express my thanks.
Looking at PdfNameTrees class, we have member functions to GetValue(), but are lacking the functions to set the values. That function exists, but are private.

For reason of symmetry, wouldn't you think that it would OK to make the setter functions public too?

Thankfully,
yours.

**Comment by ceztko** [comment]
Look here https://github.com/podofo/podofo/blob/6a2a0bced7a24192f93ff43ee81dcaf014f84420/test/unit/BasicTest.cpp#L153

You have `AddValue`.

> By the way, it would be nice to add on the level of PdfMemDocument the following functions:
> ::AttachFile()
> ::GetAttachedFiles().

No. Just use properly the name trees.

**Comment by ceztko** [comment]
You don't need to resort to `PdfNameTreeOperations`. You can use `PdfEmbeddedFiles` name tree which supports directly `PdfFileSpec`, like this:

```
auto& embeddedFiles = nameTrees.GetOrCreateTree<PdfEmbeddedFiles>();
embeddedFiles.AddValue(*fsp->GetFilename(), std::move(fsp));
```

I'm closing the issue definitively now since it's fully answered and last questions were bonuses.
