### ISSUE TITLE
Text underline incompatibility with poppler

### ISSUE THREAD

**Issue by audaki** [podofo/podofo#197]
* **I'm submitting a:**
  - [X] Bug report

* **[Bug report] What is the current behavior?**
Since 0.10.x texts with underline (and probably strike-through) render incorrectly in poppler and poppler-using PDF viewers like Okular. The underline is rendered first, the text is positioned rightwards to the line.

* **[Bug report] What is the expected behavior?**
The the underline is under the text

* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**
A simple reproduction file created with podofo 0.10.4, but the same issue exists in master (!)
[aaa 0.10.pdf](https://github.com/user-attachments/files/17410066/aaa.0.10.pdf)

I’ve created a pull-request #196 to fix this incompatibility in 0.10.x branch, I can create the same pull-request for the master branch if helpful

PS: The code used to create this PDF is not in any way special:
```
painter.DrawTextAligned(line, x, y, width, alignment, PdfDrawTextStyle::Underline);
```

* **Please tell us about your environment:**
  
  - Version/git revision: 0.10.4
  - Operating System: Linux 64 bits
  - Package manager used: source

**Comment by audaki** [comment]
I’ve created an issue with Poppler in parallel, but even if it was fixed in Poppler, a lot of (LTS) Linux OSes will be stuck with the old poppler version:

https://gitlab.freedesktop.org/poppler/poppler/-/issues/1527

**Comment by ceztko** [comment]
I've looked at the change and it looks fine to me. I would merge it instantly if you targeted master but since you targeted 0.10.x I have to have a look at that branch because it has a unrelated incomplete fix which I want to amend first before merging yours. I will look at it later tonight.

**Comment by audaki** [comment]
> if you targeted master

I’ve recreated (via cherrypick) the pull-request for master #199 :-)

**Comment by ceztko** [comment]
Thank you for the contribution!
