### ISSUE TITLE
Bug in PdfIndirectObjectList::Create*Object if number of objects is more than 2^16

### ISSUE THREAD

**Issue by nntrifonov** [podofo/podofo#20]
Hi.

I found the following issue: the call of PdfIndirectObjectList::CreateObject function return PdfObject with wrong object number if the total amount of objects in document is more than 2^16.
The bug is in in PdfReference PdfIndirectObjectList::getNextFreeObject().
File PdfIndirectObjectList.cpp, Line 195

    uint16_t nextObjectNum = static_cast<uint16_t>(m_ObjectCount);;

Please change variable type for casting from uint16_t to uint32_t 
It should be

    uint32_t nextObjectNum = static_cast<uint32_t>(m_ObjectCount);

**Comment by ceztko** [comment]
Done, thanks. https://github.com/podofo/podofo/commit/4d5cad66d47162a48f9517f376155f69993d3030
