### ISSUE TITLE
PDF/A-3 (3u) validation failed

### ISSUE THREAD

**Issue by audaki** [podofo/podofo#202]
* **I'm submitting a:**
  - [X] Bug report

* **[Bug report] What is the current behavior?**
Validation for 3u fails

* **[Bug report] What is the expected behavior?**
Validation for 3u succeeds

* **Please tell us about your environment:**
  - Version/git revision: 0.9.8, 0.10.4 and master
  - Operating System: all
  - Package manager used: source

* **[Bug report/Feature request] Other information**
While verifying PDFs generated with Podofo we noticed the following error:

```
ValidationResult[
  flavour=3u,
  assertions=[
    TestAssertion[
      ruleId=RuleId
      [specification=ISO 19005-3:2012, clause=6.2.11.4.2, testNumber=2],
      status=failed,
      message=If the FontDescriptor dictionary of an embedded CID font contains a CIDSet stream, then it shall identify all CIDs which are present in the font program, regardless of whether a CID in the font is referenced or used by the PDF or not,
      location=Location[
        level=CosDocument,
        context=root/document[0]/pages[0](17 0 obj PDPage)/contentStream[0](18 0 obj PDContentStream)/operators[159]/font[0](BAAAAA+ArialMT)/DescendantFonts[0](BAAAAA+ArialMT)
      ],
      errorMessage=A CIDSet entry in the Font descriptor does not correctly identify all glyphs present in the embedded font subset
    ]
  ],
  isCompliant=false
]
```

We received this validation error in all three branches of PoDoFo we tested.

There is a good chance we are doing something wrong with how we embed the fonts and this is not really a bug.

But curiously the code required for fonts to be embedded has changed a lot between 0.9.8 and 0.10.4 but the error is the same regardless.

To cross-check if we are using the library wrong, our code for 0.10.4 is as follows:
```
pdf.GetMetadata().SetPdfVersion(PdfVersion::V1_7);
pdf.GetMetadata().SetPdfALevel(PdfALevel::L3U);

auto& fonts = pdf.GetFonts();
auto& arial = fonts.GetOrCreateFont("Arial.ttf");
auto& arial_bold = fonts.GetOrCreateFont("Arial Bold.ttf");
```

(It seems like in 0.10.4 fonts are embedded automatically, for 0.9.8 we had an explicit embed fonts call)

Does our code look wrong or is this an issue in PoDoFo with the CIDSet?

**Comment by ceztko** [comment]
You will not get PDF/A validation "for free" just by setting `SetPdfALevel`, but I think you know it already (as a minimum you need to set the ICC profile, and not introduce any non PDF/A compliant construct). Yes, fonts are embedded by default in 0.10.x/master. The code looks ok but I don't know what your doing right after with the font. `CIDSet` is prepared [here](https://github.com/podofo/podofo/blob/049b58f93a56497d27adeaa03bc5a0c7d013abf4/src/podofo/main/PdfFontCIDTrueType.cpp#L68), has part of TrueType font embedding.

**Comment by audaki** [comment]
I’ve made progress on this issue. We are still calling font.EmbedFonts() with podofo 0.10.x, maybe this is no longer needed, but it seems this issue is unrelated.

I’ve made the simplest possible PDF that validates, and used the following 2-letter text:

`painter.DrawText("aa", 42, 420);`

now, if I change only that line to the following, I get the CIDset validation error again:

`painter.DrawText("öö", 42, 420);`

Everything else is the same. Do you have an idea what this could be?

**Comment by ceztko** [comment]
I've enforced PoDoFo to produce a valid `CIDSet` that validates but I don't understand it because this included also some glyphs as part of other compound glyphs which it doesn't make sense to me to be there, as these sub glyphs may be no CID at all. Maybe  I've to work in the `CIDSystemInfo` and constraint the defined CIDs there. I've to think about it.

**Comment by ceztko** [comment]
But `CIDSystemInfo` only defines know/registered character collections, and this is a custom subset. This is a strange situation for me. We can probably make a trivial `CIDSet` which will make the validation pass (it's all 1s for the number of the glyphs in the font), but this makes me arise more questions. Maybe there's a reason why `CIDSet` was deprecated...

**Comment by ceztko** [comment]
As said `CIDSet` is deprecated in PDF 2.0, and good news is not required PDF/A compliance levels 2-3 (it's not even mentioned in PDF/A-4), but if present it has stricter requirements. It could also be that the validation is somehow incorrect, as with a font subset with no character collection defined, veraPDF will end requiring to bit set all glyphs present in the font which makes no sense to me.  So I just configured PoDoFo to not create a `CIDSet` unless targetting PDF/A-1. Leaving some testing pdfs for reference here. 

[test-noncompliant.pdf](https://github.com/user-attachments/files/17482244/test-noncompliant.pdf)
[test-compliant-fixed.pdf](https://github.com/user-attachments/files/17482245/test-compliant-fixed.pdf)
[test-compliant-nocidset.pdf](https://github.com/user-attachments/files/17482256/test-compliant-nocidset.pdf)

**Comment by audaki** [comment]
Thank you! Just as a confirmation, I have verified that this fixes the validation error in our application as well :+1:
