### ISSUE TITLE
Behavior Change: Underline / Strikethrough Color

### ISSUE THREAD

**Issue by audaki** [podofo/podofo#203]
* **I'm submitting a:**
  - [X] Bug report

* **[Bug report] What is the current behavior?**
SetFillColor only affects text color, but not underline and strikethrough color

* **[Bug report] What is the expected behavior?**
I’m not sure, is this an intended change? I think before you couldn’t set a different underline color

--

In 0.9.x this code
```
  painter.SetColor(1, 0, 0);
  painter.SetStrokingColor(0, 0, 0);
  painter.GetFont()->SetUnderlined(true);
  painter.GetFont()->SetStrikeOut(true);
  painter.DrawText(42, 420, "OIO");
```
gave you a red text with red underline and red strikethrough

![image](https://github.com/user-attachments/assets/bd2fc655-79ea-45eb-9d42-885be4577f6b)

--

In 0.10.x this code
```
  painter.GraphicsState.SetFillColor({1, 0, 0});
  painter.GraphicsState.SetStrokeColor({0, 0, 0});
  painter.DrawText("OIO", 42, 420, PdfDrawTextStyle::Underline | PdfDrawTextStyle::StrikeThrough);
```
no longer colors the underline / strikethrough.

![image](https://github.com/user-attachments/assets/107a3c7c-f67d-4721-8c7c-27c23099759f)

--

**But it is fixable by setting the stroke color(!)**
So in 0.10.x this code
```
  painter.GraphicsState.SetFillColor({1, 0, 0});
  painter.GraphicsState.SetStrokeColor({1, 0, 0});
  painter.DrawText("OIO", 42, 420, PdfDrawTextStyle::Underline | PdfDrawTextStyle::StrikeThrough);
```
gives the old result again

![image](https://github.com/user-attachments/assets/adf29464-8b34-4d43-a0b4-61344aefce4f)

--

Due to this I’m not sure if this is even a bug or a regression?

Maybe this is a good behavior change, since now we can have an underline in a different color, which wasn’t possible before

**Comment by ceztko** [comment]
The change with 0.9.x was intended. Text rendering can be affected by both "fill" (the PDF terminology is "nonstroking") and stroke/stroking color, but the default is that text is "filled" by color, see [here](https://stackoverflow.com/a/27959484/213871). I think in most rendering API one most often want to fill text and stroking really means painting text outlines. Anyway I think it's best to adhere to PDF semantics here.

**Comment by ceztko** [comment]
In master https://github.com/podofo/podofo/commit/fa875172b46ec173e409a0534fa7a7375ad56f56 I just decided to rename"Fill" -> "NonStroking" and "Stroke" -> "Stroking", to better matching PDF terminology.
