### ISSUE TITLE
PdfDocument::InsertExistingPageAt seems to append entire source file

### ISSUE THREAD

**Issue by mpmbrainydata** [podofo/podofo#208]
* **I'm submitting a:**
  Bug report

* **What is the current behavior?**
I am trying to copy a single page from 'source' file to 'destination' file and output to a 'new' file. It appears that all the resources of 'source' file are copied to 'new' file and the 'new' file becomes the total size of 'source' and 'destination'.

For example if 'source' = 525KB and 'destination' = 274KB, 'new' becomes 797KB. Using Safari to manually do the same, results in 'new' totalling merely 366KB.

* **What is the expected behavior?**
I expected the 'new' file to be similar to the size produced by Safari.

* **Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**

```
	if (pInputFile2==NULL)
		return PDF_ERR_BAD_PARAMS;
		
	using namespace PoDoFo;
	
	try
	{
		PdfMemDocument input1;
		PdfMemDocument input2;
		
		if (pInputFile1!=NULL)
			input1.Load( pInputFile1, pOutputFile == NULL ? true : false ); // dst
			
		input2.Load( pInputFile2 ); // src

		// note: pInsertPageNo & pCopyPageNo are page numbers, not indexes, hence the -1
		if (pInsertPageNo<=0)
			pInsertPageNo = input1.GetPageCount()+1;
		input1.InsertExistingPageAt( input2, pCopyPageNo-1, pInsertPageNo-1 );

		if (pOutputFile == NULL)
			input1.WriteUpdate(pInputFile1);
		else
			input1.Write( pOutputFile );
	}
	catch( PdfError & e )
	{
		gMainOutputStack->setLastFileError((qlong)e.GetError(), e.ErrorMessage(e.GetError()));
		return PDF_ERR_FAILED;
	}
	return PDF_ERR_SUCCESS;

```

* **Please tell us about your environment:**
  - Version/git revision: 0.9.7
  - Operating System: MacOs
  - Package manager used: source

* **Other information**
In my tests I copy the last page from 'src' to the end of 'destination'
Files are attached. 

My initial question is: Has this been resolved in the latest version of PoDoFo?

[_src.pdf](https://github.com/user-attachments/files/17498330/_src.pdf)
[_destination.pdf](https://github.com/user-attachments/files/17498331/_destination.pdf)
[_new.pdf](https://github.com/user-attachments/files/17498410/_new.pdf)

**Comment by ceztko** [comment]
I'm sorry, I won't do this testing because as a volunteer and the maintainer of the project I think there are limits to the support I/we should provide. I encourage to test yourself using the [playground](https://github.com/podofo/podofo/tree/master/playground), which is very easy to to compile and run. `InsertExistingPageAt` has been moved and renamed to `PdfPageCollection::InsertDocumentPageAt`, see [`API-MIGRATION.md`](https://github.com/podofo/podofo/blob/master/API-MIGRATION.md). Please re-open if you can reproduce with master.

**Comment by mpmbrainydata** [comment]
Thank you for your quick response. I fully understand and will do necessary testing with latest build as soon as I get back from a conference. I was hoping it was a known issue.

**Comment by ceztko** [comment]
Thank you for your understanding. No, I am not aware of issues in that code, mostly because I don't use it (but I've plans to rewrite it one day, because of code quality issues). I reviewed at least a couple of patches on it, though.
