### ISSUE TITLE
There are no first some drawn text on the next created pages

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#21]
Could you clarify the following situation - I create a page, do drawing on it, finish it, create second page and the same as on first one, but I don't see the text on the second page. In more complex case I see that on the second page don't draw only some first text. Look.

```cpp
#include <podofo/podofo.h>

using namespace PoDoFo;

int main()
{
	PdfMemDocument doc;

	PdfPainter painter;

	auto * font = doc.GetFonts().SearchFont( "Droid Serif" );

	auto & p1 = doc.GetPages().CreatePage( PdfPage::CreateStandardPageSize( PdfPageSize::A4 ) );

	painter.SetCanvas( p1 );

	painter.BeginText( 50, 750 );
	painter.GetTextState().SetFont( *font, 24 );
	painter.AddText( "Hello World!!!" );
	painter.EndText();

	painter.FinishDrawing();

	auto & p2 = doc.GetPages().CreatePage( PdfPage::CreateStandardPageSize( PdfPageSize::A4 ) );

	painter.SetCanvas( p2 );

	painter.BeginText( 50, 750 );
	painter.GetTextState().SetFont( *font, 24 );
	painter.AddText( "Hello World!!!" );
	painter.EndText();

	painter.FinishDrawing();

	doc.Save( "1.pdf" );

	return 0;
}
```

And the result of this application:

[1.pdf](https://github.com/podofo/podofo/files/10436700/1.pdf)

OK, I'm sorry for your time, maybe at this time I should do my homework again?

**Comment by ceztko** [comment]
This time you did your homework very well! It's a bug: the state doesn't get reset on the second painter, and it should. As a workaround, you can recreate the painter.

**Comment by ceztko** [comment]
Should be fixed now.
