### ISSUE TITLE
GetOrCreateFont does not respect PdfFontSearchParams

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#214]
* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [x] Bug report
  - [ ] Feature request/suggestion

* **[Bug report] What is the current behavior?**

  I know that in master you make a development, but you broke something there. Possibly you
  know about it and it's just a WIP. But I decided to let you know. Look.

  ```cpp
    PoDoFo::PdfFontSearchParams params;
    params.Style = PoDoFo::PdfFontStyle::Regular;
    if (bold) {
        params.Style.value() |= PoDoFo::PdfFontStyle::Bold;
    }
    if (italic) {
        params.Style.value() |= PoDoFo::PdfFontStyle::Italic;
    }

    auto *font = doc->GetFonts().SearchFont(name.toLocal8Bit().data(), params);
  ```

  Always return regular font, does not matter what is set in `params`.

* **[Bug report] What is the expected behavior?**

  I'd like to see styled font as in PoDoFo 0.10.4.

* **Please tell us about your environment:**
  
  - Version/git revision: [master]
  - Operating System: [Linux 64 bits]
  - Package manager used: [none]

**Comment by ceztko** [comment]
```
params.Style.value() |= PoDoFo::PdfFontStyle::Bold;
```

It may be not related to your issue, but that's a bad semantics to use the `nullable` type and the support for doing this may be dropped, even after 1.0. A preferable code is:

```
PoDoFo::PdfFontSearchParams params;
// In general it's preferable to not set and explicit style and leave null
//params.Style = PoDoFo::PdfFontStyle::Regular;
if (bold)
    params.Style = PoDoFo::PdfFontStyle::Bold;

if (italic)
    params.Style = PoDoFo::PdfFontStyle::Italic;
```

Tell me if this changes anything (it probably won't).

**Comment by igormironchik** [comment]
> Tell me if this changes anything (it probably won't).

No. It doesn't change. I checked on commit 27390e5d7685fb93956eadbd85c424988edb8b5e , as HEAD can not be build (issue with include directory `3rdparty`, and on Linux GCC requires `-fPIC`).

```cpp

#include <iostream>
#include <podofo/podofo.h>

int main()
{
	PoDoFo::PdfMemDocument doc;

	try {
        auto & p = doc.GetPages().CreatePage(
            PoDoFo::PdfPage::CreateStandardPageSize( PoDoFo::PdfPageSize::A4 ) );
        auto painter = std::make_shared< PoDoFo::PdfPainter > ();
        painter->SetCanvas( p );

        PoDoFo::PdfFontSearchParams params;
        params.Style = PoDoFo::PdfFontStyle::Italic;

        auto *font = doc.GetFonts().SearchFont("Droid Serif", params);

        painter->TextObject.Begin();
        painter->TextObject.MoveTo(70., 700.);
        painter->TextState.SetFont(*font, 14);
        painter->TextState.SetFontScale(1.0);
        painter->TextObject.AddText("Text");
        painter->TextObject.End();

        painter->FinishDrawing();

		doc.Save( "out.pfd" );
	}
	catch( const std::exception & x )
	{
		std::cout << x.what() << std::endl;
	}

	return 0;
}
```

**Comment by ceztko** [comment]
Do I need to compile `3rdparty` with `-fPIC`? This wasn't spotted by a couple of CI(s) I'm running. If so, I will change it ASAP.

**Comment by igormironchik** [comment]
First:

```
FAILED: CMakeFiles/podofo-test.dir/main.cpp.o 
/usr/bin/g++-14  -I/home/igor/Work/Tmp/podofo/3rdparty/podofo/src -I/home/igor/Work/Tmp/podofo/build/Desktop-Debug/3rdparty/podofo/src/podofo -DQT_QML_DEBUG -g -std=gnu++17 -fdiagnostics-color=always -MD -MT CMakeFiles/podofo-test.dir/main.cpp.o -MF CMakeFiles/podofo-test.dir/main.cpp.o.d -o CMakeFiles/podofo-test.dir/main.cpp.o -c /home/igor/Work/Tmp/podofo/main.cpp
In file included from /home/igor/Work/Tmp/podofo/3rdparty/podofo/src/podofo/auxiliary/basetypes.h:13,
                 from /home/igor/Work/Tmp/podofo/3rdparty/podofo/src/podofo/auxiliary/StreamDevice.h:16,
                 from /home/igor/Work/Tmp/podofo/3rdparty/podofo/src/podofo/podofo.h:22,
                 from /home/igor/Work/Tmp/podofo/main.cpp:3:
/home/igor/Work/Tmp/podofo/3rdparty/podofo/src/podofo/auxiliary/span.h:5:10: fatal error: span.hpp: No such file or directory
    5 | #include "span.hpp"
      |          ^~~~~~~~~~
compilation terminated.
```

Second:

```
:-1: error: 3rdparty/podofo/3rdparty/libpodofo_3rdparty.a(faxmodule.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
```

**Comment by ceztko** [comment]
I haven't looked at your exact issue yet, but can you tell me if HEAD now compiles for you?

**Comment by igormironchik** [comment]
> but can you tell me if HEAD now compiles for you?

Hi. Builds like a charm.

**Comment by ceztko** [comment]
Ok, I triaged the issue: unfortunately it's caused by conflicting requirements and the regression was caused by changes done in https://github.com/podofo/podofo/issues/189. I have an idea for a fix, that involves searching the pattern on a list of fonts first and then fallback on best font available, but I also want to finally make some serious tests. Should come soon (next week).
