### ISSUE TITLE
Possible misuse of `PdfDocument::GetPages()`

### ISSUE THREAD

**Issue by SeekingBlues** [podofo/podofo#218]
* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [x] Bug report
  - [ ] Feature request/suggestion

Currently, it is possible for a user of the library to write the following malformed code:
```cpp
{
    PdfMemDocument doc;
    doc.Load(...);
    doc.GetPages().GetCount();    // Make sure the page list is initialized
    auto pages = doc.GetPages();  // Copy the page list
} // Double free!
```

`auto& pages` should be used to create a reference to the `PdfPageCollection` owned by the document, but since `PdfPageCollection` is copyable, the library does not prevent the programmer from making this mistake and creating a double free bug.

* **[Bug report] What is the current behavior?**

The program compiles and aborts.

* **[Bug report] What is the expected behavior?**

The program should not compile. In particular, `PdfPageCollection` should not be copyable as it contains a vector of raw pointers.

**Comment by ceztko** [comment]
Thank you, damn C++.
