### ISSUE TITLE
How to read a pdf version ?

### ISSUE THREAD

**Issue by vv3d0x** [podofo/podofo#221]
I need to read a pdf version and tried different ways, but looks like it's not possible, and hello world example is not enought. Documentation is absent.
```
document.GetMetadata().GetPdfVersion() - deleted
PdfMemDocument.GetPdfVersion - protected, (PdfMemDocument, PdfDocument are final, could not be extended)
```

**Comment by ceztko** [comment]
`doc.GetMetadata().GetPdfVersion()`

**Comment by ceztko** [comment]
Excuse me, why do you say `document.GetMetadata().GetPdfVersion() - deleted` https://github.com/podofo/podofo/blob/abb6176a18c31f708fba3c6ca673b96addc69728/src/podofo/main/PdfMetadata.h#L132 ?

**Comment by vv3d0x** [comment]
Because of:
https://github.com/podofo/podofo/blob/abb6176a18c31f708fba3c6ca673b96addc69728/src/podofo/main/PdfMetadata.h#L25

Compile error
```
 error: use of deleted function 'PoDoFo::PdfMetadata::PdfMetadata(PoDoFo::PdfMetadata&)'
  152 |     json_document.AddMember("metadata", pdf_document.GetMetadata(), allocator);
      |     ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Usa case:
```
int PageInfo(const std::string_view &filename)
{
    rapidjson::Document json_document;
    PoDoFo::PdfMemDocument pdf_document;
    
    pdf_document.Load(filename);
    json_document.SetObject();

    // must pass an allocator when the object may need to allocate memory
    rapidjson::Document::AllocatorType &allocator = json_document.GetAllocator();

    // Create object for pages
    rapidjson::Value json_pages(rapidjson::kArrayType);

    json_document.AddMember("version", pdf_document.GetMetadata().GetPdfVersion(), allocator);

    rapidjson::StringBuffer strbuf;
    rapidjson::Writer<rapidjson::StringBuffer> writer(strbuf);
    json_document.Accept(writer);

    std::cout << strbuf.GetString() << std::endl;

    return 0;
}
```

**Comment by ceztko** [comment]
You can't copy a `PdfMetadata` instance, and that's for your safety, as it would steal pointers. That's doesn't prevent you from just reading the version of the PDF. So, what's your problem? I'm sorry I don't understand. Also your second snippet seems like it will avoid the compilation error you reported just few lines above.

**Comment by vv3d0x** [comment]
I'm a noob in c++, need to fix some program which using v0.9.8 )) and I cannot compile with last snippet of code because compiler sais: " error: use of deleted function 'PoDoFo::PdfMetadata::PdfMetadata(PoDoFo::PdfMetadata&)'"
I made an investigatiion and found than cannot read a version. No examples, and only api docs, for me not informable (((

**Comment by ceztko** [comment]
> I made an investigation and found that cannot read a version

This is factually not true: as said you can call `doc.GetMetadata().GetPdfVersion()` and you will receive the PDF version of the document. Try with a simple program: it will just work. If, trying to integrate with a 3rd party library, you have compilation errors because of lack of understanding of C++ I'm sorry but you'll have to improve your knowledge first. Please, don't complain more than necessary.

**Comment by vv3d0x** [comment]
I tried extra simple example:
```
int main(int argc, char *argv[])
{
    try
    {
        PoDoFo::PdfMemDocument document;
        document.Load('foobar.pdf');

        std::cout << "version: " << document.GetPdfVersion() << std::endl;

        return -1;
    }
    catch (const PdfError &err)
    {
        err.PrintErrorMsg();

        return static_cast<int>(err.GetCode());
    }

    return 0;
}
```

I stil facing an issue while compile:
```
error: 'virtual PoDoFo::PdfVersion PoDoFo::PdfMemDocument::GetPdfVersion() const' is protected within this context
  214 |         std::cout << "version: " << document.GetPdfVersion() << std::endl;
```
