### ISSUE TITLE
Issue creating page contents stream

### ISSUE THREAD

**Issue by splashwizard** [podofo/podofo#224]
Fill the form below, removing parts that don't apply, including this note.
Please note that PoDoFo is currently activelly developed and maintained only
by a single person. The quickest and safest way to ensure bugs that
affects you are fixed and the features you need are checked-in is to
[contribute](https://github.com/podofo/podofo#contributions) high-quality patches.

* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [x] Bug report
  - [ ] Feature request/suggestion

* **[Bug report] What is the current behavior?**
GetOrCreateStream() method fails on execution.
Here is the code I've used.

PoDoFo::PdfMemDocument pdfDoc;

        // Create a new page in the document
        auto& page = pdfDoc.GetPages().CreatePage(PoDoFo::PdfPage::CreateStandardPageSize(PoDoFo::PdfPageSize::A4));

        // Create a PdfObject for the page's content
        PoDoFo::PdfObject& object = page.GetContents()->GetObject();

        // // Ensure the object is a dictionary (required for streams)
        // if (object.GetDataType() != PoDoFo::ePdfDataType_Dictionary) {
        //     object.SetDataType(PoDoFo::ePdfDataType_Dictionary); // Convert to a dictionary
        // }

		auto& stream =  object.GetOrCreateStream();
    	auto output = stream.GetOutputStream();

When I call object.GetOrCreateStream() I got the error "Segmentation fault". Should I set data type of object using dictionary?

Looking forward ~immediate~ your attention please.

Thanks

* **[Bug report] What is the expected behavior?**
The code works without any error.

* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**

* **[Feature request] What feature should be implemented in PoDoFo?**

* **Please tell us about your environment:**
  
  - Version/git revision: [1.10.0]
  - Operating System: [all | Windows (32/64 bits) | Linux (32/64 bits) | MacOs]
  - Package manager used: [source | vcpkg | conan | apt | yum]

* **[Bug report/Feature request] Other information**

  E.g. sample PDF documents, stacktraces, related issues, links for us to have contex, suggestions how to fix, etc.

**Comment by ceztko** [comment]
Please, don't use words like _immediate_ or _urgent_ again writing request supports to open source projects anymore. Today it's your lucky day anyway but be warned that I will snooze other similar requests. To create a new stream for appending content in the page you can use the following code:

```
PoDoFo::PdfMemDocument pdfDoc;
auto& page = pdfDoc.GetPages().CreatePage(PoDoFo::PdfPage::CreateStandardPageSize(PoDoFo::PdfPageSize::A4));
auto& streamForAppending = page.GetOrCreateContents().CreateStreamForAppending();
```
