### ISSUE TITLE
Using writer.write function in newer version

### ISSUE THREAD

**Issue by splashwizard** [podofo/podofo#225]
Fill the form below, removing parts that don't apply, including this note.
Please note that PoDoFo is currently activelly developed and maintained only
by a single person. The quickest and safest way to ensure bugs that
affects you are fixed and the features you need are checked-in is to
[contribute](https://github.com/podofo/podofo#contributions) high-quality patches.

* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [ ] Bug report
  - [ ] Feature request/suggestion

* **[Bug report] What is the current behavior?**
Here is the code that worked with Podofo 0.9.7, How can I rewrite to work in Podofo 0.10.4?
BOOST_FOREACH(DocInfoKey k, tdocuments)
{
	k.second->SetWriteMode(PoDoFo::ePdfWriteMode_Clean);
	k.second->Write(k.first.c_str());
}

* **[Bug report] What is the expected behavior?**
* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**

* **[Feature request] What feature should be implemented in PoDoFo?**

* **Please tell us about your environment:**
  
  - Version/git revision: [1.10.0]
  - Operating System: [all | Windows (32/64 bits) | Linux (32/64 bits) | MacOs]
  - Package manager used: [source | vcpkg | conan | apt | yum]

* **[Bug report/Feature request] Other information**

  E.g. sample PDF documents, stacktraces, related issues, links for us to have contex, suggestions how to fix, etc.

**Comment by ceztko** [comment]
There's a `PdfMemDocument::Save(filename, flags)` method. Among the flags there's also a `PdfSaveOptions::Clean` entry. There's a [API-MIGRATION](https://github.com/podofo/podofo/blob/master/API-MIGRATION.md#098---0100) document that should list the API changes between 0.9.x and 0.10.x. In case your API change is not listed there try to lurk the new headers, as many changes are very easy in nature.
