### ISSUE TITLE
PdfPostSciptTokenizer returns false and doesn't read PHPVariants

### ISSUE THREAD

**Issue by splashwizard** [podofo/podofo#226]
Fill the form below, removing parts that don't apply, including this note.
Please note that PoDoFo is currently activelly developed and maintained only
by a single person. The quickest and safest way to ensure bugs that
affects you are fixed and the features you need are checked-in is to
[contribute](https://github.com/podofo/podofo#contributions) high-quality patches.

* **I'm submitting a:**
  - [ ] Bug report

* **[Bug report] What is the current behavior?**
PoDoFo::PdfPostScriptTokenizer * tokenizer = new PoDoFo::PdfPostScriptTokenizer(spBuffer, PdfPostScriptLanguageLevel::L1 );
PoDoFo::charbuff streamBuffer;
PoDoFo::SpanStreamDevice device(streamBuffer);
PoDoFo::PdfPostScriptTokenType eType;
std::string_view keyword;
   auto var = std::make_unique<PoDoFo::PdfVariant>();
while ( tokenizer->TryReadNext ( device, eType, keyword, *var) ) {
}

Here is the content of spBuffer. I got false for TryReadNext method and can't get content of while loop running.
In PoDoFo 0.9.7 it works and I can get while loop running.

q
0 0 0 1 k
BT
/Ft5 27.552362 Tf
50 30 Td
<02> Tj
-50 -30 Td
100 20 Td
<03> Tj
-100 -20 Td
150 10 Td
<04> Tj
-150 -10 Td
ET
Q

Thank you for your reading.

* **[Bug report] What is the expected behavior?**

* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**

* **[Feature request] What feature should be implemented in PoDoFo?**

* **Please tell us about your environment:**
  
  - Version/git revision: [1.10.0]
  - Operating System: [all | Windows (32/64 bits) | Linux (32/64 bits) | MacOs]
  - Package manager used: [source | vcpkg | conan | apt | yum]

* **[Bug report/Feature request] Other information**

  E.g. sample PDF documents, stacktraces, related issues, links for us to have contex, suggestions how to fix, etc.

**Comment by ceztko** [comment]
I've seen you closed yourself the issue so you probably sorted already. As you noticed, the buffer argument is not the buffer where the content will be read (I  just documented it in master). The content is always fed by the streaming read methods in the input `device` argument. Also `PdfPostScriptTokenizer` is today quite low level. I recommend you to the `PdfContentStreamReader` ([here](https://github.com/podofo/podofo/blob/a344e94ecb51e7ad07249ce2af1bff19ad92d3a2/src/podofo/main/PdfPage_TextExtraction.cpp#L193C5-L193C28) an example of use.

**Comment by splashwizard** [comment]
Hi Francesco,

Thank you so much for reviewing my previous issue. Could you kindly check
this one too? https://github.com/podofo/podofo/issues/228

I look forward to hearing from you, I really need your help fixing this
issue.

Best regards,

Paul

**Comment by splashwizard** [comment]
Hi Francesco,

Could we have a real-time chat? I have questions to ask about the Podofo
library and would like to ask on Google Chat, skype discord or whatever
platform you like.

I will compensate you for your support using this library. I really need
this project using the Podofo library done asap so I would really
appreciate it.

Waiting for your kind reply,

Paul
