### ISSUE TITLE
PdfDocument::CreateXObjectForm doesn't create xObject elements in PDF

### ISSUE THREAD

**Issue by splashwizard** [podofo/podofo#227]
Hi!
I created a PDF page using PoDoFo v0.10.4 using below code but it doesn't create XObject element.
Below is my code.

```
PoDoFo::PdfMemDocument * targetDoc;
PoDoFo::PdfPage* sourcePage(&sourceDoc -> GetPages().GetPageAt(sourcePageNr));
xobj = targetDoc->CreateXObjectForm(sourcePage->GetMediaBox());
targetDoc->Save("imposed_doc.pdf");
```

When I open imposed_doc.pdf I don't see /Type /XObject contents I assume I should see the content like below but I can't see content like this in PDF file. Please advise me what could be wrong here. I hope to create XObject element in PDF file soon.
```
5 0 obj
<<
/Type /XObject
/BBox [ 0.000000 0.000000 400.000000 400.000000 ]
/FormType 1
/Matrix [ 1 0 0 1 0 0 ]
/Resources <<
/ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]
>>
/Subtype /Form
>>
endobj
```

**Comment by ceztko** [comment]
This is by design, as you didn't use the indirect object created as the result of calling `CreateXObjectForm` in any place in the document. Use the XObject in any way that it will be referenced in the document and the object will be preserved upon saving.

**Comment by splashwizard** [comment]
> This is by design, as you didn't use the indirect object created as the result of calling `CreateXObjectForm` in any place in the document. Use the XObject in any way that it will be referenced in the document and the object will be preserved upon saving.

@ceztko could you give some code that add reference of created XObject to the document?

**Comment by ceztko** [comment]
Well...you should have learned by yourself at this point. `PdfPainter::DrawXObject()` or `PdfAnnotation::SetAppearanceStream()` are examples of methods that will end referencing the XObject form in the document. You can also do it manually calling `PdfDictionary::AddKeyIndirect("Key", xobj->GetObject())` anywhere in the document, provided you access a dictionary in a document bound object. That may make sense or not depending on where you insert the reference to the created XObject.
