### ISSUE TITLE
`GetFonts().SearchFont()` works wrongly

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#23]
On my Ubuntu 22.04 the following code:

```cpp
PdfMemDocument doc;

auto * font = doc.GetFonts().SearchFont( "Noto Sans" );

auto & metrics = font->GetMetrics();
std::cout << "The font name is "<< metrics.GetFontNameSafe() << std::endl;
std::cout << "The family font name is " << metrics.GetFontFamilyName() << std::endl;
std::cout << "The font file path is " << metrics.GetFilePath() << std::endl;
std::cout << "The font face index is " << metrics.GetFaceIndex() << std::endl;
```

Produces:

```
The font name is NotoSansAdlam-Regular
The family font name is Noto Sans Adlam
The font file path is /usr/share/fonts/truetype/noto/NotoSansAdlam-Regular.ttf
The font face index is 0
```

What is wrong as I searched for `Noto Sans` font and got `Noto Sans Adlam`, both of which are installed on my system, and place in the same folder `/usr/share/fonts/truetype/noto/`. There I have `NotoSansAdlam-Regular.ttf` and `NotoSans-Regular.ttf`.

**Comment by ceztko** [comment]
Some research would be needed so searching the font with `PdfFontManager`, which internally uses [fontconfig](https://www.freedesktop.org/wiki/Software/fontconfig/) as a first choice in all platforms, returns the desired font in most of the cases people use this functionalities. The remaining cases where searching the font with `PdfFontManager` fails should be dealt by manually loading a specific font from a filepath/buffer, or by loading a face with the overloads accepting a `FT_Face`, which means one can search the fonts directly using fontconfig and better specifying the search pattern/options there. Previous PoDoFo 0.9.x fontconfig search code is [here](https://github.com/podofo/podofo/blob/5723d09bbab68340a3a32923d90910c3d6912cdd/src/podofo/doc/PdfFontCache.cpp#L823) and was searching for font family name. I updated it to search postscript name in PoDoFo [0.10-dev](https://github.com/podofo/podofo/blob/3c3e39a48f146e1e236ba66afdb6af96e5781256/src/podofo/base/PdfFontConfigWrapper.cpp#L46), which behaved slightly better in my case returning more fonts, but other than this the code stayed pretty much the same. Maybe there are a couple of consderations here:

- Maybe I'm wrong assuming that fontconfig will return the "best" font as the first of the found font list;
- Maybe font family name found search would return better font in your case.

I need to experiment, or you can support me by using the playground and inspecting fontconfig font results. For now, I have little resources/time to investigate this issue, so I'm prioritizing the other bugs you found.

**Comment by igormironchik** [comment]
Some commands on my Ubuntu:

```bash
igor@gmi:/usr/share/fonts/truetype/noto$ fc-scan ./NotoSansAdlam-Regular.ttf | grep postscriptname
        postscriptname: "NotoSansAdlam-Regular"(s)
igor@gmi:/usr/share/fonts/truetype/noto$ fc-scan ./NotoSans-Regular.ttf | grep postscriptname
        postscriptname: "NotoSans-Regular"(s)
igor@gmi:/usr/share/fonts/truetype/noto$ fc-scan ./NotoSansAdlam-Regular.ttf | grep family
        family: "Noto Sans Adlam"(s)
        familylang: "en"(s)
igor@gmi:/usr/share/fonts/truetype/noto$ fc-scan ./NotoSans-Regular.ttf | grep family
        family: "Noto Sans"(s)
        familylang: "en"(s)
igor@gmi:/usr/share/fonts/truetype/noto$ 
```

```cpp
pattern = FcPatternBuild(0, FC_POSTSCRIPT_NAME, FcTypeString, fontName.data(),
	FC_WEIGHT, FcTypeInteger, (isBold ? FC_WEIGHT_BOLD : FC_WEIGHT_MEDIUM),
	FC_SLANT, FcTypeInteger, (isItalic ? FC_SLANT_ITALIC : FC_SLANT_ROMAN),
	static_cast<char*>(0));
```

returns `Noto Sans Adlam` font, whereas

```cpp
pattern = FcPatternBuild(0, FC_FAMILY, FcTypeString, fontName.data(),
	FC_WEIGHT, FcTypeInteger, (isBold ? FC_WEIGHT_BOLD : FC_WEIGHT_MEDIUM),
	FC_SLANT, FcTypeInteger, (isItalic ? FC_SLANT_ITALIC : FC_SLANT_ROMAN),
	static_cast<char*>(0));
```

returns expected `Noto Sans` font.

I guess that `FC_FAMILY` works better, and looks for that that user expects.

**Comment by ceztko** [comment]
I understand. As said, there are situations where searching postscript name search finds fonts, where only searching family returns no fonts. We have to find a something that combines both results.

**Comment by igormironchik** [comment]
I'd suggest to use `FC_FAMILY` first, and `FC_POSTSCRIPT_NAME` only if first attempt fails. As I see the situation, `Noto Sans` is a usual font, that should be searched with string `Noto Sans`. Postscript name search searches first alphabetical record, that  is `NotoSansAdlam`, that is a font just for special characters...

**Comment by ceztko** [comment]
Please try https://github.com/podofo/podofo/commit/a08b110f224f0a04e935638372512b33464c91e2 and tell me how it works for you now. Also it seems your issue finding "aakar " when searching "Arial" is solved.

I moved back to search with FC_FAMILY pattern only but changed [`FcConfigSubstitute`](https://www.freedesktop.org/software/fontconfig/fontconfig-devel/fcconfigsubstitute.html) to use `FcMatchPattern` as match kind, similary to what it does [`fc-match`](https://github.com/freedesktop/fontconfig/blob/e291fda7d42e5d64379555097a066d9c2c4efce3/fc-match/fc-match.c#L188) tool. This seems to have improved the quality of the result of the query. Unfortunately these enums are not very documented but reading [this](https://lists.freedesktop.org/archives/fontconfig/2018-July/006304.html) message on the ML it seems `FcMatchPattern` will do some more magic to select the best font, which is what we are looking for.

**Comment by igormironchik** [comment]
> Please try [a08b110](https://github.com/podofo/podofo/commit/a08b110f224f0a04e935638372512b33464c91e2) and tell me how it works for you now. Also it seems your issue finding "aakar " when searching "Arial" is solved.

Good job! `Noto Sans` is searched as it should be. `Arial` on my Ubuntu now finds as `LiberationSans`, that is good! Thanks.

**Comment by ceztko** [comment]
Wonderful! PoDoFo 0.9.x [was](https://github.com/podofo/podofo/blob/5723d09bbab68340a3a32923d90910c3d6912cdd/src/podofo/doc/PdfFontCache.cpp#L836) using `FcMatchFont` when doing `FcConfigSubstitute`, which also produced strange results. For example searching "Arial Unicode MS" in my linux system returned "Suruma", which doesn't make sense at all. With `FcMatchPattern` it matches "DejaVu Sans" which makes much more sense. I think we can consider the issue closed and behavior improved compare to PoDoFo 0.9.x .

**Comment by igormironchik** [comment]
> I think we can consider the issue closed and behavior improved compared to PoDoFo 0.9.x .

Sure.
