### ISSUE TITLE
Shine `CMakeLists.txt` a little

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#24]
Just an idea, it's not a bug, but possible improvement.

In your `CMakeLists.txt` you use, for example:

```cmake
find_package(LibXml2 REQUIRED)
message("Found libxml2 library at ${LIBXML2_LIBRARIES}, headers ${LIBXML2_INCLUDE_DIRS}")

# The podofo library needs to be linked to these libraries
# NOTE: Be careful when adding/removing: the order may be
# platform sensible, so don't modify the current order
set(PODOFO_LIB_DEPENDS
    ${OPENSSL_LIBRARIES}
    ${Fontconfig_LIBRARIES}
    ${FREETYPE_LIBRARIES}
    ${LIBXML2_LIBRARIES}
    ${PNG_LIBRARIES}
    ${TIFF_LIBRARIES}
    ${JPEG_LIBRARIES}
    ${ZLIB_LIBRARIES}
    ${PLATFORM_SYSTEM_LIBRARIES}
)
```

Let consider on the example with `LibXml2` - you set include directories by hands, and use `LIBXML2_LIBRARIES` variable to link to. OK.
On Linux this is not a problem, all works like a sharm. But on Windows, for example, in conjunction with `Conan` it doesn't work, and I see unresolves...

But if refuse from variables like `LIBXML2_LIBRARIES` and `LIBXML2_INCLUDE_DIRS`, and simple use the following CMake code:

```cmake
set(PODOFO_LIB_DEPENDS
  LibXml2::LibXml2
)
```

Everything begin work on every platform without issues. And you can use `Conan` to do a test CI build for Windows platform with ease.

What do you think?

**Comment by ceztko** [comment]
I think show me a PR, but should absolutely not break the playground, brew, vcpkg. I recently added the [latter](https://github.com/podofo/podofo/actions/runs/3975330394) and it works so I don't understand why Conan fails, anyway if it's just a better way to specify includes and libraries why not?

**Comment by igormironchik** [comment]
Will do it ASAP. I don't work at Sundays at all, so guess, that it will happen at Monday.
