### ISSUE TITLE
PdfDifferenceEncoding::Create throws exception for Font with StandardEncoding

### ISSUE THREAD

**Issue by nntrifonov** [podofo/podofo#26]
Hi,

PdfDifferenceEncoding::Create throws the exception with the following description:

`PoDoFo encountered an error. Error: 31PdfErrorCode::InvalidFontData	Error Description: The font data is invalid.	Callstack:	#0 Error Source : main/PdfDifferenceEncoding.cpp: 2516		Information: Invalid /BaseEncoding StandardEncoding`

for the following Font object

```
390 0 obj
<<
/Type /Font
/BaseFont /HPDFAB+Symbol_A
/Encoding <<
/Type /Encoding
/BaseEncoding /StandardEncoding
/Differences [  32 /space  33 /exclamdown  34 /cent  35 /sterling  36 /currency
 37 /yen  38 /brokenbar  39 /section  40 /dieresis  41 /copyright
 42 /ordfeminine  43 /guillemotleft  44 /logicalnot  45 /hyphen  46 /registered
...
 122 /fa  123 /fb  124 /fc  125 /fd  126 /fe
 127 /ff  132 /Ntilde ]
>>
/FirstChar  32
/FontDescriptor  552 0 R
/LastChar  255
/MissingWidth  806
/Subtype /TrueType
/Widths [  0  0  0  0  0  0  0  0  0  0
 ...
 0  0  0  0 ]
>>
endobj
```

Could you please add "StandardEncoding" processing in PdfDifferenceEncoding::Create.

**Comment by ceztko** [comment]
Please, attach a full sample Pdf demonstrating the issue and instructions used.

**Comment by nntrifonov** [comment]
PDF file example:
[issue26x.pdf](https://github.com/podofo/podofo/files/10481335/issue26x.pdf)

\> podofotxtextract issue26x.pdf
```
Error: An error 31 ocurred during processing the pdf file.
ERROR:

PoDoFo encountered an error. Error: 31PdfErrorCode::InvalidFontData     Error Description: The font data is invalid.    Callstack:      #0 Error Source : main/PdfDifferenceEncoding.cpp: 2516
        Information: Invalid /BaseEncoding StandardEncoding
```
The issue is in Font /F3 -- 7 0 obj
...
**/BaseEncoding /StandardEncoding**
...

**Comment by ceztko** [comment]
Should have been fixed but text will still not be extracted correctly, if there's a correct way to extract symbol text. A more robust treatment of difference encoding is also still missing, see:

https://github.com/podofo/podofo/blob/2294b6930ed77e3f5ec9a89d9143db9014aacb9d/src/podofo/main/PdfDifferenceEncoding.cpp#L25
