### ISSUE TITLE
Global declared object of OpenSSLInit class (PdfEncrypt.cpp) can throw exception from constructor and crash application on start

### ISSUE THREAD

**Issue by nntrifonov** [podofo/podofo#27]
Hi!

There is an OpenSSLInit class in PdfEncrypt.cpp and the global s_SSL object of this class.
Class has a constructor that can throw an exception. The problem is that it cannot be catched because s_SL constructor is called before main(). In case of an error during initialization of OpenSSL, the program crashes before the start of main().
It is better to redesign OpenSSLInit.

**Comment by ceztko** [comment]
This risk of failures during static fields initialization may be considered acceptable in some cases but I understand your point since here we are calling an external library. An improvement here may come later (0.11): I have some code parked that will move the init in a common place to be called in various places.

**Comment by igormironchik** [comment]
![ssl](https://user-images.githubusercontent.com/11455533/230128672-6f12eb54-c6be-4f2a-9dcf-9780e466663c.png)

Confirm, this is exactly this issue.

**Comment by ceztko** [comment]
Ok, please understand that moving to lazy initialization won't fix this issue for you. You must bind to a openssl build that has legacy algorithms, or lazily crash in PoDoFo only if RC4 algorithms are needed by the actual document but OpenSSL support is not available. Patches welcome to add the latter.

**Comment by igormironchik** [comment]
> Ok, please understand that moving to lazy initialization won't fix this issue for you.

Sure, thanks. `OpenSSL` from `Conan` is unusable...

**Comment by ceztko** [comment]
It is workable with some modifications to PoDoFo, but it won't work with RC4 encrypted documents. You can point out this to the Conan index.

**Comment by nntrifonov** [comment]
Hi!
OpenSSL 3 tries to load legacy.dll. If it is not in path it returns NULL and PoDoFo throws exceptions. 
Set OPENSSL_MODULES system variable to specify the path to DLL.

**Comment by Mr-Rayman** [comment]
Just a feedback to this issue (I'm not sure where to put it and I didn't want to create a new issue yet):

As of lib PoDoFo 0.10.3 using Windows, the behavior described in this issue remains.  If legacy.dll is not available or OPENSSL_MODULES environment variable is not set, then any application linked against PoDoFo will crash hard without any further notice or error messages upon start.

This is my backtrace:

![podofo](https://github.com/user-attachments/assets/6acb4b16-9cac-48f9-8a8b-2cf14b194bdc)
