### ISSUE TITLE
`PdfPainter::Circle()` doesn't draw

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#29]
Hello,

Either I didn't do my homework again, or I caught a bug again. But in `PoDoFo` 0.9.x such approach worked.

In the following code I don't see and actual circle in the resulting PDF. But I don't see the result in KDE's Okular PDF viewer,
whereas in Firefox I see the circle. Not sure which this issue is. I will reboot under Windows to check this file there...

I'm there... Adobe Acrobat Reader doesn't draw the circle too, so I guess this is your issue.

```cpp
#include <podofo/podofo.h>

using namespace PoDoFo;

int main()
{
	PdfMemDocument doc;

	PdfPainter painter;

	auto & page = doc.GetPages().CreatePage(
		PdfPage::CreateStandardPageSize( PdfPageSize::A4 ) );

	painter.SetCanvas( page );

	painter.GetGraphicsState().SetFillColor( PdfColor( 0.0, 0.0, 0.0 ) );
	painter.Circle( 100.0, 750.0, 20.0 );
	painter.Fill();

	painter.FinishDrawing();

	doc.Save( "1.pdf" );

	return 0;
}
```

The result of this application:

[1.pdf](https://github.com/podofo/podofo/files/10490352/1.pdf)

**Comment by ceztko** [comment]
It's definitely a regression. I see the content stream is written with some draw commands. I don't know exactly what's wrong since I have little experience with PDF vectors drawing but for sure it's something simple. Can you supply the result of the same code (or similar) with 0.9.x and attach it here so I will quickly see what's wrong and fix it right away? Sorry but I haven't compiled old PoDoFo for more than 1 year.

>Either I didn't do my homework again
Yes, don't worry.

**Comment by igormironchik** [comment]
Code with `PoDoFo` 0.9.x:

```cpp
#include <podofo/podofo.h>

using namespace PoDoFo;

int main()
{
	PdfMemDocument doc;

	PdfPainter painter;

	auto * page = doc.CreatePage(
				PdfPage::CreateStandardPageSize( ePdfPageSize_A4 ) );

	painter.SetPage( page );

	painter.SetColor( PdfColor( 0.0, 0.0, 0.0 ) );
	painter.Circle( 100.0, 750.0, 20.0 );
	painter.Fill();

	painter.FinishPage();

	doc.Write( "1.pdf" );

	return 0;
}
```

The result:

[1.pdf](https://github.com/podofo/podofo/files/10497978/1.pdf)

**Comment by ceztko** [comment]
Thank you, should be fixed now. Notice I added this to the TODO:

```
- PdfPainter: Make Circle(), Arc(), Rectangle alctual Draw()
  functions (and not "add to path" functions) and add a facility
  to create a path (eg. PdfPainterPath, with AddLine, AddArc, etc.)
  and close it automatically.
```

I'm sorry, but 0.9.x `PdfPainter` API was, at best, just sketched. In the end PdfPainter will more look like .NET [`Graphics`](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.graphics) class.
