### ISSUE TITLE
Possible bugs?

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#38]
```cpp
void PdfPainterPath::AddLineTo(double x1, double y1, double x2, double y2)
{
    checkClosed();
    beginPath(*m_stream, x1, x2);
    addLine(*m_stream, x2, y2);
    closePath(*m_stream);
}
```

```
/home/igor/Work/Projects/md-pdf/3rdparty/podofo/src/podofo/main/PdfPainter.cpp:1216: warning: unused parameter ‘y1’ [-Wunused-parameter]
/home/igor/Work/Projects/md-pdf/3rdparty/podofo/src/podofo/main/PdfPainter.cpp: In member function ‘void PoDoFo::PdfPainterPath::AddLineTo(double, double, double, double)’:
/home/igor/Work/Projects/md-pdf/3rdparty/podofo/src/podofo/main/PdfPainter.cpp:1216:50: warning: unused parameter ‘y1’ [-Wunused-parameter]
 1216 | void PdfPainterPath::AddLineTo(double x1, double y1, double x2, double y2)
      |                                           ~~~~~~~^~
```

```cpp
void PdfPainterPath::AddCubicBezierTo(double x1, double y1, double x2, double y2, double x3, double y3, double x4, double y4)
{
    checkClosed();
    beginPath(*m_stream, x1, y2);
    addCubicBezier(*m_stream, x2, y2, x3, y3, x4, y4);
    closePath(*m_stream);
}
```

```
/home/igor/Work/Projects/md-pdf/3rdparty/podofo/src/podofo/main/PdfPainter.cpp:1230: warning: unused parameter ‘y1’ [-Wunused-parameter]
/home/igor/Work/Projects/md-pdf/3rdparty/podofo/src/podofo/main/PdfPainter.cpp: In member function ‘void PoDoFo::PdfPainterPath::AddCubicBezierTo(double, double, double, double, double, double, double, double)’:
/home/igor/Work/Projects/md-pdf/3rdparty/podofo/src/podofo/main/PdfPainter.cpp:1230:57: warning: unused parameter ‘y1’ [-Wunused-parameter]
 1230 | void PdfPainterPath::AddCubicBezierTo(double x1, double y1, double x2, double y2, double x3, double y3, double x4, double y4)
      |                                                  ~~~~~~~^~
```

**Comment by ceztko** [comment]
Thank you. The compiler wasn't reporting warnings as it should. I will enable `/W4` in MSVC.

**Comment by ceztko** [comment]
The naming of the functions are still subjected to change I can do shortly. I'm trying to find a consistent naming scheme, inspiring from [`CanvasRenderingContext2D`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D) and [`Graphics`](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.graphics?view=windowsdesktop-7.0). I won't fully copy one API, I'll try to get the best from both worlds.

**Comment by igormironchik** [comment]
I keep hands on pulse. :)

**Comment by ceztko** [comment]
I reworked the `PdfPainter` API again and hopefully this should settle. Graphics and text states are now accessibly trough `PdfPainter::GraphicsState` and  `PdfPainter::Text`.  I moved creation of continuous paths to `PdfPainterPathContext` and creation of continuous text to `PdfPainterTextContext`. Everything should look like more beautiful and elefant to use. Examples of use:

https://github.com/podofo/podofo/blob/259c5a6c1af57e960a45e64136367e8f0b849552/test/unit/PainterTest.cpp#L145

**Comment by igormironchik** [comment]
Got it. Thanks.

**Comment by ceztko** [comment]
I still inform you here about few more changes to PdfPainter API, hopefully last ones before 0.10. Before that it should be just bugfixing. New API use:

https://github.com/podofo/podofo/blob/f4278e006b76e5b0883b36d4c014ff382c688223/test/unit/PainterTest.cpp#L155

**Comment by ceztko** [comment]
Sorry, part of the changes didn't survive a good sleep. I actually reverted some moves of the `DrawText` like functions, so there should be less changes necessary (if any).

https://github.com/podofo/podofo/blob/1b5f14b686ea3c1275bc8f261b4c924ff63371a6/test/unit/PainterTest.cpp#L155
