### ISSUE TITLE
PODOFO_API declaration for PdfContentsReader

### ISSUE THREAD

**Issue by nntrifonov** [podofo/podofo#40]
Hi!

I tried to compile my project with MSVC and found that PdfContentsReader class `was not included in DLL.
The issue is in declaring the class without the PODOFO_API specifier.
Please add PODOFO_API to class declaration in PdfContentsReader.h +79

`class PODOFO_API PdfContentsReader final`

**Comment by ceztko** [comment]
Fixed in https://github.com/podofo/podofo/commit/cc29e1802db9358eb300e0c24ba2c991bdf080d2
