### ISSUE TITLE
Please add BeginMarkedContentWithProperties function

### ISSUE THREAD

**Issue by nntrifonov** [podofo/podofo#41]
Hi!

There are functions BeginMarkedContext and EndMarkedContext in PdfPainter class corresponding to BMC and EMC commands.
Could you please add BeginMarkedContextWithProperties function for BDC command?
And also, it might be better to rename *Conte_x_t to *Conte_n_t.

```
void PdfPainter::BeginMarkedContentWithProperties(const string_view& tag)
{
    checkStatus(StatusDefault);
    m_stream << "/OC /" << tag << " BDC" << endl;
}
```

**Comment by ceztko** [comment]
My bad, wrong issue in commit message (and there's auto close of issues enabled).

> And also, it might be better to rename *Conte_x_t to *Conte_n_t.

Done in https://github.com/podofo/podofo/commit/5f653f4d73a87068945849e2e78b83659556ed6a

> Could you please add BeginMarkedContextWithProperties function for BDC command?

Not with the signature you suggest. The standard says:

> Begin a marked-content sequence with an associated property list, terminated by
a balancing EMC operator. tag shall be a name object indicating the role or
significance of the sequence. properties shall be either an **inline dictionary**
representing the property list or a **name** object associated with it in the
Properties subdictionary of the current resource dictionary

So we need an API supporting all possibilities.

**Comment by ceztko** [comment]
This could be done with a couple of new overloads:

```
void BeginMarkedContent(const string_view& tag, const PdfDictionary& dict);
void BeginMarkedContent(const string_view& tag, const PdfName& propsName, const PdfObject& dictobj);
```

The first requires serializing the dictionary to the stream. The second would require update of the `/Resources` dictionary, and it could be a bit controversial, since we have to specify the name each time we want to use that property dictionary and update the resources, because we don't have an object wrapping a property dictionary with a name. I don't know if it's worth adding such wrapper or not.

Before 0.10, we could decide to **not** decide, adding just the first overload and a back door to `PdfPainter` so you can add whatever raw content you want to the stream.

**Comment by nntrifonov** [comment]
> void BeginMarkedContent(const string_view& tag, const PdfDictionary& dict);

Fine

> void BeginMarkedContent(const string_view& tag, const PdfName& propsName, const PdfObject& dictobj)

May be make it simpler? Something like
`void BeginMarkedContent(const string_view& tag, const PdfName& propsName)` 

On my mind it is too complex to automatically fill /Resources /Properties dict for page and /Catalog /OCProperties /OCSs /D /OFF /Order for document. But it is not difficult to fill it manually.

Back door is a good idea for PdfPainter, something like 

`
void PdfPainter::Custom(const string_view& data)
{
    checkStatus(StatusDefault);
    m_stream << data; // without endl or space at the end
}
`

It is much better than my current solution -- `BeginMarkedContext("OC /oc1 BDC %")`

**Comment by ceztko** [comment]
> May be make it simpler? Something like...
> void BeginMarkedContent(const string_view& tag, const PdfName& propsName)

I don't like it. Methods like that would be in violation of the validations I introduced in the painter API.

> Back door is a good idea for PdfPainter, something like...
> 

Yeah, but that's not what I have in mind. There is a more elegant solution:

```
PdfStringStream tempStream;
PdPainter painter(tempStream);
painter.SetCanvas(page);
// ... regular paint calls
// Use the backdoor
tempStream << "/OC /oc1 BDC" << endl;
```

I think it should work.

**Comment by nntrifonov** [comment]
Hm,

```
PdfPainter *GetCorruptPainterExample(PdfCanvas &canvas)
{
    PdfStringStream tempStream;
    PdfPainter *painter = new PdfPainter(tempStream);
    painter->SetCanvas(canvas);
// ...
    return painter;
}
```

IMHO PdfPainter::GetStream will be better. And also, PdfPainter::Custom is more safe, because the implementation is hidden, plus one can perform a validation inside Custom before write.

**Comment by ceztko** [comment]
For now I ended adding the functionality with a low level interface that can be retrieved directly from `PdfPainter`. You can use it like this:

```
PdfPainter painter;
// ...
auto& operators = static_cast<PdfContentStreamOperators&>(painter);
operators.BDC_Operator("OC", "oc1");
```

You can find all implemented operators [here](https://github.com/podofo/podofo/blob/master/src/podofo/main/PdfContentStreamOperators.h) (a few are still missing).
