### ISSUE TITLE
Default values of CMAKE_CXX_FLAGS with MSVC

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#45]
By default for MSVC `CMAKE_CXX_FLAGS` are `/DWIN32 /D_WINDOWS /W3 /GR /EHsc`. If to generate with cmake makefiles for `nmake`, i.e `cmake -G "NMake Makefiles" ...` the during compilation I see a lot of annoying warnings:

```
cl : Command line warning D9025 : overriding '/W3' with '/W4'
```

Do you know how to solve this annoying issue?

**Comment by ceztko** [comment]
I can't really reproduce. `CMAKE_CXX_FLAGS` for me is `/DWIN32 /D_WINDOWS /GR /EHsc`. Please, look at this [answer](https://stackoverflow.com/a/65898398/213871), and ensure you have at least `cmake_minimum_required(VERSION 3.15)`.

**Comment by igormironchik** [comment]
I had in my top `CMakeLists.txt`:

```cmake
cmake_minimum_required( VERSION 3.1 )
```

Changing it to:

```cmake
cmake_minimum_required( VERSION 3.19 )
```

Solved the issue.

Thank you.
