### ISSUE TITLE
Fail to sign encrypted pdf

### ISSUE THREAD

**Issue by ferencIOS** [podofo/podofo#47]
Hi all!

**What am i trying to do?**

I'm trying to sign a pdf that has the `Encrypt` tag, no password required.

**What do I get as a result?**

Trying to open the file via adobe it asks me for the password! (as the attached screenshot shows).
I know this is a new feature, podofo 0.9.x didn't have it. I'm very happy that there is!

If it helps, I signed the pdf with pdfbox (the apache competitor) and it does it correctly. Below you will find the various tags

**Original PDF** (one `Encrypt` Tag)

```c++
<<
/Size 29
/Root 28 0 R
/Info 27 0 R
/ID [<7231d95de66746b883dcfd744dac9e79><7231d95de66746b883dcfd744dac9e79>]
/Encrypt <<
/Filter /Standard
/V 2
/R 3
/Length 128
/P -44
/O (IfB˪�`��>\r��Ū����S�[�����)
/U (����\\Ѝ��[���)
>>
```

**Signed by PDFBox** (two `Encrypt` Tag: original + the new one)

```c++
<<
/Size 34
/Root 28 0 R
/Info 27 0 R
/ID [<7231D95DE66746B883DCFD744DAC9E79> <EDEC786C73023ABD9311A040299FE408>]
/Encrypt <<
/Filter /Standard
/V 2
/R 3
/Length 128
/P -44
/O <491E6642CBAAD460B1B43E0D97ADC5AAD9D2C297E61A9753AB5BC1A2FCDE0BF8>
/U <D21B8494AF5CD08DA1A45B159B1CDCDF00000000000000000000000000000000>
>>
/Prev 203073
>>
```

**Signed by PoDoFo** (two `Encrypt` Tag: original + the new one)

```c++
<<
/Encrypt 39 0 R
/ID[<7231D95DE66746B883DCFD744DAC9E79><D0439FD37B50BF9818F12D47DC2DEA78>]
/Info 27 0 R
/Prev 203073
/Root 28 0 R
/Size 40
>>
```

(it's actually a single line: `<</Encrypt 39 0 R/ID[<7231D95DE66746B883DCFD744DAC9E79><D0439FD37B50BF9818F12D47DC2DEA78>]/Info 27 0 R/Prev 203073/Root 28 0 R/Size 40>>`)

[adobe.zip](https://github.com/podofo/podofo/files/10708966/adobe.zip)

I also tried to read chapter [7.6 Encryption](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf) to look for a fix but it's not a simple topic.

**Comment by ceztko** [comment]
Thank you for the research. Please also attach all the working and non working pdfs so they will be easily inspectable. This is an interesting topic but it's low priority for me and I don't have the resources to do it, right now.

**Comment by ferencIOS** [comment]
ok I found a sample secured pdf [here](https://uwaterloo.ca/onbase/help/sample-pdf-documents)

These the results:

[samplesecured.pdf](https://github.com/podofo/podofo/files/10710013/samplesecured.pdf)
[samplesecured-Signed-pdfbox.pdf](https://github.com/podofo/podofo/files/10710010/samplesecured-Signed-pdfbox.pdf)
[samplesecured-Signed-podofo.pdf](https://github.com/podofo/podofo/files/10710012/samplesecured-Signed-podofo.pdf)

**Comment by ferencIOS** [comment]
Hi, I did not forget!  I haven't found a solution but I hope to give some useful hints.

Looking at the `samplesecured.pdf` and the two files signed by pdfbox and by PoDoFo the substantial difference is represented by the object:
```
6 1 obj
<</CF<</StdCF<</AuthEvent/DocOpen/CFM/AESV3/Length 32>>>>/Filter/Standard/Length 256/O<9EF36ED0D632E6D2F520D564ADDDF94FB3793E667832EBBFC977E0A13AB77A313DF4A2824721DC8FAF533F9B3599DBCC>/OE<3526E597E1D35623A92C61FF651EBE06C541B929C16EDF0106E869F218297E83>/P -3392/Perms<9C2A1F313E4E64608091C22711F6D473>/R 5/StmF/StdCF/StrF/StdCF/U<D2CFC4C207107A06F09ED9EE0F31E1A38B72A3048030F45D88518668F240538291B2B8EB03D7D60C3241776714CB4436>/UE<91D91A1B147CAC7DFE4B24A03A25297B71C5745DE8A387F7461A0F2F815B0AB5>/V 5>>
```

This object is created by PoDoFo following the
```
void PdfEncryptSHABase::CreateEncryptionDictionary(PdfDictionary& dictionary) const
```
and is used to create later:
```
24 1 obj
<</Type/XRef/Encrypt 6 1 R/Filter/FlateDecode/ID[<CC5 [...]
```

Why is the `6 1 obj` created?
How does pdfbox use the `23 0 obj` directly?

-------------------------------------------------------------------

A few info extracted with podofo:

`void PdfParserObject::checkReference(PdfTokenizer& tokenizer)`
```
DEBUG: The PDF file is encrypted
WARNING: Found object with reference 0 0 R different than reported 23 0 R in XRef sections
```

`void PdfMemDocument::initFromParser(PdfParser& parser)`
```
DEBUG: <</Type/XRef/Encrypt 23 0 R/Filter/FlateDecode/ID[<CC56D8A7F574DE7ED75787D94BF65288><CC56D8A7F574DE7ED75787D94BF65288>]/Index[ 2 18 21 4]/Info 2 0 R/Length 76/Root 21 0 R/Size 25/W[ 1 2 1]>>
```

Trying to open the signed file
```
PoDoFo encountered an error. Error: 7PdfErrorCode::InternalLogic	Error Description: An internal error occurred.	Callstack:	#0 Error Source : main/PdfParser.cpp: 97		Information: Unable to load objects from file
	#1 Error Source : main/PdfParserObject.cpp: 96		Information: Unable to parse the stream for object 22 0 R
	#2 Error Source : main/PdfEncrypt.cpp: 404		Information: Error AES-decryption data padding
```

-------------------------------------------------------------------

I tried to see what the competitors are doing too. [The closest to PoDoFo is MuPdf](https://github.com/ArtifexSoftware/mupdf/blob/master/source/pdf/pdf-crypt.c)!
[Here instead the pdfbox encryption module](https://github.com/apache/pdfbox/tree/trunk/pdfbox/src/main/java/org/apache/pdfbox/pdmodel/encryption)

**Comment by ceztko** [comment]
After a big `PdfEncrypt` rework I can confirm this is fixed and tested as well. It was related to https://github.com/podofo/podofo/issues/176.
https://github.com/podofo/podofo/commit/fcb42be7a1c9f8d7d9060d4050620c56890ff047
https://github.com/podofo/podofo/commit/e001f684364819e174d702aad080a92245af4f30

**Comment by ferencIOS** [comment]
Thank you so much 🚀
