### ISSUE TITLE
Too large glyph size with /MissingWidth

### ISSUE THREAD

**Issue by nntrifonov** [podofo/podofo#55]
Hi,

it looks like PoDoFo incorrectly calculates the glyph size if it is defined with /MissingWidth.
PdfFontMetricsObject.cpp +114

It may be better to move reading down after FontMatrix read and multiply MissingWidth by m_Matrix[0].

            m_DefaultWidth = descriptor->GetDictionary().FindKeyAs<double>("MissingWidth", 0) * m_Matrix[0];

**Comment by ceztko** [comment]
Your request is reasonable, but also attach the pdf where you are having the issue (or craft one).

**Comment by ceztko** [comment]
I made the change. Please still update a sample pdf (and test).
