### ISSUE TITLE
PoDoFo throws exception on doc with obj with Fl encoding

### ISSUE THREAD

**Issue by nntrifonov** [podofo/podofo#56]
Hi!

I found the PDF document with Fl encoding of stream.
It crashes doc load in PoDoFo.

> PDF Reference 1.7
> APPENDIX H
> 3.3, “Filters”
> 9. Acrobat viewers accept the abbreviated filter names shown in Table H.1 in
> addition to the standard ones. Although the abbreviated names are
> intended for use only in the context of inline images (see Section 4.8.6, “Inline Images”), they are also accepted as filter names in any stream object.

The sample PDF is in the attachment [fl.pdf](https://github.com/podofo/podofo/files/10813384/fl.pdf).
**> podofotxtextract fl.pdf**
> 
> Error: An error 33 ocurred during processing the pdf file.
> ERROR:
> 
> PoDoFo encountered an error. Error: 33PdfErrorCode::UnsupportedFilter   Callstack:      #0 Error Source : main\PdfParserObject.cpp: 96          Information: Unable to parse the stream for object 9 0 R
>         #1 Error Source : private\PdfDeclarationsPrivate.cpp: 382               Information: Fl

**Comment by ceztko** [comment]
In the now disappearing "Adobe® Supplement to the ISO 32000 BaseVersion: 1.7 ExtensionLevel: 3" (I uploaded it in the podofo resources [repo](https://github.com/podofo/podofo-resources/blob/master/TechDocs/adobe_supplement_iso32000.pdf)). The wording is different:

> Acrobat viewers accept the abbreviated filter names shown in table titled “Abbreviations for standard
filter names” in addition to the standard ones. These abbreviated names are intended for use only in
the context of inline images (see Section 4.8.6, “Inline Images”), they **should not** be used as filter names
in any stream object.

Regardless, I will leniently accepting the short names.

**Comment by ceztko** [comment]
Are you generating that [fl.pdf](https://github.com/podofo/podofo/files/10813384/fl.pdf)? It has multiple violations of the PDF specification. For example it has an inline font in the resource dictionary which shouldn't happen (it should be an indirect object). Also it has a spurious `Q` operator in the page stream. As usual Adobe is very lenient, so PoDoFo will have to be lenient as well, but I recommend fix those issues.

**Comment by nntrifonov** [comment]
Thank you for fixes.

Yes, I made test file in text editor.
The original files are huge and I combined several issues in one small file for test purpose.

Why do you think that inline font is not valid?

**Comment by ceztko** [comment]
> Why do you think that inline font is not valid?

The specification is less clear than I hoped with regard to this point. Let say the wording and the examples strongly suggest resources in resource dictionaries should be referenceable with indirect references, and code implementations may leverage on this. It's clear that Adobe and most other PDF implementations are lenient so I guess you can keep inline fonts at your liking, but having them indirect would be best for compatibility.

**Comment by nntrifonov** [comment]
It was a surprise to me that it is possible to declare a font directly in dictionary.
The original file was generated by PDF-XChange Editor and I think that this is strange but valid declaration.
As I see in PDF Refernce 1.7:

3.2.9 Indirect Objects
Any object in a PDF file **may be** labeled as an indirect object. This gives the object
a unique object identifier by which other objects can refer to it (for example, as an
element of an array or as the value of a dictionary entry).

3.7.2 Resource Dictionaries
...
Each key in a resource dictionary is the name of a resource type, as shown in
Table 3.30. The corresponding values are as follows:
• For resource type ProcSet, the value is an array of procedure set names
• For all other resource types, the value is a subdictionary. Each key in the subdictionary is the name of a specific resource, and **the corresponding value is a PDF object associated with the name**

5.1.1 Basics of Showing Text
... The Tf operator specifies the name of a font resource—that is, an entry in the Font
subdictionary of the current resource dictionary. The value of that entry is a **font
dictionary**.

**Comment by nntrifonov** [comment]
But! )))
In PDF Refernce 1.0 I found:

6.8 Resources
...
Each key in the Resources dictionary is a resource type, whose value is a dictionary
or an array. If it is a dictionary, it contains keys that are resource names and values
that are **indirect references** to the PDF objects specifying the resources.

The same in 1.1 and 1.2. Only indirect reference.
But since version 1.3, it is not prohibited

3.7.2 Resource Dictionaries
...
Each key in a resource dictionary is the name of a resource type, as shown in
Table 3.20. For most resource types, the corresponding value is a subdictionary
whose keys, in turn, are the names of resources of the given type and whose
values are the PDF objects representing those resources.

**Comment by ceztko** [comment]
Thank you for the research. In several places when it make sense the specification points that objects should be indirect reference, and I was convinced it was a similar case. My implementation for caching fonts benefits from fonts being indirect, which is definitely the most used case, and store fonts differently when they are inline, using a slightly less efficient indexing method. As said, it really doesn't matter that much to me: in the end I obey to what Adobe does.
