### ISSUE TITLE
cmake build failing with "missing: OPENSSL_CRYPTO_LIBRARY"

### ISSUE THREAD

**Issue by blackandwhitebg** [podofo/podofo#57]
On Windows (x64), I tried to build with OpenSSL 3.0.7 - it failed.
I also tried 1.1.1s (exactly the one from the podofo-deps repository)
Still getting the same error:
  _Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  version "1.1.1s")_

This is what I use for the CMake arguments:
-DOPENSSL_INCLUDE_DIR=C:\PoDoFo\podofo-deps-master\3rdparty\openssl\include
-DOPENSSL_CRYPTO_LIBRARY=C:\PoDoFo\podofo-deps-master\3rdparty\openssl\lib\Win64\crypto.lib

**Comment by blackandwhitebg** [comment]
I made some progress,

I found that if I use a prebuilt OpenSSL library from a different place, and not from "podofo-deps",
using parameter "-DOPENSSL_ROOT_DIR=C:\OpenSSL-Win64" works. 

So basically the bug is that the OpenSSL part from podofo-deps is incomplete

**Comment by ceztko** [comment]
Please note the [disclaimer](https://github.com/podofo/podofo-deps#disclaimer).

> These dependencies are supplied only for development purposes and come with no warranty. They are not frequently updated, may contain security flaws and be unsafe to use.

The openssl builds there are fine but the libs/includes directory layout may be incompatible with your attempt to hint the cmake find module for OpenSSL. I will better specify that the deps there are supposed to be used with the [playground](https://github.com/podofo/podofo/tree/master/playground) only. I will also improve the build/quickstart guide to encourage to use package managers, such as vcpkg and Conan.

**Comment by blackandwhitebg** [comment]
Ok, this is the workaround I found:
Copy the 4 lib files from
`\podofo-deps-master\3rdparty\openssl\lib\Win64`
to
`\podofo-deps-master\3rdparty\openssl\lib\`

And you are OK to use `-DOPENSSL_ROOT_DIR=C:\PoDoFo\podofo-deps-master\3rdparty\openssl`

Additionally, I found that
`-DFREETYPE_INCLUDE_DIRS=C:\PoDoFo\podofo-deps-master\3rdparty\freetype\include`
is not creating a working VS solution, it has to be
`-DFREETYPE_INCLUDE_DIRS=C:\PoDoFo\podofo-deps-master\3rdparty\freetype\include\freetype2`

That way I was able to compile and run the HelloWorld example.

**Comment by ceztko** [comment]
I updated the relevant Readme [section](https://github.com/podofo/podofo#development-quickstart) read it carefully. I also update the disclaimer about [`podofo-deps`](https://github.com/podofo/podofo/tree/master/playground#disclaimer) in the playground. I am assuming you'll be able to continue on your own, especially in case of dependencies build from sources, for which I can't really provide support.
