### ISSUE TITLE
PdfFontConfigWrapper.cpp has #include <fontconfig/fontconfig.h> for undefined PODOFO_HAVE_FONTCONFIG

### ISSUE THREAD

**Issue by blackandwhitebg** [podofo/podofo#58]
I`ve been experimenting with different types of builds.

According to the documentation fontconfig is optional for Windows, but PdfFontConfigWrapper.cpp fails to compile because it includes its header, ignoring the fact that 
podofo_config.h has /* #undef PODOFO_HAVE_FONTCONFIG */

**Comment by ceztko** [comment]
Fixed, but please consider that fontconfig may be no more optional at some point.
