### ISSUE TITLE
Incorrect include in PdfVersion.h

### ISSUE THREAD

**Issue by angelaschmid** [podofo/podofo#60]
When compiling podofobrowser I ran into an issue with _/usr/local/include/podofo/main/PdfVersion.h:28_
which should be:

`#include <podofo/auxiliary/podofo_config.h>`

**Comment by ceztko** [comment]
Unfortunately this will break internal builds, so I'll have to find another solution, but it's something urgent so I will do it right after. Also please keep in mind that podofobrowser has not been ported to PoDoFo 0.10.

**Comment by ceztko** [comment]
Please, retest with an hello world program, or any program that you're sure it should work with PoDoFo 0.10.

**Comment by angelaschmid** [comment]
@czetko
I am only interested to get a working podofobrowser.
I managed to compile podofobrowser just some minutes ago with podofo@RELEASE_0_9_7, but the tree does not work correct.
With which other podofo tag/commit is podofobrowser (latest commit, Oct 30, 2021) compatible?
I also wrote a question in gitter.

**Comment by ceztko** [comment]
Sorry, podofobrowser is a currently an unrelated project. Things may change later but this means I have no clues on it's working conditions. Latest PoDoFo 0.9.x series stable version is 0.9.8. I also recommend to look for the branch [0.9.x](https://github.com/podofo/podofo/tree/0.9.x) for the latest fixes.

**Comment by angelaschmid** [comment]
@ceztko, Thanks. Compiled podofobrowser successful with the 0.9.x branch.
