### ISSUE TITLE
`OpenSSL` 3.x.x support

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#63]
`Qt` 6.5.0 has arrived, and I'm unable to use this version of `Qt` in my application because `PoDoFo` requires `OpenSSL` 1.x.x,
whereas `Qt` 6.5.0 built with `OpenSSL` 3.x.x.

So I ask you to add support of `OpenSSL` 3.x.x to `PoDoFo`.

**Comment by ceztko** [comment]
OpenSSL 3.x support is already there. Please read [this](https://github.com/podofo/podofo/issues/54#issuecomment-1441458039) message.

**Comment by igormironchik** [comment]
Hmm, I saw a strange message once... Please give me some hours to check everything. I'll report and close the issue if everything is fine.

**Comment by igormironchik** [comment]
OK, I see that `PoDoFo` supports `OpenSSL` 3.x. On `Linux` and `MacOS` tests passed. On `Windows` I caught strange [error](https://stackoverflow.com/questions/75940066/what-versions-of-3rdparty-libs-qt-6-5-0-was-built-with-on-windows).

This is not your issue, I believe...

**Comment by ceztko** [comment]
Of course, even it the problem is early caused by #27 (and we will improve it moving it to lazy lazy initialization), the OpenSSL binary must satisfy some [requirements](https://github.com/podofo/podofo/blob/10d7dab388de9cc2600dca19b74a92f2f3cddb98/src/podofo/main/PdfEncrypt.cpp#L57).
