### ISSUE TITLE
Required TrueType table missing

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#65]
* Install attached `Droid Serif` fonts on Windows.
* Try to use `Droid Serif` font to generate `PDF`.
* And you will cought exception:

```cpp
void PdfFontTrueTypeSubset::InitTables()
{
    ...

    if ((tableMask & ReqTable::all) == ReqTable::none)
        PODOFO_RAISE_ERROR_INFO(PdfErrorCode::UnsupportedFontFormat, "Required TrueType table missing");
}
```

What interesting is that if use `doc->GetFonts().GetOrCreateFont()` with these fonts - everything is fine, but using them from
`doc->GetFonts().SearchFont()` when they installed in the system - exception throws.

Could you clarify this situation?

Thanks.

[droid_serif.zip](https://github.com/podofo/podofo/files/11182738/droid_serif.zip)

I use

* `freetype/2.13.0`
* `fontconfig/2.14.2`

on Windows, if it makes sense.

**Comment by igormironchik** [comment]
I started to investiagte the problem. 

```cpp
string PdfFontConfigWrapper::SearchFontPath(const string_view fontPattern,
    const PdfFontConfigSearchParams& params, unsigned& faceIndex)
```

found wrong font `C:/Windows/fonts\YuGothM.ttc`, `fontPattern` is `Droid Serif`, 4 facets of this font installed in:

```
C:\Users\igorm\AppData\Local\Microsoft\Windows\Fonts
```

where I have:

```
 Directory of C:\Users\igorm\AppData\Local\Microsoft\Windows\Fonts

08/04/2023  09:20    <DIR>          .
08/04/2023  09:20    <DIR>          ..
29/03/2023  14:41           302,688 courier_new_mc_serif.ttf
29/03/2023  14:41           172,532 droid_serif.ttf
29/03/2023  14:41           184,836 droid_serif_bold.ttf
29/03/2023  14:41           177,176 droid_serif_italic.ttf
29/03/2023  14:41           189,916 droid_serif_italic_bold.ttf
               5 File(s)      1,027,148 bytes
```

**Comment by igormironchik** [comment]
Installing `Droid Serif` font for all users into `C:\Windows\Fonts` solves the problem...

**Comment by ceztko** [comment]
I see you are using fontconfig and that you installed the font as normal users (meaning the font is in your local user folder, not in `C:\Windows\Fonts`. Can you try edit the default fontconfig [here](https://github.com/podofo/podofo/blob/2571cdb504d63de96c3de2326839a845b9049739/src/podofo/main/PdfFontConfigWrapper.cpp#L119) to be like the following and retry?

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <dir>WINDOWSFONTDIR</dir>
    <dir>WINDOWSUSERFONTDIR</dir>
    <dir prefix="xdg">fonts</dir>
    <cachedir>LOCAL_APPDATA_FONTCONFIG_CACHE</cachedir>
    <cachedir prefix="xdg">fontconfig</cachedir>
</fontconfig>
```

**Comment by ceztko** [comment]
If you already installed the font in the system dir and you want to try my suggestion, uninstall it first.

**Comment by igormironchik** [comment]
> ```xml
> <?xml version="1.0"?>
> <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
> <fontconfig>
>     <dir>WINDOWSFONTDIR</dir>
>     <dir>WINDOWSUSERFONTDIR</dir>
>     <dir prefix="xdg">fonts</dir>
>     <cachedir>LOCAL_APPDATA_FONTCONFIG_CACHE</cachedir>
>     <cachedir prefix="xdg">fontconfig</cachedir>
> </fontconfig>
> ```

This works!
