### ISSUE TITLE
[podofo-0.10.0]a SIGSEGV error occurs

### ISSUE THREAD

**Issue by longuu9** [podofo/podofo#67]
When using podofopdfinfo to parse a PDF file, a SIGSEGV error occurs. By debugging with gdb, it was found that the error occurred at line 163 in podofo-0.10.0/src/podofo/main/PdfObject.cpp:

if (m_IsDelayedLoadDone)

When checking the value of m_IsDelayedLoadDone with "p" command, it was found that the value was 0x31. As a boolean value, it should only be assigned either 0 or 1, but not any other numbers. Previously, PoDoFo::PdfObject::DelayedLoad was also called and executed normally, but calling this function in the getString() function would result in a failure. The specific gdb bt stack trace is as follows.

![Z_%VS`9LQ_22SJVY06P7ZFB](https://user-images.githubusercontent.com/56356572/231064295-fa5fb8c9-8b33-45ca-a670-fcd21d3cfa68.png)

**Command Input**

podofopdfinfo poc_file 

poc_file are attached.

**Environment**

- OS: Ubuntu 20.04.1
- clang:12.0.0
- podofo:0.10.0

[poc_file.zip](https://github.com/podofo/podofo/files/11196911/poc_file.zip)

**Comment by ceztko** [comment]
See https://github.com/podofo/podofo#podofo-tools

**Comment by longuu9** [comment]
Although we discovered this bug while using podofopdfinfo, the issue is actually occurring in the core code of the PoDoFo library, rather than in the PoDoFo tools.

**Comment by ceztko** [comment]
Sorry, that was too quick triage, but I am actually not expecting people to use tools at all in this moment so I am a bit surprised to see them mentioned in bug reports.

**Comment by ceztko** [comment]
Should be fixed with https://github.com/podofo/podofo/commit/3759eb6aae7c01f2d8670f16ac46f5e116c7f468 .
