### ISSUE TITLE
compilation difficulties on macOS

### ISSUE THREAD

**Issue by artificiel** [podofo/podofo#68]
hello! looked in the issues and did not find references to this problem:

I'm compiling on macOS 13.1 / arm64 from the instructions here: https://github.com/podofo/podofo/blob/c52bbff74c211ac792a4f81dee7760adbdf45389/README.md?plain=1#L87-L97

and get to the last step, but block here:

```make
[ 26%] Building CXX object src/CMakeFiles/podofo_static.dir/doc/PdfAcroForm.cpp.o
In file included from /Users/brtn/source_control/podofo/src/doc/PdfAcroForm.cpp:21:
In file included from /Users/brtn/source_control/podofo/src/doc/PdfAcroForm.h:25:
In file included from /Users/brtn/source_control/podofo/src/doc/PdfElement.h:25:
In file included from /opt/homebrew/include/podofo/base/PdfObject.h:39:
In file included from /opt/homebrew/include/podofo/base/PdfParser.h:38:
/opt/homebrew/include/podofo/base/PdfTokenizer.h:107:16: error: unknown type name 'thread_local'
        static thread_local int s_nRecursionDepth; // PoDoFo is multi-threaded and requires a C++11 compiler with thread_local support
               ^
1 error generated.
gmake[2]: *** [src/CMakeFiles/podofo_static.dir/build.make:664: src/CMakeFiles/podofo_static.dir/doc/PdfAcroForm.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:761: src/CMakeFiles/podofo_static.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

also, throughout the compilation I also get a lot of warning about exception specs (maybe a clue?) such as:

```make
 warning: 'operator==' is missing exception specification '__attribute__((nothrow))' [-Wmissing-exception-spec]
```

**Comment by ceztko** [comment]
I don't know what's going on but github mac [workflow](https://github.com/podofo/podofo/blob/master/.github/workflows/build-mac.yml) so I have no doubt build should if [requirements](https://github.com/podofo/podofo#requirements) are met. From your error it seems C++17 is disabled for some reason. Ensure you haven't tweaked the project CMakeLists.txt (that's obviously unsupported).
