### ISSUE TITLE
Crash on working with outlines when merging files.

### ISSUE THREAD

**Issue by kNDC** [podofo/podofo#73]
The library does not handle the case when two files are merged, and the first does not have outlines, while the second one does. Specifically, the problem arises in [PdfDocument.cpp](https://github.com/podofo/podofo/blob/master/src/podofo/main/PdfDocument.cpp) in function append (starting from line 117): when PdfOutline* root is declared and initialised in line 183, it remains a null pointer, and as a result, line 193 tries to access non-existing memory.

The simplest solution would be of course not to generate any outlines at all in this case, but this naturally leads to the loss of information on them in the output file, and so I do not know if that would be a desirable behaviour:

if (!root) {}
else root->InsertChild(new PdfOutlines(m_Objects.MustGetObject(ref)));

**Comment by ceztko** [comment]
Please see the comment [here](https://github.com/podofo/podofo/issues/76#issuecomment-1559011559) which should apply to your issue as well.

**Comment by ceztko** [comment]
Crash fix should be done in https://github.com/podofo/podofo/commit/82e708ba9b48aac8b4c150e02f2621877343f1cd . If there are functional issues with merging files -> new issue, but remember merging should be rewritten at some point.
