### ISSUE TITLE
Infinite loop in PdfDocument::InsertDocumentPageAt

### ISSUE THREAD

**Issue by kovidgoyal** [podofo/podofo#76]
In the loop at line 219
```c++
    for (auto& obj : GetObjects())
    {
        PdfReference ref(static_cast<uint32_t>(obj->GetIndirectReference().ObjectNumber() + difference), obj->GetIndirectReference().GenerationNumber());
        auto newObj = new PdfObject(PdfDictionary());
        newObj->setDirty();
        newObj->SetIndirectReference(ref);
        m_Objects.PushObject(newObj);
        *newObj = *obj;

        PoDoFo::LogMessage(PdfLogSeverity::Information, "Fixing references in {} {} R by {}",
            newObj->GetIndirectReference().ObjectNumber(), newObj->GetIndirectReference().GenerationNumber(), difference);
        fixObjectReferences(*newObj, difference);
    }
```

You are looping over m_Objects while adding objects to it in the body of the loop. I can never remember all the semantics of C++ iterator invalidation, but that seems unlikely to be correct. And in practice i have observed that calling that function hangs in that loop, looping till out of memory.

**Comment by ceztko** [comment]
Sorry, the page append/insert functions were taken from 0.9.x, renamed as per the API review and never tested again (I don't use them, nor they were unit tested in 0.9.x). I briefly looked at those functions and personally don't like the code there, because it's hacky, and I will rewrite them in the future, but it's not a priority for me right now. If you want to commit fixes for these functions please send me a PR with a trivial test case.

**Comment by kovidgoyal** [comment]
The insert function was reliably failing but the append seems to work
for me, so have simply removed use of insert. I dont know enough about
PoDoFo internals to patch these functions, so for the moment I will
leave it as is. If you do get around to refactoring these functions,
please start with append as it is more important for me.

**Comment by kovidgoyal** [comment]
Incidentally, is there a better alternative to append I should use if I want to combine two PDF files?

**Comment by ceztko** [comment]
I think there isn't. Those functions are the correct ones for your use case.

**Comment by kovidgoyal** [comment]
I will note that append is *much* slower than insert was. I am guessing its O(n**2) vs O(n) somewhere.
