### ISSUE TITLE
pdftilingpattern code maybe mistake

### ISSUE THREAD

**Issue by steven-spec** [podofo/podofo#8]
PdfTilingPattern.cpp  at line 137 rRect.SetHeight(-pImage->GetHeight()); 
I think the right code should be rRect.SetHeight(pImage->GetHeight()); 
is it right?

**Comment by steven-spec** [comment]
Thank you for your contribution

**Comment by ceztko** [comment]
After the pdfmm -> PoDoFo merge this should be sorted out.

https://github.com/podofo/podofo/blob/55c2ffd53b9eff2ac0418b3bce1a29e9a6688359/src/podofo/contrib/PdfTilingPattern.cpp#L87
