### ISSUE TITLE
API changes confirmed for new version 0.10.0

### ISSUE THREAD

**Issue by FrankXie05** [podofo/podofo#80]
Hello, I'm one of the maintainers of vcpkg.

Recently we received an issue about the support update for version `0.10.0`.
But after our investigation we found out that version `0.10.0` has significant changes to the api of version `0.9.8`.

question:
Will this `api` name change be applied in future versions?
If it is, we will update it synchronously.

As for downstream compatibility issues, we will try our best to solve them.
https://github.com/podofo/podofo/wiki/PoDoFo-API-migration-guide/#098---0100
https://github.com/podofo/podofo#api-migration

Related: vcpkg Issue https://github.com/microsoft/vcpkg/issues/31578
Vcpkg PR: https://github.com/microsoft/vcpkg/pull/31584

**Comment by ceztko** [comment]
> question: Will this `api` name change be applied in future versions? If it is, we will update it synchronously.

Sorry but the question is not very clear to me. The `SONAME` of the library has been moved to canonical [single digit](https://github.com/podofo/podofo/blob/d4a2581e466da7ae039ee74865788042a230ee6e/CMakeLists.txt#L25).
The API is confirmed for `0.10.x`, and probably `0.11.x` too. It will change again in `1.0.x` where we hope to reach a stable, fully reviewed API. As you noticed the change `0.9.x` -> `0.10.x` is very relevant. Downstream projects maintainers should reach us in the mailing-list and/or here, and provide feedback. Some has done already. Unfortunately I'm in a critical working period so I can't devote too many resources to PoDoFo, but I will be more available this summer.

**Comment by FrankXie05** [comment]
Thank you for your reply, so what we can confirm is that the API is stable at `0.10.0`. However, there will still be changes in future versions.
For new API changes, we welcome users to submit an issue. :)

**Comment by ceztko** [comment]
I will track API changes closely in the `0.10.x` -> `1.0.x`. Sorry, but this was not possible for `0.9.x` -> `0.10.x`, as the latter is really a reimagination of the whole API.

**Comment by FrankXie05** [comment]
> I will track API changes closely in the `0.10.x` -> `1.0.x` path. Sorry, but this was not possible for `0.9.x` -> `0.10.x`, as the latter is really a reimagination of the whole API.

This is not an easy task. I will also pay attention to it whether it's `vcpkg` or `podofo`. 😊

**Comment by FrankXie05** [comment]
I will check the issues about the new version `0.10.0` of `Podofo` and see if I can be helpful.

**Comment by FrankXie05** [comment]
I have got the answer, close this issue.
