### ISSUE TITLE
When extracting text using podofo and poppler,  podofo is much slower

### ISSUE THREAD

**Issue by playgithub** [podofo/podofo#81]
Tried to extract text for one pdf page using podofo and poppler,
The time podofo takes is about 380 times to that poppler takes.

Code here:
https://github.com/playgithub/benchmarks/tree/main/podofo_vs_poppler

Anyway to improve the code above for podofo for better performance?

**Comment by ceztko** [comment]
Without the document itself being tested this report appears to be very incomplete. Yes, I suspect PoDoFo is very slow at extracting text: I profiled it once but at the time I could not find obvious bugs I could fix with few lines of code. Until this became my priority, this is an area where research and patches are very welcome. There's also a known inefficiency with documents with many pages, not really related to text extraction, that I am aware of that I want to fix, as soon as I have more time to work on PoDoFo.
