### ISSUE TITLE
tilingpattern use PdfXObject

### ISSUE THREAD

**Issue by steven-spec** [podofo/podofo#9]
i add a new method in tilingpattern, use PdfXObject replace PdfImage,  the PdfXObject is one page of a document.   but show nothing

**Comment by ceztko** [comment]
The report is very unclear, you should improve it with code showing what you are doing. Also consider I can't provide support in PDF shader rendering. You should either ask on the PoDoFo ML or try to internally debug PoDoFo and, if indeed there's a bug, send a patch if you know how to fix it.
