### ISSUE TITLE
Set metadata don't work en 0.10.0

### ISSUE THREAD

**Issue by manugc** [podofo/podofo#93]
* **I'm submitting a:**
  - Bug report

* **[Bug report] What is the current behavior?**
* When I get the metadata and make a set, the metadata is not changed in the object or in the document.

* **[Bug report] What is the expected behavior?**
* In version 0.98 it works correctly
 
  - Version/git revision: 0.10.0
  - Operating System: Windows (32/64 bits)
  - Package manager used: vcpkg

**Comment by ceztko** [comment]
Show some code in a new issue of what you expect and what you get and we can't talk about it. Before that the comment is: metadata setting works for me.
