### ISSUE TITLE
Error in Adobe Acrobat Reader if changing canvas more then 3 times.

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#94]
* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [x] Bug report
  - [ ] Feature request/suggestion

* **[Bug report] What is the current behavior?**

  The following code with `PoDoFo` from repository produces PDF on what latest Adobe Acrobat Reader complains about error on Windows 10.

  ![error](https://github.com/podofo/podofo/assets/11455533/1106ada4-2547-4bdf-9271-0f8bd746ae1c)

* **[Bug report] What is the expected behavior?**

  There should not be errors in Adobe Acrobat Reader.

* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**

  Doesn't matter what drawing will be done, changing canvas (that means finishing it) more then 3 times leads to this error message. This is ugly behaviour, comparing with `Skia`, that doesn't allow to jump from canvas to canvas at all, `PoDoFo` wins, but has this limitation...

  ```cpp
  #include <podofo/podofo.h>

  using namespace PoDoFo;

  int main()
  {
	  PdfMemDocument doc;

	  PdfPainter painter;

	  auto & page1 = doc.GetPages().CreatePage(
		  PdfPage::CreateStandardPageSize( PdfPageSize::A4 ) );

	  auto & page2 = doc.GetPages().CreatePage(
		  PdfPage::CreateStandardPageSize( PdfPageSize::A4 ) );

	  for( int i = 0; i < 4; ++i )
	  {
		  painter.SetCanvas( page1 );
		  painter.GraphicsState.SetFillColor( PdfColor( 0.5, 0.5, 0.5 ) );
		  painter.GraphicsState.SetStrokeColor( PdfColor( 0.5, 0.5, 0.5 ) );

		  painter.SetCanvas( page2 );
		  painter.GraphicsState.SetFillColor( PdfColor( 0.5, 0.5, 0.5 ) );
		  painter.GraphicsState.SetStrokeColor( PdfColor( 0.5, 0.5, 0.5 ) );
	  }

	  painter.SetCanvas( page1 );
	  painter.FinishDrawing();

	  painter.SetCanvas( page2 );
	  painter.FinishDrawing();

	  doc.Save( "out.pdf" );

	  return 0;
  }
  ```

* **Please tell us about your environment:**
  
  - Version/git revision: [da8a1b9ca8cedbf61f9a9b242608267c62de9dea]
  - Operating System: [Windows 64 bits]
  - Package manager used: [none]

**Comment by igormironchik** [comment]
Surely I can work around this issue in the code, and I will do it. Just think on the problem...

**Comment by igormironchik** [comment]
No, I guess it's impossible to work around this problem... Not sure what happening there, I can't save PDF in not compressed format (this will be one more issue soon).

**Comment by ceztko** [comment]
Were you expecting to be able to reuse the same painter on multiple pages dumping previous added content? That's not the way it's supposed to be used. The corruption is not good though. I hope to find the time to investigate the issue later.
