### ISSUE TITLE
PdfSaveOptions::NoFlateCompress doesn't work

### ISSUE THREAD

**Issue by igormironchik** [podofo/podofo#95]
* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [x] Bug report
  - [ ] Feature request/suggestion

* **[Bug report] What is the current behavior?**

  `PdfSaveOptions::NoFlateCompress` passed to `PdfMemDocument::Save()` doesn't have any effect.
`out_compresssed.pdf` and `out_not_compressed.pdf` are identical in the following example.

* **[Bug report] What is the expected behavior?**

  I'd like to see not compressed streams in output PDF. Or did I missunderstand something here?

* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**

  ```cpp
  #include <podofo/podofo.h>

  using namespace PoDoFo;

  int main()
  {
	  PdfMemDocument doc;

	  PdfPainter painter;

	  auto & page1 = doc.GetPages().CreatePage(
		  PdfPage::CreateStandardPageSize( PdfPageSize::A4 ) );

	  auto & page2 = doc.GetPages().CreatePage(
		  PdfPage::CreateStandardPageSize( PdfPageSize::A4 ) );

	  for( int i = 0; i < 4; ++i )
	  {
		  painter.SetCanvas( page1 );
		  painter.GraphicsState.SetFillColor( PdfColor( 0.5, 0.5, 0.5 ) );
		  painter.GraphicsState.SetStrokeColor( PdfColor( 0.5, 0.5, 0.5 ) );

		  painter.SetCanvas( page2 );
		  painter.GraphicsState.SetFillColor( PdfColor( 0.5, 0.5, 0.5 ) );
		  painter.GraphicsState.SetStrokeColor( PdfColor( 0.5, 0.5, 0.5 ) );
	  }

	  painter.SetCanvas( page1 );
	  painter.FinishDrawing();

	  painter.SetCanvas( page2 );
	  painter.FinishDrawing();

	  doc.Save( "out_compresssed.pdf" );

	  doc.Save( "out_not_compressed.pdf", PdfSaveOptions::NoFlateCompress );

	  return 0;
  }
  ```

* **Please tell us about your environment:**
  
  - Version/git revision: [da8a1b9ca8cedbf61f9a9b242608267c62de9dea]
  - Operating System: [Windows 64 bits]
  - Package manager used: [none]

* **[Bug report/Feature request] Other information**

  [out_compresssed.pdf](https://github.com/podofo/podofo/files/12440330/out_compresssed.pdf)
  [out_not_compressed.pdf](https://github.com/podofo/podofo/files/12440331/out_not_compressed.pdf)

**Comment by ceztko** [comment]
I believe this is a misrepresentation of what `PdfSaveOptions::NoFlateCompress` is meant to do: it's really meant to avoid compressing streams that are found plain/uncompressed when saving the document. Already compressed object won't be affected. To achieve what you want we should add an API to customize the default[1] filters that are applied when creating a stream. If you plan to add this functionality drop a note here. The default should not be global but document instance specific, and inside `PdfObjectStream` you should retrieve it from the document where the parent object belongs to.

[1] https://github.com/podofo/podofo/blob/16c74258fb92677a61876014b246ee5d4d5dd49c/src/podofo/main/PdfObjectStream.cpp#L20
