### ISSUE TITLE
PdfObject.cpp:576：Segmentation fault

### ISSUE THREAD

**Issue by Liujiahao0** [podofo/podofo#97]
I'm submitting a Bug report

[Bug report] What is the current behavior?
System prompt Segmentation fault

[Bug report] What is the expected behavior?
Extracting image from PDF Files

[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem

podofoimgextract 1.pdf out/

podofo/src/podofo/main/PdfObject.cpp：
int64_t PdfObject::GetNumber() const
{
    DelayedLoad();
    return m_Variant.GetNumber();
}

Please tell us about your environment:

Version/git revision: [0.11.0]
Operating System: Linux (64 bits)
Package manager used: [apt]
[Bug report/Feature request] Other information

The stack information is as follows：
Program received signal SIGSEGV, Segmentation fault.
PoDoFo::PdfObject::GetNumber (this=0x0) at /Oscar01/liujiahao/podofo/src/podofo/main/PdfObject.cpp:576
576         DelayedLoad();
(gdb) bt
#0  PoDoFo::PdfObject::GetNumber (this=0x0) at /Oscar01/liujiahao/podofo/src/podofo/main/PdfObject.cpp:576
#1  0x00000000004053ef in ImageExtractor::ExtractImage (this=this@entry=0x7fffffffe738, obj=..., jpeg=false)
    at /Oscar01/liujiahao/podofo/tools/podofoimgextract/ImageExtractor.cpp:95
#2  0x0000000000404e60 in ImageExtractor::Init (this=0x0, input=..., output=...) at /Oscar01/liujiahao/podofo/tools/podofoimgextract/ImageExtractor.cpp:53
#3  0x00000000004047c6 in Main (args=...) at /Oscar01/liujiahao/podofo/tools/podofoimgextract/podofoimgextract.cpp:33
#4  0x0000000000406808 in main (argc=<optimized out>, argv=<optimized out>) at /Oscar01/liujiahao/podofo/tools/private/MainEntryPoint.cpp:35

[1.pdf](https://github.com/podofo/podofo/files/12493918/1.pdf)

**Comment by ceztko** [comment]
Tools are not supported. I fixed it anyway because it was easy fix, but can you tell me how I can make more clear that bugs on tools shouldn't be reported? At least until, if it ever happen, tools are cleaned enough to be re-enabled by default in compilation.
