### ISSUE TITLE
Simply reading and saving without any opeartions on the attached PDF file causes data loss

### ISSUE THREAD

**Issue by kovidgoyal** [podofo/podofo#99]
* **I'm submitting a:**
  - [ ] Vulnerability report -> **use the specific [form](https://github.com/podofo/podofo/security/advisories/new) instead!**
  - [x ] Bug report
  - [ ] Feature request/suggestion

* **[Bug report] What is the current behavior?**
Reading the PDF file into a PDFMemdocument and then writing it out to a new PDF file reduces the size from ~4MB to 40KB and the images are lost.

* **[Bug report] What is the expected behavior?**

There is no significant file size reduction and the visual appearance of the exported PDF file is identical to the original.

* **[Bug report] Please provide the steps to reproduce and if possible a minimal reproduction code of the problem**
Call PdfMemeDocument::Load() then call PdfMemDocument::Save()

Note that loading the document reports a warning:
PoDoFoWARNING: Found object with reference 0 0 R different than reported 46 0 R in XRef sections

This probably means the PDF file is corrupted, but it is rendered correctly by every PDF program I tried. PoDoFo should ideally handle the corruption or throw an exception when trying to write instead of silently discarding the data.

* **Please tell us about your environment:**
  
  - Version/git revision: [1.10.0]
  - Operating System: [all ]
  - Package manager used: [source ]

* **[Bug report/Feature request] Other information**
The problem document:
https://bugs.launchpad.net/calibre/+bug/2035026/+attachment/5699703/+files/Sourcefile.pdf

**Comment by ceztko** [comment]
I agree, something very wrong is happening here. I'm investigating.

**Comment by ceztko** [comment]
The warning was spurious. I fixed it but it still doesn't fix the main issue.

**Comment by kovidgoyal** [comment]
Thanks :)

**Comment by ceztko** [comment]
Decryption has been been seriously broken for long time in case of big enough chunk of data (>4096 bytes) and compiler not zero initialing stack variables (which is definitely allowed to) . I put the case on unit testing. Yesterday I rushed a 0.10.2 release before noticing this issue. I consider it critical enough that a 0.10.3 is needed soon (not all bugfixing goes to 0.10.x). Let's wait until end of week and if nothing else happens I will release 0.10.3. In the mean time, if you can give some testing I would be glad.

**Comment by ceztko** [comment]
This is the [branch](https://github.com/podofo/podofo/tree/0.10.x) where 0.10.3 will be tagged.

**Comment by kovidgoyal** [comment]
Here is another issue, basically reading the PDF, updating the info dict and the XMP metadata and saving the pdf is taking extremely long: 
https://bugs.launchpad.net/calibre/+bug/2041745

Probably some quadratic algorithm somewhere. This is with 0.10.1 but I dont see anything in the changelog since then that could be relevant.
